{"kind":"deck","format":"deez.nut","version":2,"name":"History v4"}
{"kind":"note","note_type":"basic","fields":["Which statement is untrue about Jackie Robinson, who broke the color barrier in professional baseball in 1947?","When Walter Alston signed him, both Alston and Robinson received death threats."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1940s the USA began the Manhattan Project to build the first Atomic bomb. The first part of this project was to split the atom. It was accomplished by a team led by great Enricco Fermi. Where was it done?","Chicago, Illinois."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 1945 Nobel Prize in Physiology and Medicine went to three men from Oxford University who played a significant role in the discovery and development of penicillin and its use as an antibiotic. Which of these scientists did not share this prize?","Paul Winchell"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous metaphor did Winston Churchill use in the 1940s to describe what Russia did to Eastern Europe after WWII?","The Iron Curtain"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was fighting in the Revolutionary War for more than a year before the United States declared independence from Britain.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where were the first shots of the American Revolutionary War fired?","Lexington, Massachusetts"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term refers to the body of delegates from the colonies who met during the Revolutionary War until a constitutional government was finally formed near the end of the war?","The Continental Congress"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why is July 4th, 1776 considered the birthday of the United States?","because the signing of the Declaration of Independence began on that day"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT true about the Battle of Saratoga in 1777?","General George Washington was wounded while directing the American troops."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The American victory in this battle is often called the turning point of the Revolutionary War in the South.","Battle of Kings Mountain"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did the French aid the American patriots during the Revolutionary War?","all of these"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What statement is true about John Paul Jones who fought in the American Revolutionary War?","He was successful in naval warfare against the British."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What statement is true about the Treaty of Paris of 1783?","It recognized US independence."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["We may have not known the meaning of","Lady Marmalade"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The pros: this pet needed no watering, feeding, worming or grooming. You could go on a six month vacation and never have to ask your neighbor to take care of this pet. The cons: this pet could only learn how to stay and was very, very boring. Thanks to Gary Dahl, what pet sold over 1,000,000 in 1975?","Pet Rock"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where would you be if you heard Tattoo yell out, Ze plane! Ze plane!","Fantasy Island"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT a quote from Saturday Night Live?","Nanoo nanoo!"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ever since the Napoleonic wars, conscript troops were blamed for a lack of professionalism and could not be trusted. However, this changed at the 1866 battle at...?","Koniggratz"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This 1899 -1902 war marked the beginning of the decline of the British Empire","The Boer War - South Africa"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1905 the Russian fleet engaged the Japanese fleet in front of the Korean coast. In order to reach Korea, the Russian fleet had to cross half of the world from their western ports. Believing they were battling Japanese torpedo boats in the North Sea, the Russian fleet mistakenly attacked British fishing ships.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1853 the Crimean War began. Which country was not part of the coalition against Russia?","Austria"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This conflict ended in a humiliating defeat for China and forced the opening of 5 ports to international trade; Canton, Shanghai, Foochow, Ningpo, and Amoy. Which conflict was it?","The first Opium War 1839 - 1842"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Civil War raged between 1967 - 1970, costing an estimated 1 million people their lives. In the aftermath the Non-Governmental Organization Medicins sans Frontiere was created in 1971. In which country did this civil war take place?","Nigeria"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This conflict lead to the start of a period which is referred to as The Catastrophe by the defeated. Which conflict is this?","The Arab-Israel War - 1948"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On April 24th 1916 an uprising took place in this country in an attempt to gain independence from the UK. Where did this uprising take place?","Ireland; The Easter Uprising"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When and where did the Velvet Revolution take place?","1989 ; Prague ; Czechoslovakia"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The United Islamic Front for the Salvation of Afghanistan is also known as?","Northern Alliance"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During his lifetime Montesquieu (1689 -1755) was an outright critic of the French Absolutism. He put this forward in books like Lettres Persanes (Persian Letters - 1721). He also developed his own view on an ideal political system which he described in his Lesprit des Lois (on the Spirit of Laws -1748). What political system was he envisioning?","Constitutional Monarchy"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In June 1812, Napoleon Bonaparte and his Grand Armee suddenly invaded Russia at Nemel. After victories at Smolensk and Borodino, Napoleon managed to conquer Moscow without a fight. It was the start of the end of his army. After Russian refusals to come to terms and a big fire in Moscow, Napoleon was forced to retreat. The retreat turned into a complete disaster when crossing the Berezina river in November 1812. At what place did this crossing take place?","Studjanka"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On September 27th, 1779 this politician was appointed by American Congress to start negotiating peace with the British.","John Adams"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Between 1639 and 1858 Japan was largely isolated from the outside world. The port of Nagasaki was only open to Dutch and Chinese ships. In 1858 Commander Perry forced the Japanese Shogun to stop preventing trade. What was one of the results of this event?","The Meiji Restoration"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1861 Italy was finally (largely) unified with Victor Emmanuel II assuming the title of King of Italy. Who became the first Prime Minister of Italy?","Camillo di Cavour"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1876 the International Comittee of the Red Cross came into being. Which battle witnessed by one of the founders led to the foundation of the Red Cross?","The battle of Solferino June 24th, 1859"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happened at Prokhorovka on July 12th, 1943?","The biggest Tank batlle of WW II"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["July 1969 will go into history as the month man first set foot on the Moon. However, in that same month and year another momentous event took place. Which event was that?","The Nixon Doctrine is declared"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the War of Laws?","The implementation of National legislation laws vs. Soviet Union laws"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the dividing line between North and South Korea after World War Two?","the 38th parallel"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did the Korean War begin?","in 1950 when communist North Korea suddenly attacked non-communist South Korea"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Early in the Korean War, communist forces drove deep into South Korea until they were finally stopped at the perimeter surrounding this city near the southern end of Korea.","Pusan"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was US President during most of the Korean War?","Truman"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the Korean War, after stopping the original communist invasion the anti-communist forces, commanded by General MacArthur, steadily drove the North Koreans back deep into North Korea. Then the war had a new development as Communist Chinese forces attacked in force. What is the most probable reason why the Chinese decided to enter the war?","MacArthurs aggressive policies and proclamations made the Chinese fear that they themselves might be attacked by the anti-communist forces."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the Korean War, why was General MacArthur fired as commander of the anti-communist forces in Korea by the President (who is also commander-in-chief of US armed forces)?","MacArthur publicly disagreed with the Presidents policy of limited war in Korea."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement is true about the Chinese entry into the Korean War?","It pushed the anti-communist forces back rapidly all the way into South Korea."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement regarding the consequences of the Korean War is true?","When the war ended, no nation made any significant gain in territory or economic concessions. The dividing line between North and South was almost the same as when the war began."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After conquering the vast majority of Western Europe, early in World War II, the German High Command ordered the construction of a string of fortifications known as the Atlantic Wall. Parts of these barrier systems included mines, barbed wire, casemates and imitation stones. What were these imitation stones?","Camouflaged bunkers"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the 1945 siege of Berlin by Russian forces, rumors spread among the German refugees in the Berlin Underground, that Russian T-34 tanks had entered the Underground.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1944 the Allies launched a very ambitious airborne and ground campaign into the Netherlands, codenamed Operation Market Garden. Who was in direct charge of the 1st British Airborne Division?","Maj. Gen. Urquhart"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1944 the Allies launched Operation Overlord starting the liberation of Europe. When troops entered the beaches and caught their first prisoners, they were surprised to hear this language.","Russian"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the objective of Operation Hailstone that was launched in 1944 by the United States Navy?","Attack on Truk Atoll"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During World war II, Singapores defenses were so strong that it was considered to be the Gibraltar of the Pacific. However the city fell to the Japanese relatively easy on February 15th 1942. What was the main reason for this?","The Japanese assaulted Singapore over land."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During World War II V-2 Rockets were never aimed at targets outside the UK.","False"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the objective of Operation Husky launched in 1943?","The capture of Sicily"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In May 1941 the Germans used airborne divisions to invade the Island of Crete. Who was the commander of these forces?","General Kurt Student"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the codename for the amphibious assault on Normandy, France on 6 June 1944?","Neptune"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who assassinated Robert F. Kennedy on June 5, 1968?","Sirhan Sirhan"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What cartoon character made his film debut on June 9, 1934?","Donald Duck"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first horse to claim the United States Triple Crown of Thoroughbred Racing on June 11, 1919?","Sir Barton"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This corporation, initially known as the Computing-Tabulating-Recording Company, was incorporated on June 15, 1911.","IBM"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What holiday was first celebrated on June 19, 1910?","Fathers Day"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 21, 1788 the US Constitution became the law of the land when ratified by New Hampshire.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What president signed legislation providing for an 8-hour work-day applicable to federal employees on June 25, 1868?","Andrew Johnson"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who assassinated Austrian Archduke Franz Ferdinand and his wife on June 28, 1914?","Gavrilo Princip"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What soap opera moved from radio to television on June 30, 1952?","Guiding Light"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Greek mythology, Patroclus donned Achilles armor to fight against the Trojans and was killed by Hector.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did the Greeks overtake the city of Troy during the Trojan War?","They used a wooden hollow horse."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scythian monk Dennis the Little, who lived in the sixth century invented this.","Numbering years according to the life of Jesus"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these was invented by US assistant commissioner Kathy Adams?","The expression Y2K"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It can be difficult to both hold a string instrument and play it. Which of these musicians holds a patent for a device used for holding a stringed instrument?","Eddie Van Halen"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous person holds a patent for a cardiac pulse monitor?","Zeppo Marx"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous person got a patent in 2002 for a device used to tune drumheads?","Marlon Brando"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous person holds a patent for the design of an ash tray?","Lawrence Welk"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1951 this famous actor was awarded a patent for the design of a blowout toy. He was very famous for his musical comedies.","Danny Kaye"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these people holds a patent for the design of a certain toy figure?","George Lucas"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actor, who was the voice of Roger Rabbit in 1988 and did voice work in Polar Express, got a patent for a toy adapted for pulling and stretching.","Charles Fleischer"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This person worked in a patent office while in graduate school and is the co-holder of patent # 1781541 for a refrigerator.","Albert Einstein"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Few people know that this person holds a patent for a type of disposable child’s diaper.","Jamie Lee Curtis"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these people holds several patents for fishing lures?","Gary Burghoff"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Under his real name this person holds patent #140245 for an improved method for scrapbooking.","Mark Twain"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of one these people holds patent #1370316 for a divers suit?","Harry Houdini"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which musician holds a patent for an electronic device that helps a composer, a musician, or a conductor to interactively select parts of a musical score?","Harry Connick, Jr."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If you recall well the performances of these men, it won’t be hard to guess which one of them holds a patent for a device that allows a performer to lean forward past his center of gravity.","Michael Jackson"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This man holds a patent for a special Jacuzzi-type of spa bath for women that includes a chair, a circulation valve, and a device for eliminating the dirty water.","Penn Jillette"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these people was issued patent # 6469 for a new method of buoying vessels over shoals?","Abraham Lincoln"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1974, this lady got a patent for a pantyhose with a shaping band for cheeky derriere relief.","Julie Newmar"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Great Pyramid of Giza is believed to have been built as the tomb of this Egyptian pharaoh.","Khufu"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the original height of the Great Pyramid?","481 feet"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Great Pyramid is one of the pyramids of the Giza pyramid complex. Which monument is NOT a part of that complex?","The Pyramid of Amenemhet I"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where in Egypt are the Pyramids of Giza situated?","On the outskirts of Cairo"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the estimated frame of time in which the Great Pyramid was constructed?","15 - 20 years"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of the Pyramids of Giza has visibly retained its polished limestone casing at its apex?","The Pyramid of Khafre"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which peculiarity of the Great Pyramid interior distinguishes it from the other pyramids?","The ascending passages and upper chambers"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What common feature do all of the entrances of the Pyramids in Giza share?","They all face the exact north."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Towards the end of the 14th century, vandalized by an angered Sufi Muslim, the Great Sphinx of Giza lost what essential piece.","Its nose"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What word refers to the hundreds of flat-roofed Egyptian tombs built round the Pyramids of Giza?","Mastabas"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Alamo mission was captured on this day in 1836.","March 6"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sam Houston avenged the deaths of those killed at the Alamo in this battle.","Battle of San Jacinto"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did General Santa Anna escape during the battle with Sam Houston (only to be caught the next day)?","He was dressed as a peasant."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who portrayed Davy Crockett in the 1960 movie The Alamo?","John Wayne"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Dukes of Hazzard star played Thumblerig the Gambler in the 1960 movie The Alamo?","Denver Pyle"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dennis Quaid played Sam Houston in the 2004 movie The Alamo.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Richard Widmark played Jim Bowie in the 1960 movie The Alamo.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Never in the field of human conflict was so much owed by so many to so few. These words uttered by Winston Churchill refer to the bravery of the men serving in the British Royal Air Force. What is the name given to the air warfare that was carried out by the powerful Luftwaffe against the RAF","Battle of Britain"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Crusaders lost the Battle of Hattin because of the stupidity of King Guy of Jerusalem who insisted on marching the Crusaders in heavy armor through arid, waterless land and demanding the enemy come out and fight like good Christian soldiers. What Muslin leader was able to lead his quick, mobile cavalry to victory over the Knights Templar and the army of the Crusaders?","Saladin"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was on September 18,1862 that General Robert E. Lee and the Confederate Army of Northern Virgina battled General George McClellan on a cornfield near Sharpsburg, Maryland. What is the name of the battle that is often called the bloodiest single day of warfare in American history?","Antietam"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What brilliant Carthaginian general defeated the Romans in the Second Punic War at the Battle of Cannae in 216 B.C.?","Hannibal"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Duke Kazimir of Stettin, a member of the Teutonic Knights, insulted King Wladislaw II of Poland when he demanded the King come out and fight like a man. King Wladislaw answered when, by 7:00 p.m. July 15, 1410, 18,000 of the Order of Teutonic Knights were dead or dying and 14,000 of the Order were taken prisoner. Can you name this battle?","Battle of Tannenberg"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Operation Barbarossa is the largest land invasion in history. The superior German army moved further and faster than any other army in the history of modern warfare. But it was in the house-to-house and factory-to-factory fighting that the mighty German Sixth Army was defeated. What battle was the turning point for the Eastern Front in World War II?","Battle of Stalingrad"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a few minutes of time, skill and luck met over the waters of the Pacific in June 1942. American SBD Dauntless dive bombers from the USS Yorktown and Enterprise struck three Japanese carriers and put them out of action. In what decisive battle did the Japanese lose the carriers Kaga, Soryu, Akagi and the Hiryu?","Battle of Midway"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Tet Offensive was the first major defeat for the US/ARVN military forces in the Vietnam War.","False"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During this century Constantine I ruled, and Kama Sutra was created.","4th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During this century the French Revolution began, and the United States Declaration of Independence was signedd.","18th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this century paper was first produced by Chinese people, and the Silk Road between Europe and Asia was created.","2nd century BC"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this century, the Muslim conquests began, and the population on the planet was reduced to approximately 208 million people.","7th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During what century did Ramesses III, Pharaoh of Egypt, live, rule and die?","12th century BC"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This century saw the discovery of the Americas and of a sea route along Cape of Good Hope to India.","15th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this century gunpowder was first used in a battle, and lions become extinct in Europe.","10th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Roman Emperors Caligula, Augustus, Claudius and Nero lived in this century.","1st century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Great Fire of London and the Great Plague of London occurred in this century.","17th century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What century witnessed the reign of the so-called Five Good Emperors of Rome?","2nd century AD"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie won the Academy Award for Best Picture at the 61st Academy Awards ceremony held on March 27, 1989?","Rain Man"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What British actor was born on 23 July, 1989 in London, United Kingdom?","Daniel Radcliffe"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["American actress Bette Davis, who passed away on October 6, 1989, was the the first woman to be presented with this award by the American Film Institute.","Lifetime Achievement Award"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was awarded the 1989 Nobel Prize for Peace?","The 14th Dalai Lama, Tenzin Gyatso"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What notable event happened in New York City on November 7, 1989?","The first African American mayor of the city was elected."],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American Idol winner was born on December 22, 1989 in Phoenix, Arizona?","Jordin Sparks"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular artist passed away on January 23, 1989?","Salvador Dali"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name is commonly used to refer to the political events that took place in 1989 and are also known as Revolutions of 1989?","Autumn of Nations"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American rapper was born on October 4, 1989 in New York City?","Lil Mama"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first full-length episode of this popular TV sitcom premiered on Fox on December 17, 1989.","The Simpsons"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who named the Cambrian period?","Adam Sedgwick"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cambrian period lasted from 490 million years ago to 443 million years ago.","False"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term refers to the raise of biodiversity that occurred during the Cambrian period?","Cambrian Explosion"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This animal, which lived during the early Cambrian period, is possibly one of the first fish to evolve.","Haikouichthys"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the Cambrian little or nothing lived on land.","True"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Anomalocaris was a predatory arthropod of the Cambrian period which could reach a length of 100 cm or more.","False"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What ocean separated Laurentia from Baltica and Siberia during the Cambrian.","Iapetus ocean"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What caused the Cambrian-Ordovician mass extinction?","Glaciation"],"tags_json":"[\"trivia\",\"history\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
