{"kind":"deck","format":"deez.nut","version":2,"name":"General Knowledge v7"}
{"kind":"note","note_type":"basic","fields":["The wedding cake originated in ancient Rome where it was thrown at the bride or broken over her head as a sign of fertility.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In ancient times, it was common for the groom to abduct his bride. The honeymoon originated as a way for the bride and groom to go into hiding after the wedding, to keep the brides family from finding her.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The bride traditionally wears a veil, because it is considered bad luck for the groom to see the bride before the wedding.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which 1968 film starred Jane Fonda as a scantily-clad sci-fi heroine?","Barbarella"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the more common name for the superfood Vaccinium oxycoccos?","Cranberry"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If bactrian equals two, what equals one?","Dromedary"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In May 2008, this painter set a new world record for sale value of a painting by a living artist when Benefits Supervisor Sleeping was sold for $33.6 million. What is his/her name?","Lucian Freud"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which World War One battles were the first ever fought by the Australian and New Zealand Army Corps (ANZAC) as a joint force?","Gallipoli battles"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the anvil-shaped bone in the middle ear that along with the malleus and stapes allow us to hear?","Incus"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the second most important vegetable fibre after cotton that is woven to make coarse cloth and sacks?","Jute"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which 1994 film featured Jean Reno as a hitman who worked out of Little Italy in New York City and offered sanctuary to a young girl when her family was murdered by corrupt Drug Enforcement Agency agents?","Léon"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name for a vocal musical composition for between two and eight singers, written in the Renaissance and early Baroque eras and often performed without musical accompaniment?","Madrigal"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["For which hobby would you need frames, hoops and canvas?","Needlepoint"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What O-word can be added to each of the following to make a new meaningful word:","Out"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The fruit of this deciduous shrub or small tree is a berry 5 - 12 cm (2 – 4.7 inches) in diameter, with thick red skin and about 600 seeds.","Pomegranate"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which actress played the part of Teresa di Vicenzo in the James Bond film On Her Majestys Secret Service?","Diana Rigg"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What toxic chemical was released in the Tokyo subway by the Aum Shinrikyo sect in 1995?","Sarin"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character from J. R. R. Tolkien’s The Lord of The Rings: The Two Towers was also known as Fangorn and was the oldest of his kind?","Treebeard"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What commonplace object has parts called stretcher, runner and rib?","Umbrella"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country gained independence from the UK and France in 1980 and has a national anthem entitled Yumi, Yumi, Yumi?","Vanuatu"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which actor played the sinister Gabriel Sylar Gray in the TV series Heroes?","Zachary Quinto"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As a child, this singer allegedly witnessed a car accident in the desert, where a family of Native Americans were injured. He considered this incident to be the most impactful event in his life and often referred to it in his poems and songs.","Jim Morrison"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the author of The Asian Saga, a series of six epic novels centering on Europeans in Asia.","James Clavell"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What guitarist and singer fronted a band whose debut album was titled Are You Experienced?","Jimi Hendrix"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["James Dean received the first official posthumous Academy Award nomination for Best Actor for his performance in this movie.","East of Eden"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Although this author spent much of his life outside his native Ireland, his landmark novels Ulysses and A Portrait of the Artist as a Young Man are set in Dublin.","James Joyce"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these actors, named James, is not correctly matched with an Oscar-nominated role he played?","James Jim Carrey - Truman Burbank in The Truman Show"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these US Presidents had the shortest tenure?","James A. Garfield"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What prolific 19th century novelist wrote The Leatherstocking Tales, a series of novels featuring frontiersman Natty Bumppo?","James Fenimore Cooper"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these accomplishments was not made by Captain James Cook, an English explorer, navigator and cartographer?","In 1774, he became the first explorer to sight Antarctica."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement, regarding James VI of Scotland and James I of England, is true?","They are one and the same person."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who wrote, directed, and starred in the 1981 movie The Four Seasons?","Alan Alda"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who wrote the concertos called The Four Seasons?","Vivaldi"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do we call the longest day of the year?","The summer solstice"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When does the vernal equinox occur in the Northern Hemisphere?","March 20, 21, or 22"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where in the USA would you find the place that in 1921 set a North American record for the largest snowfall in a 24-hour period?","Colorado"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is a tuque?","A winter hat typically worn in Canada."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the famous Welsh poet who wrote the poem The Boys of Summer.","Dylan Thomas"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of The Eagles lead singer and drummer who wrote the song The Boys of Summer?","Don Henley"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The book The Boys of Summer tells the story of this baseball team.","The Brooklyn Dodgers"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which season did ancient Greeks celebrate Mothers Day?","Spring"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1955 pianist Roger Williams had an instrumental hit with this record.","Autumn Leaves"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Scandinavian mythology this is the equivalent of the apocalypse.","ragnarok"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who composed and performed the ballad Goodbye Yellow Brick Road?","Elton John"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A major earthquake struck this city in 1906, killing almost 3,000 people.","San Francisco"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following was not a game show host?","Walter Bradley"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many English words (not proper nouns) begin with dw?","4"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which former US President said I know Im getting better at golf because I hit fewer spectators.","Ford"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A book claiming that the story of Wilhelm Tell was just a myth was burned at the stake in Switzerland.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Spanish is an official language of this African country.","Equatorial Guinea"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Find the quote by Federico Fellini.","A different language is a different vision of life."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Greek it is Sayapo, in Lakota it is Techihhila, in Lithuanian it is Tave myliu, in Albanian it is te dua. What is it in English?","I love you"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 14th Century, Moscow replaced this city as the cultural center of Russia.","Kiev"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A very common greeting in India is namaste or namaskar. What does it mean?","I bow to you."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is telesophobia?","Fear of being last"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ellis Island was the location of the entry facility used by many immigrants to enter the USA. When did the facility operate?","1892-1954"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did the last veteran of the American Civil War die?","1958"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Eddie Slovik was a soldier killed during World War II. How did he die?","He was shot by the US for desertion."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Jerome Napoleon Charles Bonaparte, the last member of the Bonaparte family, die?","He died of injuries sustained when he tripped over his dogs leash."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In how many ways can ough be pronounced in English?","8"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does antepenultimate mean?","second from last"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Find the correct statement.","Irrupt means to break in or rush in."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lawrence Bohune was the first doctor in the British Colony of Virginia. When did he arrive?","1610"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first person to show that blood moved from the heart to the lungs and back?","ibn-al-Nasif"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was the first person nominated for the Oscar for Producer (Best Picture), Director, Actor and Screenwriter for the same movie.","Orson Welles"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first movie for the Olsen twins?","Little Rascals"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did the word golf originate?","Scotland"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Coca Cola was originally green.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the late 1980s which television station did Rosie ODonnell work for?","VH1"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the sitcom Cheers what was the name of the restaurant that sat above the bar?","Melvilles"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following was invented by a woman?","all of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what 1997 movie does the following exchange take place?","As Good as It Gets"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following planets is not named after a Roman god?","Uranus"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Rolling Stones member made a cameo appearance in the 2007 movie Pirates of the Caribbean: At Worlds End?","Keith Richards"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous American authors is not a Pulitzer Prize winner?","Mark Twain"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This landlocked Alpine country, whose official Latin name is Confoederatio Helvetica, is a federation of relatively autonomous cantons.","Switzerland"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Crimean war, which lasted from 28 March 1854 until 1856, an alliance of the United Kingdom, France, the Ottoman Empire and Piedmont-Sardinia fought against which country?","Russia"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement about Gee Jon, who died on February 8, 1924, at the age of 29, is true?","He was the first person in the USA executed by lethal gas"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["German chemist Martin Klaproth discovered uranium in what year?","1789"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Voltaic pile, known as the first modern electric battery, was invented by Alessandro Volta in what year?","1800"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This leader, who ruled the Holy Roman Empire from 1792 until 1806, is known as the last Holy Roman Emperor.","Francis II"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On December 3rd 1967, South African surgeon Christiaan Barnard succeeded in performing what?","The first human heart transplant"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The famous Leporello Catalogue Aria is from which Mozart opera?","Don Giovanni"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Greek word hamartia, used in Aristotles Poetics, means what?","A fatal flaw"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who directed the 1931 musical comedy Le Million, in which the storyline centers on a lottery ticket?","Rene Clair"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what city was the first , free, public high school opened?","Boston"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What company sold the first quartz wristwatch?","Seiko"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A clay tablet, which dates from around 2300 bce is on display at the museum in Konya, Turkey. What is on the tablet?","The earliest known map"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the first town built by Europeans in the Western Hemisphere?","Isabella"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1948 several cities in the USA had comic books burnt publicly.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 2004 Dennis Quaid / Sela Ward movie The Day After Tomorrow, books are burned in order to avoid freezing. Why were some characters in the movie angry?","They did not burn the furniture."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The exprssion The dog days of summer was first used because of this.","An astronomical idea"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Irish it is Taim ingra leat. In Hebrew it is Ani ohev otah. In Hungarian it is Sz eretiek. In Dutch it is ik houd van jou. What is it in English?","I love you."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Robert Todd Lincoln Beckwith was the last of the Lincoln line. When did he die?","1985"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the last state to put photos on drivers licenses?","New York"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Brian Hayes coined the term umop-episdn. What does it mean?","Topsy-turvy"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Portland Alien Museum is dedicated to studying alien life and life forms.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Petite Danseuse de Quartorze Ans by Edgar Degas is a painting depicting a 14-year-old dancer.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what city was the first permanent drama theater in Europe opened?","Malaga, Spain"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first professional sports organization in the USA was formed in this city.","Baltimore"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does sagination mean?","The act of fattening up"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the first chess tournament in the USA?","Paul Morphy"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is considered the Father of Modern Dentistry?","Pierre Fauchard"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Darlene Iskra famous for?","She was the first woman to command a US Navy ship during a war."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Andreas Gruenintzig was the doctor who first performed this procedure.","Angioplasty"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish the nursery rhyme:","pickled peppers"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does Michael Corleone give the kiss of death in one of the most memorable scenes of the movie Godfather II?","Fredo Corleone"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the New Testament, which of the 12 Apostles gave Jesus a kiss, known as the kiss of betrayal?","Judas"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actress, best known for playing Ilsa Lund in one of the most popular romantic dramas, defined a kiss as a lovely trick designed by nature to stop speech when words become superfluous.","Ingrid Bergman"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie soundtrack features Seals Grammy Award-winning song Kiss from a Rose?","Batman Forever"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Shakespearean comedy inspired Cole Porters musical Kiss Me, Kate?","The Taming of the Shrew"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What fictional character in a romantic drama were the following words addressed to: Open your eyes and look at me. No, I dont think I will kiss you. Although you need kissing badly. Thats whats wrong with you. You should be kissed, and often, and by someone who knows how.?","Scarlett OHara (Gone with the Wind)"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ace Frehley, one of the original members of Kiss, created the bands iconic logo, in which the letters SS look like lightning bolts. In which of these countries have Kiss used a modified version of their logo in order to avoid controversy?","Germany"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A kunik is an intimate way of greeting that involves pressing the nose and upper lip against the skin of the other person. What group of people is this form of greeting typically associated with?","Eskimos"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character in the movie Casablanca was interrupted by Rick while singing, You must remember this / A kiss is still a kiss / A sigh is just a sigh ...?","Sam"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actress and singer, who performed her first adult on-screen kiss in the 1940 movie Little Nelly Kelly, wrote a love poem containing the lines:","Judy Garland"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the first 3-D film?","The Power of Love"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which was the first TV series regularly broadcast in color?","Bonanza"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nuclear fusion is the production of energy from the splitting of certain atoms.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The nickname of this U.S. state is The Equality State. Its motto is Equal Right.","Wyoming"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first message spelled out in a neon sign?","Neon"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This persons goddaughter is Gwyneth Paltrow and he hired her for her first role, Wendy in Hook. Who is he?","Steven Spielberg"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Edward Nigma was the name of which fictional character?","The Riddler"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many miles per gallon did the 1908 Ford Model T get?","25-30"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The members of this band included Sgt. Floyd Pepers, Janice, Zoot, Animal, and Lips.","Dr. Teeth and Electric Mayhem"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what temperature does water begin to boil on top of Mount Everest?","150 degrees Fahrenheit"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the name of the computer program developed by the Hollywood division of the Los Angeles Police Department to create a database of crimes, criminals, and all related information.","HITMAN"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do Lou Gehrig, the four Beatles, Beethoven, Bach and Mr. Spock have in common?","They are asteroids."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do you add to steel to make it stainless?","Chromium"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This word can mean to jump straight up or a foolish and/or weak person.","Pronk"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actor played Murphy Brown’s son in the Murphy Brown sitcom.","Haley Joel Osmont"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Michael Moore finance his movie „Roger and Me?”","He ran bingo games."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["U.S. antitrust lawyers took Microsoft to court claiming that the company tried to use its monopolistic power to destroy this computer language.","JAVA"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which singer led The Nude Tour?","Prince"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was the first NHL player to buy his former team.","Mario Lemieux"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which super computer lost a match to Garry Kasparov?","Deep Blue"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Arabic term, Maghrib represent?","Sunset prayers"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Widely known as Crazy Bet, she was a famous Union spy in the American Civil War.","Elizabeth Van Lew"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pendleton Civil Service Reform Act, which established the United States Civil Service Commission, was drafted during the office of which President?","Chester A. Arthur"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The melody of which 1951 pop song was written by a politician who was awarded the Nobel Peace Prize?","All in the Game"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The famous Japanese cherry trees were planted in Washington, D.C., around the Tidal Basin at the request of which US First Lady?","Helen Taft"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Latin proverb, Dum spiro, spero, mean in English?","While I breath, I hope"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You are given a bag with 10 marbles, four red marbles and six blue marbles. You select one at random. What is the probability that the marble you select is either blue or green?","6 out of ten"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This French mathematician, physicist, and religious philosopher, author of the Lettres provinciales, stated the following: There are truths on this side of the Pyranees, which are falsehoods on the other.","Blaise Pascal"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Irish playwright, novelist and poet wrote the following line in his famous play Waiting for Godot: We are all born mad. Some remain so.","Samuel Beckett"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The standing long jump and the standing high jump were once Olympic sports.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This soul singer and songwriter, often called Silky Smooth because of his rich baritone, is famous for his hits Rainy Night in Georgia, Fools Rush In, This Time of the Year.","Brook Benton"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This city, known also as Anvil City, is situated in Northwest Alaska.","Nome"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Easter Island, an island in the south Pacific Ocean, is a territory of which country?","Chile"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Walden Pond, made famous by writer, naturalist, and philosopher Henry David Thoreau, is located in which US state?","Massachusetts"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The dialectic of this philosopher is most often characterized as a three-step process of thesis, antithesis, synthesis. According to his concept, a thesis would cause the creation of its antithesis and this would eventually result in a synthesis.","Hegel"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Freuds psychoanalytic theory, the defense mechanism in which anxiety-producing or unacceptable emotions are replaced by their direct opposites is defined by which term?","Reaction formation"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bloomsday is a secular holiday, which commemorates the life of Irish writer James Joyce and the fictitious events in his novel Ulysses. Bloomsday is celebrated annually, on what date?","June 16"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Latin phrase ceteris paribus mean?","All other things being equal"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This medical term refers to a disease-causing protein agent that contains no genetic material.","Prion"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Russian city, founded by Grand Duke George II of Russia in 1221, was called Gorky from 1932 to 1990.","Nizhny Novgorod"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which animal is the record holder for the largest male genital organ-to-body length ratio in nature?","Slug"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The purpose of the striped fur of most tigers species is camouflage.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The California state flag originally featured a wolf.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A day on Venus is equal to how many Earth days?","243"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A fly flies slower when the sun is behind the clouds.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that starfish can see with the help of the two eyes at the end of each leg?","No"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which great composer wrote Wellingtons Victory , which included cannons, drums, and a lot of brass?","Beethoven"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which was the first sub-Saharan African nation to gain its freedom?","Ghana"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which US state is the Bicycle Museum of America located?","Ohio"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement is untrue about Luxembourg?","Its capital, Esch-sur-Alzette, is not its largest city."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous Russian politicians was also famed as a literary critic?","Trotsky"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Queen Elizabeth II was coronated Queen in 1953. Whom did she directly succeed?","George VI"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is considered the first American to be killed in the Cold War?","John Birch"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1078, a battle between two rulers was averted because of a chess game.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elmer Valo, a Major League Baseball player and coach, is one of the few American major leaguers born in this country.","The Czech Republic"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following political figures was the first to fight a war as President of the United States?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which was the first racehorse to run the Kentucky Derby in less than 2 minutes?","Secretariat"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which English king had wives called Catherine, Anne, Jane, Anne, Catherine and Catherine, in that order?","Henry the Eighth"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the robot in the 1986 comedy sci-fi film Short Circuit and its 1988 sequel Short Circuit 2?","Johnny 5"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This novella by H.P. Lovecraft was published in 1936 and is about a hybrid race of human/ fish/ frog people who inhabit a small town in Massachusetts.","The Shadow Over Innsmouth"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is no cure for this disease that is characterized by the death of muscle cells and tissue. Diagnosis is often based on the results of a muscle biopsy.","Muscular dystrophy"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Twilight Zone is a term used by the United States Air Force to describe the border between day and night on a planetary body.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This song about a paralyzed war veteran whose wife cheats on him was written by Mel Tillis and performed by Kenny Rogers and the First Edition in 1969. It has also been recorded by CAKE, The Killers, Waylon Jennings, Roger Miller and Wolfsheim.","Ruby, Dont Take Your Love to Town"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many colonies formed United States of America in 1776?","13"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the correct formal name of the country known as the UK?","United Kingdom of Great Britain and Northern Ireland"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This English city is home to a top European soccer team, which contains the word United in its name and is nicknamed The Red Devils.","Manchester"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the full name of the Benetton fashion brand?","United Colors of Benetton"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city is the capital of the European Union?","The EU has no official capital."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city is the capital of the United Arab Emirates?","Abu Dhabi"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What airport is the largest hub of United Airlines?","OHare in Chicago"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of soviet, as in Soviet Union?","Council"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the full name of UTC, the company that manufactures Sikorsky helicopters?","United Technologies Corporation"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first person to be crowned Czar of Russia?","Ivan the Terrible"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first play Shakespeare wrote?","Henry VI, Part One"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do Oscar Robertson (ex-NBA All-Star) and Roy Orbison (the great singer/songwriter) have in common?","The same nickname"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which country was Carlos Mencia born?","Honduras"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is a bibliopole?","Someone who sells books"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the Papstiche Schweizergarde?","A 500 year-old organization of Swiss guards"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The square root of a number is always smaller than that number.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why are Cipriano dela Valera and Casiodoro de Reina famous in the Spanish-speaking world?","They are responsible for the most popular Spanish version of the Bible."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the dancer described in the following lyrics?","Mr. Bojangles"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What musician is often referred to as The Man in Black?","Johnny Cash"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of object does the term black hole refer to in physics?","A collapsed star"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is black color, or kuro, associated with in Japanese tradition?","All of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What day is commonly called Black Friday in the United States?","The Friday after Thanksgiving"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the black color associated with in Native American tradition?","Soil"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the expression the new black in the fashion world?","Something considered very trendy and a fashion basic"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The members of what subculture have adopted a preference for the black color?","Goth"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What female musician won five Grammy Awards for her album and song Back to Black?","Amy Winehouse"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The outbreak of what deadly disease is often referred to as Black Death?","Plague"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name used for black tea in Chinese, Korean and Japanese languages?","Crimson tea"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mixing what colors will result in a brown color?","All of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What planet has brown clouds floating over its surface?","Jupiter"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is James Browns honorific nickname?","Godfather of Soul"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the term browning refer to in cooking?","All of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song by Irish band U2 contains the line, Blue-eyed boy meets a brown-eyed girl?","The Sweetest Thing"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the brownish pigment that gives coloration to the human skin, iris and hair?","Melanin"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the brown aura associated with in parapsychology?","Greed"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the most important ingredient for preparing brownies, a type of American dessert?","Chocolate"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal meaning of the Japanese word Chairo which denotes a brown color?","Tea color"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the popular song written by American composer Joseph Winner in 1869?","Little Brown Jug"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete the title of this 1983 song by Prince:","Corvette"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state is nicknamed The Golden State?","California"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Academy Award-winning actress starred in the 1981 movie On Golden Pond?","Katharine Hepburn"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor portrayed agent James Bond in the 1964 movie Goldfinger?","Sean Connery"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which wedding anniversary is known as the Golden Wedding Anniversary, or Golden Wedding Day?","50th anniversary"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of what animal is the legendary Golden Fleece from Greek mythology?","Ram"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what field is the Golden Duck Award given annually?","Childrens science fiction"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be from Asia?","610"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be from the African continent?","149"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be from the North American continent?","79"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would speak Mandarin as their first language?","132"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would speak English as their first language?","59"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would speak Hindi as their first language?","101"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be non-religious (that is: Atheist, Agnostic, Secular Humanist, No preference)?","171"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be in the workforce?","484"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["if the world were a village of 1000 people, how many would be age 65 or older?","74"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be doctors?","1"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would be teachers?","7"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many would own an automobile?","70"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, what would the life expectancy of the villagers be?","66"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, how many acres of land would be in the village?","6000"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the world were a village of 1000 people, what would the per capita income (in USD, Atlas method) of the villagers be?","$7000"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these terms means fear of pins and needles?","Belonephobia"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bathophobia means fear of taking a bath.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bibliophobia means fear of reading the bible.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which term means fear of gravity?","Barophobia"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What word means fear of prostitutes or venereal disease?","Cypridophobia"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Catoptrophobia is defined as fear of mirrors.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cancerophobia is a condition characterized by fear of malignant growth.","True"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What word means fear of newness or novelty?","Cainophobia"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Chiraptophobia means fear of snow.","False"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What should be done according to a Russian superstition when someone has left the house and gone on a long journey?","Their room and their possessions should not be cleaned up until they have arrived."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is a Russian tradition of spitting three times to chase away bad luck, similar to knocking on wood. Where should one spit?","Over their left shoulder"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What should one do on examination day in order not to chase away good luck according to Russian superstition?","All of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of presents are considered to be taboo according to Russian superstition?","Sharp objects"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where shouldnt unmarried people sit if they dont want to stay single for a long time according to Russian superstition?","At the corner of the table"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What should a stranger say when seeing a baby less that an year old according to Russian tradition?","Oh, what an ugly child!"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How is a latecomer punished in Russian traditions?","They are forced to drink a full glass of alcohol."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What will happen very soon if the cat is washing its face according to Russian beliefs?","Guests will come."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does sneezing while talking mean according to Russian superstition?","The person is telling the truth."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What will happen if a fork or a spoon falls on the ground according to Russian superstition?","A female guest will come."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following movies does not star Will Ferrell?","Mrs. Doubtfire"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the first routine that Chazz Michael Michaels and Jimmy MacElroy do together in the movie Blades of Glory?","Fire and Ice"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How was the FIFA World Cup Won in 2006?","penalty kick shootout"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If there is a one way street and there are two cars going the opposite direction, is either of the drivers breaking the law?","No"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why did King Oedipus marry his mother according to the Greek legend?","He didnt known she was his mother."],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the actor who starred in the 2007 drama movie There Will Be Blood.","Daniel Day-Lewis"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What blood song did Michael Jackson release in 1997?","Blood on the Dance Floor"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor starred as mercenary Danny Archer in the 2006 movie Blood Diamond?","Leonardo DiCaprio"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of a 1971 Academy Award-nominated movie directed by John Schlesinger?","Sunday Bloody Sunday"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What female musician released the single Red Blooded Woman in 2004?","Kylie Minogue"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What action star played the lead role in the 1988 movie Bloodsport?","Jean-Claude Van Damme"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The term cheiromancy, also known as palm reading, is derived from Greek. What does it literally mean?","Hand divination"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is the art of palm reading believed to have originated?","India"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What characteristics of the palm are explored by palm readers to predict the future or estimate the personality of its owner?","All of these"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to a theory, palm readers should explore only the left hand of people which of the following people?","Women"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What classification of the hands do modern palmists most often use to define the personality of the owner?","By elements"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not within the lines of the palm explored by palm readers?","Past line"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the Sun line of the human palm associated with in palmistry?","Fame"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cheirognomy is part of chiromancy, or palm reading. What is the object of its study?","The mounts of the palm"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How are the people having rectangular palms, flushed skin and short fingers classified according to palmistry?","Fire"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which line of the palm is traditionally examined first by palm readers?","Heart line"],"tags_json":"[\"trivia\",\"general\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
