{"kind":"deck","format":"deez.nut","version":2,"name":"Brain Teasers v1"}
{"kind":"note","note_type":"basic","fields":["Which of these is true about the sleep of zebras?","They sleep standing up."],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A farmer had 12 sheep and 3 cows. All of the animals except 9 sheep died. How many animals did he have left in his farm?","9 sheep"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I dont speak, I cannot hear, but I always tell the truth.","The Mirror"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Can a Roman Catholic man from California marry his widows sister who is from Texas?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does this proverb continue: The squeaking wheel gets ...","The grease"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["An old man was looking at a photograph of a young man. Somebody asked him who it was. The mans answer was the following: Brothers and sisters, I have none. But that mans father is my fathers son. Who was in the photograph?","His son"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A shepherd from a village tended the sheep of those of his fellow villagers who did not tend their own. However, he did not tend the sheep of those villagers who tended their own sheep. In that village, there was only one shepherd and he also had several sheep. Can all this be true?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A famous story begins like that, It was a clear summer day and my family was preparing dinner for the New Years Eve. Can this story be true?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a basket there are five apples. We give the five apples to five kids so that each kid receives an apple. However, in the basket there is still one apple. Is this possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two days ago my son was three years old and next year he will be 6. This could be a correct statement.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The single difference between the two cities A and B was that the citizens of A always said the truth, while the citizens of B never did. Once, a man who had never been to either city arrived at one of them. Which question should the man have asked in order to identify the city he was in? Have in mind, that people from A often visited their friends in B and vice versa.","Are you a citizen of this city?"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You have two right triangles. The sides of the first one are 3 m, 4 m and 5 m. The sides of the second are 3 m, 4 m and 7 m. The area of the second triangle is bigger.","False"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What number comes next in the row - 31, 28, 31, 30, ?","31"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If you were running a race and passed the person in second place, what place would you be in?","2nd"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What number comes next: 1, 11, 21, 1211, 111221, 312211, 13112221?","1113213211"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest number you can write out with numbers 1, 2, and 3?","10,460,353,203"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["John went to a party one night. The next day he was asked if he met a lot people at the gathering. Figure it out for yourself, John said. Of the girls I spoke to, all but two were blondes, all but two were brunettes, and all but two were redheads. How many girls did he talk to?","3"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A kid found two old coins. The first coin said it was minted in 43 BC, while the other said it was minted during the reign of Emperor Nicholas I. Which of the coins was fake?","Both"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A contestant on a TV show had to answer 26 questions. For each correct answer he received 8 points, while a wrong answer penalized him 5 points. How many answers did the man answer correctly, bearing in mind that he eventually had 0 points?","10"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lets suppose that I offer you a bet under the following conditions: I bet $1 and claim that if you give me $5 I will give you $99 in return. Will you gain something from this bet?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You can put something between the digits 2 and 3 so that the resultant number is bigger than 2 and smaller than 3.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A row consists of 10 letters. The first six are - Z, O, T, T, F, F. Which is the tenth letter?","N"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You have a square and a circle and the perimeter of the square is equal to the circumference of the circle. Which of the two figures covers a bigger area?","The circle"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sometimes we see 10 but say 22, see 4 but say 16.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Can you build a house so that all its walls face north?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the beginning of the day, I was behind a car at a stoplight, whose vanity plate read: 4SBWIU. What is the driver of this car most likely a fan of?","Movies"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["My first stop was the supermarket. When I had completed my shopping and was in the parking lot, I spied this snazzy auto with the following vanity plate: 10S42. What sport is the driver of this vehicle most likely a fan of?","Tennis"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["My next errand took me all the way across town. I decided to take a shortcut which put me on a boulevard of small, eclectic businesses. One of these businesses I passed on my way was a fortune tellers shop. A Cadillac was parked out front, which, I assume, belonged to the owner of the shop. What would be the most appropriate vanity plate for this automobile?","N2IT"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the on-ramp to the freeway, I was behind an auto with the following plate: 4IS. What is the likely profession of the driver of this car?","Optometrist"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Well, I got caught in noon rush hour. As luck would have it, I saw yet another vanity plate. This one told me that the driver at least checks in his / her rear view mirror. What plate did I see?","OICU2"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I went to my favorite restaurant to pick up some carry out for an early dinner. I saw the owners car parked out front. The vanity plate asked a question. What do you suppose the plate read?","E10YET"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I always go up and down the stairs without moving.","A rug"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If the mother of a boy spanks him and then his father comes and does the same, who hurts the most?","The boy"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which letter behaves as a selfish friend?","P"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You always wear these flowers.","Tulips"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["12 candles were alight. The wind blew out 5 of them. How many candles were left?","12"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A team of two horses ran for 3 miles. How many miles did each of the horses run?","3"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nine passengers carried with them enough food for five days. Several other passengers joined the first group and they all shared the same food, which was now enough for three days. How many passengers joined the first group?","6"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many times does the digit 3 occur in the numbers from 1 to 50?","15"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A pole is 20 m high. An ant is climbing it as follows - every day she ascends 5 m and every night she descends 4 m. In how many days will the ant be on the top of the post?","16"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A butcher had to stick a total number of 50 sheep in a week. Every day he sticked an equal number of sheep and managed to fulfill the task. How many sheep did he kill per day?","10"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a basket there are three sorts of apples. How many apples do you have to take from the basket to make sure you have at least 2 apples of the same sort?","4"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["An old potter was selling pots. Once, a woman came and bought a pot for its sticker price. She had to pay $1 plus half its price. What was the price?","2"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Four glasses and a jug weigh as mush as 17 iron balls do. The jug weighs as much as a glass and 7 balls. How many balls does the jug weigh?","9"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Three cats can eat 3 mice in 1.5 hours. How long will it take 10 cats to eat 20 mice?","3 hours"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is there a way you can divide 7 identical pieces of bread equally among 12 people?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A lion can eat a sheep in 2 hours, a wolf - in 3 hours, and a dog - in 6 hours. How long will it take the three animals to eat a sheep if they eat together?","1 hour"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two men were walking towards a river. There was a boat on one of the riverbanks. However, this boat could carry only one man at a time. Nevertheless, both men managed to cross the river with the boat. This is possible.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Some of my relatives are 600 times younger than me. Can this be true?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A man is carrying three croquet balls across a bridge. The bridge has a sign that says bridge can only hold 200 pounds. The man weighs 195 pounds and the croquet balls weigh 2 pounds each. The man ends up crossing the bridge in one trip and no one else helps him. This is possible.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which letter comes next in this series:","S"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A squirrel finds a hollow log with 9 ears of corn in it. If he can carry out 3 ears every day, how many days will it take him to empty the log?","9"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Suppose youre taking a multiple-choice quiz. One question has three choices - A, B, C. You do not know the answer and guess A. The instructor then announces that C is incorrect. Should you switch to B before turning in your paper?","Yes, this should help"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A worm can gnaw through 1 mm of paper for a single day. On a bookshelf there are two volumes, each 4 cm thick. Each of the covers is 2 mm thick. How long will it take the warm to gnaw from the first page of the first volume to the last page of the second volume?","4 days"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The train leaves in 2 minutes and the distance to the train station is 2 miles. If you drive the first mile at 30 miles/h, at what speed should you drive the second mile?","It does not matter."],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A driver noticed that the dashboard showed he had driven a total number of 15951 miles. He thought that this was a strange number because no matter in what direction it was read (from left to right or from right to left) it was the same. However, in two hours, the dashboard showed a number that had that same characteristic. What was the speed of the car?","55"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Three hunters, different in height, got stuck in a pit. They tried to get out of it and stepped one onto the other. However, the shortest, who was on top, could not reach the edge for just 5 cm. Can these three hunters ever get out of the pit without the help of anyone else or of any additional object?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Middle Ages a thief went into a church and fell asleep on a pew. He dreamed about stealing the cross of the minister and being sentenced to execution for that. However, just as he was about to be executed, he was woken by a local lady. Immediately after that the thief died. Modern scientists say it was due to a heart attack. Is everything okay with the story?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of these pairs of numbers has this strange characteristic - when you subtract one of them from the other you get a number equal to what you will get if you divide one by the other. Can you spot it?","25/4 and 5/4"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The local limo company have recently expanded their inventory and no longer have enough room for all of their limos. Fifteen of the limos have to be stored outside. If they decide to increase their garage space by 50%, this will give them enough room for all of their current limos, plus enough room to store another fifteen in the future. How many limos does the company currently own?","75"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A horse is tied to a five meter rope in front of an old saloon. Six meters directly behind the horse is a bale of hay. Without breaking his rope, the horse is able to eat the hay whenever he chooses. Assuming the horse is perfectly normal, is this possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A famous playboy explained to a beautiful woman his system for playing roulette: In each round, I always bet half of the money I have at the time on red. Yesterday, I counted and I had won as many rounds as I had lost. Over the course of the night, did the gambler win, lose or break even?","lose"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A horse travels a certain distance each day. Strangely enough, two of its legs travel 30 miles each day and the other two legs travel nearly 31 miles. Can this be true?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A total of 15 delegates from Africa, Asia, America, and Europe meet at an international conference.","Asia"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One kid has a toy car with a strange remote control- it has only one button on it. When the car is switched on, it starts moving forward and doesnt stop until its switched off. When the boy presses the button, the car makes a 60 degree turn clockwise. Considering that this is a very lazy boy, try calculating the smallest number of times he has to press the button so that the car travels back to him.","5"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Here is something like a warm-up before you get to the next one. Three friends, Peter, Nick and Tom were competing in a race. After they finished, a person ,who was late for the race, asked them who was the winner. Tom said I didnt finish first and Peter didnt finish second. Then Nick said Tom didnt finish second either. Who was the winner?","Peter"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One watermelon weighs 10kg (22 lbs) plus the half of its own weight. How much does it weigh?","20kg (44 lbs)"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Try thinking out a random 3-digit number and writing it twice on a piece of paper, forming a 6-digit number (for example the number is 123, than you will have to put down 123123 on the paper). Now divide this 6-digit number by 7. There will be no remainder, I guarantee. Now divide the result by 11. No remainder again, I guarantee. Now divide the new result by 13. What happened?","The result is your original number"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two dice are randomly thrown. What is the possibility that the number, formed by the two digits that come form the dice, is a prime?","5:12"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Yesterday I heard an interesting conversation in a shop:","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["4, 7, 12, 19, 28, 39, ??","52"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A man buys a horse for $60. After a while he sells it for 70$. Some time passes and the man regrets his decision and goes to buy the horse again. But now he has to pay $80 for it and he does. After a while he regrets to have bought the horse back and sells it for $90. Now in total, how much loss/profit did the man make from the three transactions?","$10"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Somewhere, there is a very interesting village. And whats so interesting about it? Well, in this village there is a barber, a very special barber. He cuts the hair of everybody in the village that doesnt cut his own hair. Who then cuts the barbers hair?","Such village cannot exist, it is a paradox"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two men were playing for title of championship of the world for the checkers tournament. They each played five games and they each won three. There were no ties, is this possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Take two apples from three apples and what do you have?","two apples"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A famous, well respected archaeologist went on a dig in Jerusalem. He found a coin dated 56 B.C. He was so excited, he rushed to the museum so it could be put on display. But the museum wouldnt accept the coin because they said it could not possibly be authentic. They said that the coin had to be a fake.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country can your spouse be jailed along with you if you are caught drinking and driving?","Malaysia"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Approximately how much money does the taxpayer spend on a prisoner serving a life sentence in California?","1,550,000"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What creature is responsible for the most human deaths?","The mosquito"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest county in the US?","San Bernadino, CA"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it possible to test positive on a breathalyzer after drinking only a glass of milk?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I have four legs in the morning, two legs in the afternoon and three legs in the evening. What am I?","A human"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why do Chinese people eat more rice than Japanese people?","Because Chinese people are more than Japanese people"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the smartest letter.","Y"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which is the month that allows women to talk the least?","February"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the number of men born last year in USA?","None"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is what you can see once in a minute, twice in a moment, but never in a thousand years.","The letter M"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["With a red beard, gray mustache and black sideburns, the man had a distinct HIRSUTE quality. What does hirsute mean?","hairy, shaggy, covered in hair"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Stacy was extremely annoyed by Jills PECCADILLO. Jill constantly ate food with her mouth open. What does the word peccadillo mean?","a petty fault"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["DERIDE means to laugh at someone with contempt.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jerry was worried he would mumble and slur his words, so he had to go slowly and try to ENUNCIATE each word. Words might get lost if you dont enunciate. What does enunciate mean?","pronounce articulately"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Annas brother took his AVUNCULAR duties very seriously. He taught her children how to read, write and speak German. What does avuncular mean?","Adjective of an uncle"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Jack and Jill went to see The Notebook, Jill was surprised at Jacks obvious display of his LACHRYMOSITY. What was Jack doing?","crying"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A CHORTLE is an tool used to cut pastry dough.","False"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The rancid meat attracted flies and maggots and wafting from it was a FETID odor. What is the meaning of fetid?","stinking"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The king required FEALTY from all his vassals. What does the word fealty mean?","allegiance"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The siblings were complete opposites. Tom was pedantic and read all the time and Lucy was LUDIC. She was always getting mud on her clothes. What is the meaning of ludic?","playful"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The vegetable rhubarb is delicious but its leaves are poisonous. What did rhubarb originally mean?","root of the barbarian"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What modern slang term once meant a carnival worker who performed disgusting tasks such as biting off the heads of live chickens?","Geek"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is heavier a pound of bricks or a pound of feathers?","Their weight is equal"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A farmer had 20 sheep. All but 8 died. How many are still alive?","8"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a house with a maid, a mail receiver, and a chef, the owner was murdered on a Sunday morning. The police questioned all the 3 people (the chef, the mail receiver, and the maid). The chef said; I was making her breakfast. The mail receiver said; I was getting the mail., and finally the maid said; I was cleaning her living room. The police arrested one of them right after the interview. Who got arrested?","The mail receiver"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is a branch with 10 birds on it. I shot 2 of them and then 1 more. How many birds are left on the branch?","0"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If you have in your suitcase 6 white socks, 4 red socks, 8 green socks, and 2 brown socks, how many socks would you have to pull out (without looking at them) to be sure you have a matching pair?","5"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Joe had 29 pairs of socks. How many socks did he have?","58"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One camera could take 350 pictures and Bob bought 3 cameras of the same type. How many pictures could he take?","1050"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One iPod can hold 950 songs and 3 movies. How many iPods of this model would one person have to buy to have 27 movies and 8550 songs?","9"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In an office building, there are 350 windows and half as many doors. How many doors are there in 3 office buildings?","525"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A monster had double the amount of eyes he had ears, triple the amount of ears he had legs, and had six legs. How many eyes did he have?","36"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If I had $654,987, how much change is that?","65,498,700 cents"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a rectangular room there are 10 chairs. It is possible to arrange the chairs in such a way so that an equal number of chairs is set against each wall of the room.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Five years ago the sum of the age of a sister and a brother was 8. What will be the same sum in 5 years?","28"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a room, there can be two mothers and two daughters, three women in total.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A woman once said about a man, I am not his wife but this mans mother is the mother-in-law of my mother. What were the man and the woman?","A daughter and a father"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A cowboy was looking after 100 animals (oxen, cows and calves). For his job he was paid $100 (for every ox he received $10, for every cow $5 and for every calf $0.5). How many were the oxen, the cows and the calves?","1 ox, 9 cows, 90 calves"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A farmer had 9 cows. The first one produced 1 gallon of milk, the second one 2 gallons and so on. The ninth cow produced 9 gallons of milk. The farmer had three sons and he wanted to divide the cows in such a way that each of his sons received an equal number of cows and the cows of each produced an equal amount of milk. Is that possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In a lake there were lilies. The strange thing about them was that they doubled their number once per day. If on the 15th day half of the lake was covered with lilies, on which day will the whole lake be covered with them?","16"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A peasant buys a pregnant sheep, which gave birth to a lamb. At the age of 3, the lamb gives birth to another lamb. After that it starts bearing a lamb per year. How many sheep will the peasant have 9 years after the birth of the first lamb if all the lambs are female and none of them ever dies?","60"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A farmer had a yard, whose shape was a square, and in the four corners of this square there were apple trees. Some years later the farmer decided to make his yard twice as big and preserve the square shape. However, after the enlargement the four apple trees were still by the fence.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Marsha dug her FUNEREAL attire out of the closet. It consisted of a black dress and a black overcoat. What does funereal mean?","having to do with a funeral"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The newly blooming lavender was a HARBINGER of spring. It was beautiful and fragrant. What does harbinger mean?","a sign of things to come"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Her passion for art bordered on pathological MONOMANIA. Shes a sculptor, studies medieval art in night classes, frequents galleries and is often caught doodling in a notebook. What does monomania mean?","excessive concentration one one subject"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It wasnt accidental it was pure KISMET that Joey fell in love with Laura. What does kismet mean?","fate, destiny"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Because Ben travels to many countries for business, he has written a POLYGLOT lexicon for himself. It contains quick references on phrases he might need in any given situation. What does polyglot mean?","containing many languages"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A QUAGMIRE is a difficult or precarious situation.","True"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The fortune teller persuaded Anna that she needed a PHILTER to gain the attention of her beau. She only needed to apply the elixir and think of him. What does PHILTER mean?","love potion"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Matt and Julie asked their son How was your day at school? and they always received the same BRUSQUE answer-fine. Brusque means habitual, constant, the same.","False"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jack grabbed Janets hand and they began to GAMBOL in the sunshine. They felt like children, not a care in the world. What does gambol mean?","to frolic and leap playfully"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To ESCHEW something means to be attracted to it.","False"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After a long walk, two sons and two fathers find three apples. Each of them has an apple and they all go their way. How is that possible?","they were a boy, his father and his grandfather"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The name of what is coded in the following: 86,smopuim?","the name of a software product"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Five girls are sitting next to each other on a train. Ann and Betty are as close to each other as Ann and Kate are. Dana and Ann are sitting as close to each other as Dana and Kate are. Between which two of her friends is the fifth girl, Jane, sitting?","between Ann and Betty"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What number multiplied by 10 equals the square of the same number, times 5?","2"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bob has a book of 100 pages and in 10 seconds he can count out 10 pages. What is the shortest time in which Bob can define where the 60th page is?","40 seconds"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two people get to a river and find a boat capable of accommodating only one person. Using this boat, both of them manage to cross the river. If they crossed without any of the them swiming the river which of the following is true?","They were on different banks of the river."],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which term refers to a king or prince in India?","raja"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete the Latin term for an unacceptable person: persona non _____.","grata"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are 15 birds sitting on the branches of a tree. A hunter goes by and shoots 3 of them. How many birds are left on the tree?","0"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A man walked by an old fisherman and asked him how many fish he had caught. The fisherman replied: The half of the eight, the nine without its tail, and the six without its head. How many fish did the fisherman caught?","0"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A tree is 20 meters tall. An ant is climbing it. Every day the ant climbs 5 meters, and each night it descends 4 meters. In how many days will the ant reach the top of the tree?","16"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A bar of soap is placed on one of the sides of a pair of scales. On the other side there is 3/4 of a bar of the same soap and а 3/4 kg metal weight. The scales are in balance. How much does a bar of soap weigh?","3 kg"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are three sorts of apples in a basket. How many apples have to be taken from the basket, without looking, to be sure that there are at least 2 apples of the same sort?","4"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A boy and a pig weigh as much as 5 crates. The pig weighs as much as 4 cats. 2 cats and the pig weigh as much as 3 crates. How many cats weigh as much as the boy?","6 cats"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A fish costs a dollar and half a fish. How much do 5 fish cost?","$10"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are three lemons. One of them is lighter than the other two, which have the same weight. Can we tell which of the lemons is the lighter one with just one measurement on the scales?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A father has seven sons, and each son has one sister. How many children does the father have?","8"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Several rabbits and hens are placed together in a cage. How many rabbits and hens are there, if the total number of their heads is 35, and the combined number of their legs is 94?","12 rabbits and 23 hens"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is there a kind of coat that can only be put on wet?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["10% of all the people living in a certain town in Georgia have unlisted phone numbers. If you selected 100 names at random from the towns phone book, on average, how many of these people would have unlisted phone numbers?","0%"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A magician had a water glass filled to the top. Holding the glass above his head he let it drop to the floor without spilling a single drop of water. Is this possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Can you take a picture of a person with a wooden leg?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it possible to name three consecutive days without using the words Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, or Sunday?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You are on a ship and over the side hangs a rope ladder with one foot rungs. The tide rises a one foot per hour. At the end of five hours, how much of the ladder will remain above the water assuming that 12 rungs were above the water when the tide began to rise?","12 rungs"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is a gun dog breed which is subdivided into Springer, Cocker, Cavalier King Charles, etc.","Spaniel"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What family of animals has species called Oryx, Duiker, Dik-dik and Impala?","Antelope"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the only venomous snake native to the British Isles?","Adder"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This animal, also known as Suricate, is a member of the mongoose family. It has a long, thin tail which is used for balance when standing on hind legs. It lives underground in colonies of up to 30 individuals that operate an early warning system where sentries stand guard beside the burrow entrances and warn of approaching danger from predators.","Meerkat"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This majestic bird can be golden, bald and tawny. One of the species is a symbol of the United States of America.","Eagle"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the white crystalline sugar found in wood and straw?","Xylose"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the characters that have appeared in Brian Herberts Legends of Dune universe, Disneys Aladdin and the video game System Shock 2?","Xerxes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What X-word means a colourless, flammable liquid ingredient used to make synthetic resins, dyes and insecticides?","Xylene"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is xenophobia a fear of artificial lights?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What plant tissue conducts water and mineral salts from its roots to other parts of the plant and also provides mechanical support?","Xylem"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which word refers to a colourless, odourless gaseous element that occurs in trace amounts in air?","Xenon"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Were X-rays at one time proposed to be called Röntgen rays?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When you add 55 and 45 the sum is 100. When you add 65 and 35 the sum is also 100. But which is greater: 55 multiplied by 45 or 65 multiplied by 35?","55 multiplied by 45"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two doctors and two mothers went to an ice cream shop. Each one of them ordered different flavors. The waiter then gave them one chocolate, one vanilla, and one strawberry and everybody on the table had an ice cream. Is this possible?","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two children were on their way to school, when they began to question what day of the week it was. They were so confused in their reckoning that one of them gave the following riddle to help sort the matter out: When the day after tomorrow is yesterday, then today will be as far from Sunday as that day was which was today when the day before yesterday was tomorrow!","Sunday"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["We know very little about the life of the mathematician Diophantus (called the father of algebra) except that he lived around the year 250 B.C. Due to one admirer of his, who described his life by the means of an algebraic riddle, we can at least determine his age at death:","84 years"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Three goddesses were sitting in an old Indian temple. Their names were Truth (who always tells the truth), Lie (who is always lying) and Wisdom (who sometimes lies). In order to figure out which goddess was which you posed the following questions to each:","1. Wisdom 2. Lie 3. Truth"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are two kinds of people who live on a mysterious island. They are the so-called Honestants, who always speak the truth, and the others are the Swindlecants, who always lie.","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You are on your way to visit your Grandma, who lives at the end of the valley. Its her birthday, and you want to give her the cakes youve made.","2"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["My grandson is about as many days as my son is weeks, and my grandson is as many months as I am in years. My grandson, my son and I together are 120 years. Can you tell me my age in years?","72"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was Emilys first day at school. The teacher suggested that it would be a good idea for each child to meet every other child in the class. The teacher said, When you meet, please shake hands and introduce yourself by name. If there were 10 children in the class, how many were the total handshakes?","45"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A woman has 7 children, half of them are boys.","Yes"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Paul designs food displays for the local Supermarket. For one of his displays, he wants to set up soup cans in the form of a square pyramid. Hes decided to use 10 cans for each side of the square base of the pyramid. If each carton holds 25 soup cans, how many cartons will Paul need to open to build the pyramid?","16"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A firefighter stood on the middle rung of a ladder, spraying water on a burning house. He then climbed up 6 rungs before the heat of the flames caused him to come down 10 rungs. After some minutes he was able to climb 18 rungs to the very top of the ladder. How many rungs did the ladder have?","29"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A man burst into a police station soaking wet and started screaming My wife has been murdered, my wife has been murdered! A police officer asked what had happened and the man explained that when they were walking along the cliffs of the shore, he heard a big roll of thunder come out of nowhere. No further thunder washeard after the first one. He turned around startled to see what happened and then a huge bolt of lightning struck and he heard his wife scream. He turned around and saw his wife lying mangled on the sharp rocks at the bottom of the cliff, and he saw a man running away. Can the mans story be true?","No"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The stubs obtained by burning ten candles will yield one extra candle if you melt them all together. If you burned 100 candles, how many extra candles could you make?","11"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How long did the Hundred years war last?","116 years"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cold is faster than hot.","False"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Its quarter past three. Of how many degrees is the angle formed by the hands of the clock at this moment?","7.5"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Charlie asked Margaret how old she was and she answered him: In two years I will be twice as old as I was five years ago. How old is she?","12"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A mother has 6 daughters and each of them has a brother. How many children are there?","7"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the next letter in the sequence O, T, T, F, F, S, S, E, ?","N"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You meet two men who are playing a game. One of them tells only lies on Monday, Tuesday and Wednesday, and during the rest of the week he speaks the truth. The other one lies only on Thursday Friday and Saturday and says the truth the rest of the time. Today they both say they were lying yesterday. Which day of the week is it?","Thursday"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dessert was created for and named after a famous ballet dancer in 1926.","Pavlova"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What food can be Chinese, Jerusalem and Globe?","Artichoke"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This food is one of the most versatile and convenient. You can boil it, fry it, poach it, scramble it, use it in baking. What is it?","Egg"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If there are three pineapples and you take two, how many will you have?","2"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Imagine you were running a race and you passed the person in 2nd place. What place would you be in?","2nd"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What letter should be added the group of letters P, N, N, E, S, O, R, H, E, T, and I to form a twelve-letter word that is related to blood?","Y"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What on earth could dance, and live and die?","Fire"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Each morning I appear","Your shadow"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Im one of five, and Im not alive.","A stone"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I am related to the water but I am not wet.","a mirror"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I have eight to spare, in case I lose my one.","a cat"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are these two country farmers milking their cows. While the one farmer is milking, a fly zooms into the cows ear. The cow starts jumping around, shaking its head and mooing. He tries to steady the cow and suddenly it settles down. He looks down and sees the","in one ear and out the udder"],"tags_json":"[\"trivia\",\"brain-teasers\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
