{"kind":"deck","format":"deez.nut","version":2,"name":"Video Games v2"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not a place in RuneScape?","Duel Wars"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the female character and one of the four survivors in LFD1.","Zoey"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the main difference between LFD1 and LFD2 in regard to use of weapons?","In LFD1 there are no melee weapons like the ax or the machete."],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Setting off a car alarm scares off the zombies in LFD.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A pipe bomb is an ideal weapon to destroy LFD zombies because it is a silent weapon and they wont hear it when you throw it among a group of them.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Unlike in other video or PC games you cannot save a game in LFD and then come back later to play it from where you left off.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the fictional government agency or organization that was supposed to fight the infection and evacuate people from infected areas in LFD.","CEDA"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In LFD2 the Parish campaign takes place in this city.","New Orleans"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of fictional band featured in LFD2?","The Midnight Riders"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What pestilence or disease caused people to turn into zombies and deformed some of them into super mutants in LFD?","The green flu"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the race car driver encountered in the Dead Center campaign of LFD2?","Jimmy Gibbs Jr."],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In LFD1 the achievement known as Do Not Disturb is awarded for which of the following?","Sneaking past all Witches in a campaign without disturbing one"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In LFD2 the achievement known as the CHAIN OF COMMAND is awarded for which of the following?","Killing 100 Common Infected with the chainsaw"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You can add more maps and campaigns in LFD1 and LFD2.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In both LFD1 and LFD2, accumulating more cash than the other survivors will give you an advantage.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unique Zord do the Time Force Rangers have?","Time Shadow"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Zelda, featured in The Legend of Zelda series of video games, is what kind of character?","The princess"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the currency used in the Legend of Zelda video game series?","Rupees"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not a race featured in the Legend of Zelda video games?","Hobbit"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these items is always in Links arsenal in the Legend of Zelda games?","Boomerang"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The Legend of Zelda series of video games Zelda possesses which piece of the Triforce?","Wisdom"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is there a game called Super Mario Tennis?","No"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are Mario games featuring racing, baseball, soccer, tennis, and golf.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following characters is NOT a sidekick in Super Mario Strikers?","Paratroopa"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Mario Superstar Baseball what do you have to you use to unleash your characters super pitch?","A star"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Mario Kart, characters are classified as either heavy or light.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Luigis power shot in Mario Power Tennis?","A hammer"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Mario Power Tennis, Bowsers racket has spikes on it.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the most basic court in Mario Power Tennis?","Peach Dome"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sonic the Hedgehog is the protagonist of a video game, released by Nintendo.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these game systems was released by Nintendo?","snes"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Nintendos mascot Mario wear a red and black hat?","No"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that Kirby, the protagonist of the Kirby game series, is pink?","Yes"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Captain Falcon, from the F-Zero video games, is a pirate.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these games was not released by Nintendo?","Assassins Creed"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Super Smash Bros. Melee character can be unlocked by defeating the 10-minute melee?","Falco"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee can be unlocked by beating the game with every character?","Mr. Game and Watch"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee did not have a grapple ability?","Zelda"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Pokemon character in Super Smash Bros. Melee damages itself by using its B button moves?","Pichu"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee is the final boss of the normal game (Classic Mode)?","Master Hand"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee could jump more than once in midair?","Kirby"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee is unlocked by beating the game with a character from the same game?","Roy"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee had the ability to pick up other characters and walk with them?","Donkey Kong"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following game series featured the most Super Smash Bros. Melee characters?","Mario"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character in Super Smash Bros. Melee does not have a saving Up B button move?","Yoshi"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the main character in the 2006 third-person shooter Gears of War?","Marcus Fenix"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In video game Gears of War, these creatures let loose loud piercing shrieks when they attack but are generally easy to kill.","Wretches"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Gears of War, if you stay in the dark and walk slowly, the mutant race Kryll wont attack you.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Gears of War, which of these creatures is blind, walks upright and hunts by smell?","Berserker"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the third-person shooter Gears of War, can you kill the Corpser in the Locust tunnels by using the Hammer of Dawn?","No"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the Colonel who is in command according to the scenarios in Gears of War?","Hoffman"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Gears of War game, which member of Alpha Team is first found fighting in a small courtyard, alone and taunting the Locust?","Cole"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which difficulty setting can only be unlocked by completing Gears of War once on any difficulty?","Insane"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["General RAAM is protected by the mutant race Kryll when you try to kill him on the train at the end of Gears of War.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these dragons is the strongest in the Runescape game?","Black Dragon"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Runescape creatures drops a Dragon 2H Sword?","Chaos Elemental"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the city in Runescape that you unlock after the Lost City Quest?","Zanaris"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is the postal service in Runescape?","RPDT"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Runescape game you get a fishing skillcape in the Legends Guild.","False"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many forms does the Calphite Queen have in the game Runescape?","2"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these pets can you own in Runescape?","Kitten"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You can own a pet rock in the Runescape game.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the action/adventure game Killer7, the name of the assassin who can change between seven deadly personalities is Harman Smith.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which persona from the Killer7 game is the one with the Scope on his/her Automatic?","Kaede"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Killer7, what is the character Con Smiths’ age?","14"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which voice-over actress, who has also done voices for Nickelodeon, is the voice of Kaede in Killer7?","Tara Strong"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of character Iwazarus ex-wife in the action/adventure game Killer7?","Mizaru"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the game Killer7, what is the name of Harmans maid?","Samantha"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The only time you can use the save feature in Killer7 is when character Samantha is in what costume?","Maid uniform"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Mask De Smith’s profession before coming apart of the killers’ team in Killer7?","Professional wrestler"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the action/adventure Killer7, who is the only informant able to contact the Killer7 team?","Christopher Mills"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Besides your Avatar, what other characters can you get at the beginning of the game Baldurs Gate II: Shadows of Amn?","Imoen, Jahiera, Minsc"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where can you get the gauntlets of ogre power in the game Baldurs Gate II: Shadows of Amn?","The Planar Sphere"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What ranger can you save in the game Baldurs Gate II: Shadows of Amn by defeating the Shadow lord in the ruin temple?","Merella"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What organization takes Imoen from you, after you escape the first level in the game Baldurs Gate II: Shadows of Amn?","The Cowled Wizards"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who kidnaps Nalia in the game Baldurs Gate II: Shadows of Amn?","Isaea Roenal"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 2007 RuneScape Easter special, what item or items do you earn by helping the Easter bunny?","A chicken suit"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What two special benefits do RuneScape members get?","special tree logs and special locations"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the RuneScape game, it is illegal to use a macroer.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the RuneScape game, the woodcutting skillcape lets you save a bird from a tree.","True"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On a non-member world in RuneScape, how many places can you travel to on the ship in Port Sarim?","1"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal is Santa on the 2005 RuneScape Christmas special?","wolf"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the dog the main character is trying to save in the Dogs Life video game?","Daisy"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What changes on the dog every time you go to a different Poodle Parlour in the video game Dogs Life?","his collar"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what location do you first have to run away from the dog catcher in the Dogs Life video game?","Village center"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When you pick up scents in the game Dogs Life, which of the following is not part of a competition with another dog?","Barking competition"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the names of Miss Peaches henchmen in the Dogs Life game?","Wayne and Dwayne"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Dogs Life video game, what challenge do the purple scents start?","Collect them all before time runs out"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What improves your speed, stamina, and health in the game Dogs Life?","bones"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT found at the grooming parlour in the video game Dogs Life?","shaver"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many places can you go to by train in the Dogs Life game?","3"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the radio show in the game Dogs Life?","The Loud Brothers Live"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What button do you press to dig in Dogs Life (PS2)?","Circle"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What color is Miss Peaches hair in the video game Dogs Life?","Orange"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is the Lucky 7s Machine located in the game Dogs Life?","Lake Minniwahwah Cafe"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Dogs Life video game, what is the name of the group of bandits at Boom City?","The Sleeping Bandits"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What color is the jacket the girl wants you to get from the ski slopes in the video game Dogs Life?","yellow"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Dogs Life video game, what does the girl NOT ask you to bring to make her snowman?","a scarf"],"tags_json":"[\"trivia\",\"video-games\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
