{"kind":"deck","format":"deez.nut","version":2,"name":"Celebrities v7"}
{"kind":"note","note_type":"basic","fields":["Morris Chestnut starred in Like Mike along with Lil Bow Wow.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album The Wall contains these lyrics:","Comfortably Numb"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album The Wall opens with these lines:","Another Brick in the Wall"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album The Dark Side of the Moon contains these lyrics:","Brain Damage"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album Wish You Were Here includes these lyrics:","Have a Cigar"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album The Dark Side of the Moon opens with these lyrics:","Eclipse"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Pink Floyds album Wish You Were Here contains these lyrics:","Welcome to the Machine"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by rock band Evanescence opens with these lines:","Even in Death"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which single, recorded by rock group Evanescence contains these lines:","Surrender"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song, recorded by Evanescence begins with these lyrics:","October"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song released by rock band Evanescence contains these lines:","Give Unto Me"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song from the debut album of Evanescence includes these lyrics:","Whisper"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by Evanescence on the album Origin includes these lyrics:","Where Will you Go"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement is true about Lenny Bruce?","He was born Leonard Alfred Schneider in Mineola, Long Island, NY."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lenny Bruces father was born in England and his mother was a dancer.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Select the correct statement concerning Lenny Bruce.","Lenny was a high school dropout."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement about Lenny Bruce is correct?","Lenny was married and divorced twice."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement about comedian Lenny Bruce is true?","Lenny and his wife Honey had one daughter, Kitty Bruce."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Lenny Bruces salary for his first comedy job?","$12 and a spaghetti dinner."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lenny Bruce was arrested in 1951 in Miami, Florida on what charges?","Imitating a priest"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement concerning Lenny Bruce is incorrect?","Lenny recorded his first two albums at his own expense."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lenny Bruce made a big name for himself at what famous North Beach venue?","The Hungry i"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which TV show did Lenny Bruce make his debut?","The Steve Allen Show"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What were the charges on which Lenny Bruce was arrested in San Francisco in 1961?","Obscenity"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1964 Lenny Bruce was arrested for obscenity at what famous New York City club?","Cafe Au Go Go"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement about Lenny Bruce is incorrect?","Lennys last years were his most successful years as a comic."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This star, who got her start on Entertainment Tonight, shares a birthday with a boyfriend she started dating in 2006.","Vanessa Minnillo"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Matthew Gray Grubler, who plays Dr. Spencer Reid on the CBS hit show Criminal Minds (2005) shares his birthday with rapper Chingy.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This star, born in 1980, happens to be the youngest cast member of the shows Jackass and Viva La Bam.","Chris Raab"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elden Henson, who starred as Fulton Reed in the Mighty Ducks trilogy, was born on August 30, 1980.","False"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This sports star happens to have his name on the side of a Vitamin Water bottle. He is known for his speed as well as his good looks.","Kasey Kahne"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following lyrics are from which song by Carbon Leaf?","One Day"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Red Hot Chili Peppers band member dated Irish singer Sinead OConnor, known for her shaved head?","Anthony Kiedis"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Albert Einstein possessed one of the most talked about and copied hairstyles in history. How did he often handle curious people who stopped him in the street to ask questions about his theories?","He would say, Pardon me, sorry! Always I am mistaken for Professor Einstein."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elvis Presleys hairstyles have always been an inspiration for his fans and stylists alike. Which member of the Beatles and huge Elvis fan once said, Nothing really affected me until I heard Elvis. If there hadnt been an Elvis, there wouldnt have been a Beatles?","John Lennon"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mogul Donald Trump, who is also famous for his signature hairstyle, is keen on what sport?","Golf"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Multi award-winning pop singer Cher, who is known for her hairstyles, her huge wig collection and extravagant outfits, was one of the first women to expose this part of her body on television.","Navel"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Football player David Beckham, known for often changing his hairstyles, confessed that he is addicted to what sensation?","The pain of needles"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Danish dance-pop band Aqua was once famous for its members insanely unusual hairdos. What member of the band did lead vocalist Lene Nystrom marry in 2001?","None of them"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Spice Girls are among the iconic phenomena that marked the 1990s show business. Their outfits and hairstyles were copied by fans around the world and this phrase became their signature slogan.","Girl power!"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tionne Watkins, one of the female artists with a signature hairdo, became famous as a member of this band.","TLC"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Gwen Stefani was known for her crazy hair, back when she was a member of No Doubt. What was her hair color on the cover of the bands album Return of Saturn?","Bright pink"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by Linkin Park do these lyrics belong to?","My December"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ed McMahon was born in Los Angeles, California.","False"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Ed McMahon and Johnny Carson join The Tonight Show?","1962"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ed McMahon served in the Navy.","False"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ed McMahon was married 3 times fathering how many children?","5"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What real estate mogul offered to purchase Ed McMahons home in 2008 so it would not be foreclosed?","Donald Trump"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ed McMahon appeared in the 2005 movie Fun with Dick and Jane.","False"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["McMahon appeared alongside what popular 1990s rapper in a Cash for Gold commercial?","MC Hammer"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What job did Ed McMahon take in Maine when he was 15?","bingo caller"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ed McMahon starred in an episode of Baywatch.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following lyrics are from a song by Hootie and the Blowfish, included in their album Cracked Rear View:","Hold My Hand"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These are the opening lines of which song, recorded by Hootie and the Blowfish:","Old Man Me"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by Hootie and the Blowfish opens with the following lines:","Only Lonely"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These lyrics are from a song on Hootie and the Blowfishs album Musical Chairs:","Michelle Post"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by Hootie and the Blowfish begins with these lines:","Innocence"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following lyrics are from which song, included in the sixth studio album by Hootie and the Blowfish:","Get Out of My Mind"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song on Hootie and the Blowfishs debut album contains these lines:","Drowning"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song by pop-rock band Hootie and the Blowfish opens with the following lines:","Goodbye"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which song, written by guitarist Mark Bryan, contains the following lyrics:","Earth Stopped Cold at Dawn"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Hootie and the Blowfishs song from the album Musical Chairs includes these lines:","Las Vegas Nights"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Before the Jonas Brothers became a pop group of three, there was a music project of just this one of the brothers.","Nick Jonas"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the first names of the Jonas Brothers?","Nick, Joe and Kevin"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what U.S. state did The Jonas Brothers band originate?","New Jersey"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Disney Channel movie features The Jonas Brothers?","Camp Rock"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2007-2008, The Jonas Brothers have appeared in all of the following television shows, except this one.","The View"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of the Jonas Brothers plays the tambourine, guitar, and keyboards?","Joe Jonas"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nick Jonas starred in the Broadway plays Les Miserablesand Beauty and the Beast.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Nick Jonas first single?","Dear God"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor starred opposite Meg Ryan in the 1998 movie City of Angels?","Nicolas Cage"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the popular 1995 romantic comedy in which Meg Ryan starred opposite Kevin Kline.","French Kiss"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Meg Ryan voiced the protagonist in this popular 1997 animated movie.","Anastasia"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first movie in which Meg Ryan and Tom Hanks starred together?","Joe Versus the Volcano"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Meg Ryan starred opposite this Oscar-winning actor in the 1996 war movie Courage Under Fire.","Denzel Washington"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Clash lead singer Joe Strummer has a daughter with this interesting name.","Jazz Domino Holly"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unusual name did David Duchovny and Tea Leoni give to their second child?","Kyd"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Alec Baldwin and Kim Basinger named their daughter after this country.","Ireland"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first-born son of rapper Game is named after this neighborhood of New York City.","Harlem"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Professional tennis player Arthur Ashe has a daughter with this unusual name.","Camera"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Stings daughter who was born on April 17, 1982 was named after this flower.","Fuchsia"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1989, this member of Irish band U2 became father of a girl named Blue Angel.","The Edge"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kurt Russell and his first wife actress Season Hubley named their son after this U.S. city.","Boston"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American RB singer named her first-born daughter Heaven Loveon Stone?","Lil Mo"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name did actors David Carradine and Barbara Hershey give to their son, born in 1972?","Free"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following lyrics are from what song by My Chemical Romance:","Jack the Ripper"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These lyrics are from which 2004 song by My Chemical Romance:","Thank You for the Venom"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of Madonnas debut single released in 1982?","Everybody"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country was football star Ronaldo Luis Nazario de Lima, better known as simply Ronaldo, born?","Brazil"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The birth name of what popular American rapper is Cornell Haynes, Jr.?","Nelly"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["English model, actress, author and singer Lesley Hornby adopted this stage name and later legalized it as her real name.","Twiggy"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Richard Hall, better known as Moby, was nicknamed so by his parents due to which of the following?","He was related to Herman Melville, the author of Moby Dick."],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actress and singer portrayed Mexican American singer Selena in the 1997 biographical movie Selena?","Jennifer Lopez"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The birth name of which U2 member is Paul David Hewson?","Bono"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the birth name of singer and model Rihanna?","Robyn"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Prince Rogers Nelson, better known as Prince, named after?","His father"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What disease did singer and songwriter Anastacia survive, after being diagnosed with it in 2003?","Breast Cancer"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sean Penn and Robin Wright gave this interesting name to their son, born in 1993.","Hopper"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The son of what popular Hollywood actor was called Jett?","John Travolta"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Popular chef and TV host Jamie Oliver gave this unusual name to his first-born daughter.","Poppy Honey"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal name did soul singer Erykah Badu give to her daughter born in 2004?","Puma"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Will Smith and Jada Pinkett Smiths daughter who was born in 2000 was given this interesting tree name.","Willow"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Director and producer Kevin Smith named his daughter after this villain from the Batman comic series.","Harley Quinn"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["RB diva Toni Braxton named gave this unusual fabric name to her first-born child.","Denim"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular model named her daughter Princess Tiaamii Crystal Esther Andre?","Jordan"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular rock musician has a daughter named Calico?","Alice Cooper"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Grammy-winning musician John Mellencamp gave this unusual name to one of his sons.","Speck"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following words were spoken by Marlene Dietrich:","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On July 23, 1984 Vanessa Williams made the headlines when she gave up which of the following?","Her Miss US title"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Vanessa Williams parents write on her birth announcement, that turned out to be a prophesy?","Here she is: Miss America"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What music instrument did Vanessa Williams learn to play when she was growing up?","Piano"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Vanessa Williams debut album, released in 1988?","The Right Stuff"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Vanessa Williams eighth studio album, released on June 2, 2009?","The Real Thing"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Vanessa Williams starred alongside this huge action star in the 1996 movie Eraser.","Arnold Schwarzenegger"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of these popular TV shows has Vanessa Williams made a guest appearance?","All of these"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Vanessa Williams character in the popular TV show Ugly Betty?","Wilhelmina"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name did Vanessa L. Williams choose for her first-born child, born in 1987?","Melanie"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the radio countdown that Homer listens to in an episode of The Simpsons where a song by Vanessa Williams is included.","Sign of Evil"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which member of Natasha Richardsons family was a great star in the movie industry?","All of these"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what age did actress Natasha Richardson make her film debut?","Four"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Natasha Richardson was married to this celebrated Hollywood actor from 1994 until her death in 2009.","Liam Neeson"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what 1998 comedy movie did Natasha Richardson star as the mother of twin girls played by Lindsay Lohan?","The Parent Trap"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular author did Natasha Richardson portray in the 1986 movie Gothic.","Mary Shelley"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Natasha Richardson was an activist for raising awareness about this disease, as her father died from it.","AIDS"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Natasha Richardson starred opposite Christopher Walken and Rupert Everett in this 1990 movie.","The Comfort of Strangers"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of character is Caroline Lane, played by Natasha Richardson in the 2002 romantic comedy Maid in Manhattan?","Socialite"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of accident caused actress Natasha Richardsons death on March 18, 2009?","Skiing accident"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the last movie in which actress Natasha Richardson appeared before her sudden death in 2009?","Wild Child"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Nirvanas album Nevermind contains these lyrics:","Smells Like Teen Spirit"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Nirvanas album In Utero contains the following lyrics:","Heart-Shaped Box"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This song is from Nirvanas album In Utero:","Pennyroyal Tea"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What cover song from Nirvanas album Bleach contains these lyrics:","Love Buzz"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Nirvanas album Nevermind contains the lyrics,","In Bloom"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this song off the Nevermind album, the phrase And I swear that I dont have a gun","Come As You Are"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which In Utero song are the lyrics,","All Apologies"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song on Bleach and Unplugged in New York contains the lyrics,","About a Girl"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from Nirvanas album Nevermind contains the lines,","Polly"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Epica song do these lyrics belong to:","Sancta Terra"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Epica song contains these lyrics:","Seif Al Din"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what New York City borough was Mary J. Blige born on January 11, 1971?","Bronx"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What family member taught Mary J. Blige how to sing when she was a child?","Her father"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the age of 17, Mary J. Blige recorded a cover of a song by this Grammy-winning female RB artist.","Anita Baker"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Mary J. Bliges debut album released on July 28, 1992 by Uptown Records?","Whats the 411?"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What notable hip hop and RB artist supervised the creation of Mary J. Bliges debut album?","P. Diddy"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["With what rap artist did Mary J. Blige collaborate on Ill Be There for You/Youre All I Need to Get By, a song that won her the first Grammy Award in her career?","Method Man"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What two musical genres is Mary J. Blige well known for combining?","Soul and hip hop"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What imposing music artist collaborated on Mary J. Bliges fourth album Mary?","All of these"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the song that Mary J. Blige and George Michael recorded together in 1999?","As"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song by Mary J. Blige became her first Billboard Hot 100 number one in 2001?","Family Affair"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What 30 Seconds to Mars song includes the lyrics,","Buddha for Mary"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was Donald Trump born?","New York City"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Donald Trumps reality TV show, which debuted in 2004?","“The Apprentice”"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Trump Place is a multi-building development located along this river.","the Hudson River"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name Donald Trumps first wife.","Ivana Trump"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who referred to Donald Trump as The Donald in an interview?","Ivana Trump"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2007, Forbes valued Donald Trumps wealth to how much?","$3.0 billion"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Donald Trump has a star on the Hollywood Walk of Fame.","True"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Donald Trump is known for enthusiastically practicing which of the following sports?","Golf"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Donald Trump marry his third wife, Melania Knauss-Trump?","2005"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What University did Donald Trump graduate from in 1968?","University of Pennsylvania"],"tags_json":"[\"trivia\",\"celebrities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
