{"kind":"deck","format":"deez.nut","version":2,"name":"People v6"}
{"kind":"note","note_type":"basic","fields":["Eva Peron died before reaching the age of 35.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 1996 movie Evita starred Madonna and Antonio Banderas.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This French actor won the Golden Globe Award for Best Actor for his performance in the movie Green Card.","Gérard Depardieu"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This popular French actor served in the French Indochina war but was dishonarably discharged from the military. He rose t stardom after he played the title role in the movie Rocco and His Brothers.","Alain Delon"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1944, this French actor and singer was discovered by Édith Piaf in Paris and she made him part of her act. He was married to Simone Signored and they co-starred in several films.","Yves Montand"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This French actor is famous for portraying fictional detective Jules Maigret. He also starred in Jean Renoirs acclaimed anti-war film La Grande Illusion.","Jean Gabin"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This French actor is best known to English-speaking audience for his roles in Black Swan and Oceans Twelve.","Vincent Cassel"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This French actor rose to fame with the success of the comedy movie The Policeman from Saint-Tropez.","Louis de Funes"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actor became famous after his performance opposite Brigitte Bardot in Roger Vadims drama movie And God Created Woman.","Jean-Louis Trintignant"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This comedy actors horse-like teeth became part of his trademark. He first gained popularity in French vaudeville and operettas. His first Hollywood movie was Around the World in Eighty Days.","Fernandel"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This American-born French actor played Connor MacLeod in the Highlander film series.","Christophe Lambert"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He played the villainous Sir Hugo Drax in the James Bond film, Moonraker and French detective Lebel in The Day of the Jackal.","Michael Lonsdale"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 8 April 2009 about 400 miles (640 km) east of Mogadishu, the Danish owned cargo ship MV Maersk Alabama was captured by pirates. What was the nationality of the whole crew?","American"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 4 April 2009 the French yacht Tanit was captured by pirates and all five people, including a 3-year-old child, were taken hostages. What was the outcome?","The French forces rescued four of the hostages,including the child, and the fifth one was killed."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On January 1, 2009 Somali pirates hijacked the Egyptian cargo ship Blue Star with 28 crew aboard. What kind of ransom did the pirates demand?","US$ 1,000,000"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the Somali pirates in general?","All of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to a BBC report, most of the Somali pirates fall into this category.","All of this"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Somali pirates were known for getting their weaponry from this country.","Yemen"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What predominant type of weapons was used by the Somali pirates?","All of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 28 January 2009, Japan announced its intention of sending a naval task force to support the international forces fighting against Somalian piracy. Why was this decision unusual for Japan?","The constitution of Japan allows the use of the military forces only for defence."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did the UN Security Council adopt a resolution allowing international land and sea occupations in the pursuit of pirates?","On December 17, 2008"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the anti-piracy campaign of the European Union that started on 2 January 2009 with the capturing of eight Somali pirates?","Operation Atlanta"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 2008 book Love Letters of Great Men plays a key role in the plot of this movie.","Sex and the City"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Message in a Bottle, what is the occupation of Theresa Osborne, who becomes fascinated by a mysterious, intriguing love letter, found in a bottle in the sand?","researcher for a major newspaper"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The Police song Message in a Bottle, a castaway on an island sends out a message in a bottle to seek love. What does he find on the shore a year later?","a hundred billion bottles"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous person wrote a love letter that contains the line, Sweet, incomparable Josephine, what a strange effect you have on my heart?","Napoleon Bonaparte"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Irish author wrote to his wife Nora Barnacle You are my only love. You have me completely in your power. They had their first romantic liaison on June 14 1904, the date that is the setting of one of his most notable novels.","James Joyce"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Passionate love letters were part of this couples timeless romance. They sometimes addressed each other as Dearest Scrupelshrumpilstilskin and Dearest Hubs.","Richard Burton and Elizabeth Taylor"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This US President and his wife, Abigail, exchanged over 1,100 letters.","John Adams"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Queen of England received from her future husband Henry VIII a love letter that contained the following line:My mistress and friend: I and my heart put ourselves in your hands..?","Anne Boleyn"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Hollywood legend wrote to his girlfriend Barbara Glenn, Darling I havent written because I have fallen in love and then went on to say that he was referring to his horse Cisco the kid.","James Dean"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actress said this: “Its going to seem idiotic to say this, but I think that at a given moment we all need a place to ourselves where we can refuge ourselves and cut ourselves off from the world.”","Milla Jovovich"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“The 100% American is 99% an idiot.” was a remark made by this non-American playwright.","George Bernard Shaw"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“How can I lose to such an idiot?” was a shout by this master of chess.","Aaron Nimzovich"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“While time, the endless idiot, runs screaming round the world.” was said by this American writer of poetry, plays and essays.","Carson McCullers"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous comedian of silent films said: “Man as an individual is a genius. But men in the mass form the headless monster, a great, brutish idiot that goes where prodded.”?","Charlie Chaplin"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Austrian journalist, writer, satirist, essayist, aphorist, playwright and poet who said, “Education is a crutch with which the foolish attack the wise to prove that they are not idiots.”","Karl Kraus"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous composer of the 17th 18th century said “If I decide to be an idiot, then Ill be an idiot on my own accord.”?","Johann Sebastian Bach"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“Half the world is composed of idiots, the other half of people clever enough to take indecent advantage of them” was uttered by this writer and Broadway critic.","Walter Kerr"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of the Beatles said this: “I resent performing for frisking idiots who dont know anything.”?","John Lennon"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which American lyrical poet, playwright and feminist wrote “April comes like an idiot, babbling and stewing flowers.”","Edna St. Vincent Millay"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This poet, painter and printmaker said, “What is grand is necessarily obscure to weak men. That which can be made explicit to the idiot is not worth my care.”","William Blake"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous playwright wrote: “Life is a tale told by an idiot -- full of sound and fury, signifying nothing.”?","William Shakespeare"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“Cluelessness - There are no stupid questions, but there are a LOT of inquisitive idiots.” is a quote by this American sociologist and author.","Larry Kersten"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["“The word user is the word used by the computer professional when they mean idiot.” is a quote from this winner of a Pulitzer Prize for Commentary.","Dave Barry"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what century did Greek philosopher Plato live?","5th-4th century BC"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Plato, the structure of society corresponds to the structure of which of the following?","Human soul"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Plato’s opinion, human society should be governed by people who possess these main virtues.","Wisdom and reason"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Platos influence has been especially strong in which of the following subjects?","Mathematics"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Plato believed that reality could not be perceived by which of the following type of people?","Those who use their senses"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What family relationship occupied much of the thoughts of Greek philosopher Plato?","Father-son relationship"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the famous ancient school founded by Plato in Athens?","Academy"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Plato was the middle name of Aristotle Onassis, the prominent shipping magnate of the 20th century.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what present day country was Aristotle Onassis born?","Turkey"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did Aristotle Onassis go after leaving his home country in 1923.","Buenos Aires, Argentina"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aristotle Onassis father had a fleet of how many ships?","10"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the age of 16, Aristotle Onassis spoke four languages.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aristotle Onassis had a notorious affair with this opera diva.","Maria Callas"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1954, Aristotle Onassis was investigated by the FBI for fraud against the U.S. government.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these women is the mother of Aristotle Onassis’ two children?","Athina Livanos"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What member of Aristole Onasis family died in a plane crush?","his son"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Athina Onassis Roussel is the granddaughter of Aristotle Onassis.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which country was David Beckham born on May 2, 1975?","England"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was David Beckhams dream job back when he was a child?","Football player"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["David Beckhams parents were ardent fans of this football team, and they passed the passion to their son.","Manchester United"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first football club for which David Beckham played professionally?","Tottenham Hotspur"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of David Beckhams first-born son?","Brooklyn"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who became the godfather of David and Victoria Beckhams sons Brooklyn and Romeo?","Elton John"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the 2002 movie that involved David Beckhams name?","Bend It Like Beckham"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why did David Beckham have numerous tattoos done all over his body?","He was addicted to it."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What TV host made David Beckham take off his Shirt on their TV show in April 2008?","Ellen DeGeneres"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fragrance for men released by David Beckham in 2007?","David Beckham Instinct"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the shortest way to a womans heart according to Casanova?","Gratitude"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the popular partly autobiographical book written by Casanova?","Story of My Life"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first name of Casanova, the most popular lover ever born?","Giacomo"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Casanova graduated from the University of Padua, Italy, with a degree in this academic field.","Law"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Casanova had a brief career in this institution.","Church"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Casanova once save the life of a Venetian nobleman of the Bragadin family?","By having him bled"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Casanova was good at playing this musical instrument and he even became a professional musician for some time.","Violin"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Apart from women, this remained Casanovas uncontrollable passion throughout his whole life.","Gambling"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These are believed to have been the very last words of Casanova before his death.","I have lived as a philosopher and I die as a Christian."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This prolific writer and actress co-starred with her husband, Roy Rogers, in the popular television series, The Roy Rogers Show.","Dale Evans"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This character from the sitcom Green Acres, portrayed by Eva Gabor, was the wife of Oliver Wendell Douglas, a successful New York City attorney.","Lisa Douglas"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This character, portrayed by Ellen Corby, was married to Zeb Walton in the TV series, The Waltons.","Esther"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Fred Astaires famous dancing partner in the films Roberta, The Gay Divorcee and Shall we Dance?","Ginger Rogers"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the TV series The Brady Bunch, this widowed architect married Carol Martin.","Mike Brady"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This famous alcoholic actor starred in The Bank Dick. He was also quoted saying I never drink anything stronger than gin before breakfast.","W.C. Fields"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous alcoholic film actor is best known for his romantic swashbuckler roles such as his role in The Adventures of Robin Hood?","Errol Flynn"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the famous alcoholic who was Republican Senator from Wisconsin between 1947 and 1957 and made freewheeling accusations of communist sympathies against people in the U.S. government.","Joseph McCarthy"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fictional alcoholic from The Andy Griffith Show?","Otis Campbell"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which alcoholic singer and movie actor was partnered with Jerry Lewis for many years?","Dean Martin"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This famous American poet and short story writer, alleged to have died as a result of alcoholism, wrote the poem The Raven.","Edgar Allan Poe"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the animated alcoholic which was known for his belches on The Simpsons?","Barney Gumble"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which politician, who suffered from alcoholism, was the 14th President of the United States?","Franklin Pierce"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which American jazz singer, a famous alcoholic, was also known as Lady Day?","Billie Holiday"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This popular American film actress and pin-up model, who starred in I Married a Witch in 1942, died as a result of her drinking problem.","Veronica Lake"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Shakespearean actor, suffering from alcoholism, was nicknamed The Great Profile?","John Barrymore"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which American author, who frequently exhibited eccentric behavior, due to his alcoholism, wrote In Cold Blood and Breakfast at Tiffanys?","Truman Capote"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Dave went all the way from driving a talking car to judging whether or not Americas Got Talent.","David Hasselhoff"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This would-be jockey became the heartthrob of the made for TV band The Monkees.","Davy Jones"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dave Couliers first starring TV role was in the Nickelodeon Classic Show Cut it Out!.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dave Thomas named his restaurant chain after his daughter.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dave Thomas co-starred with which SCTV veteran in the cult classic Strange Brew?","Rick Moranis"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["David Duke, the former Republican representative for Louisiana, is famous for heading what other organization?","Ku Klux Klan"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This humor columnist was syndicated nationwide before he retired in 2005.","Dave Barry"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["David became the first King of Israel after slaying Goliath.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["David Schwimmer, who co-starred in the television show Friends, plays a hypochondriac character in which animated movie?","Madagascar"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Canadian actor lived on the Dog Creek Reserve until he was 8?","Adam Beach"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This B-movie actress was born on March 10, 1957, in St. Johns, Newfoundland.","Shannon Tweed"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which actress was born on October 17, 1948 in Yellowknife, Northwest Territories?","Margot Kidder"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was born in Wilmot Nova Scotia in 1844, and was the first man to sail around the world alone.","Josua Slocum"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous person was born on October 25, 1912 in Hamilton, Ontario?","Jack Kent Cooke"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Canadian author is known for his novel which was adapted into a Kevin Costner movie.","W.P. Kinsella"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which celebrity was born Eileen Regina Edwards, in Windsor, Ontario?","Shania Twain"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Canadian is the inventor of basketball?","James Naismith"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous journalist was born in Toronto Ontario on July 29, 1938?","Peter Jennings"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This famous Canadian actor, who starred in over 100 movies and TV shows, is best known for playing either cowboys or ordinary people in extraordinary circumstances.","Glenn Ford"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of Henry VIIIs chancellors had an international reputation as a great Renaissance Humanist?","Sir Thomas More"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["While Elizabeth I never married, she retained a lifelong attraction to her Master of Horse, Robert Dudley, who was honored with this title.","Earl of Leicester"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elizabeth Is privateers, known as Sea Dogs, were a colorful chapter in her reign. One of these claimed international celebrity by circumnavigating the globe. Name him.","Francis Drake"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bloody Mary was the pejorative nickname given to Mary Stuart, Queen of Scots.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is one of those dynastic ironies that the great royal enemy of Elizabeth I of England, Philip II of Spain, was also related to her in what way?","He was her brother-in-law."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of he following famous English dramatists was NOT a part of the Elizabethan era?","Richard Sheridan"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Tudor dynasty was founded by a Welsh adventurer, Owen Tudor, who gained prominence by marrying the widow of Henry V, Margaret Beaufort.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mark Twains well loved story, The Prince and the Pauper involves the adventures of a teenage pauper and this English Prince who exchange their roles and identity.","Edward VI, son and heir of Henry VIII"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Tudors are credited with their skillful use of Parliament. Yet, Parliaments met infrequently at the royal pleasure. Elizabeth I ruled almost a half century and called only 4 Parliaments during her entire reign.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first woman to be elected to the U.S. Congress?","Jeannette Rankin"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There were no women among the first 12 astronauts who set foot upon the moon.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Billy the Kids real name?","Henry McCarty"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Billy the Kid was virtually unknown in his own lifetime.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Billy the Kid was born November 23 of what year?","1859"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Billy the Kid was one of the founding members of a vigilante group known as The Regulators.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is believed that Billy the Kid was born in this state.","New York"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Billy the Kid was left handed.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what state did Billy the Kid die?","New Mexico"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Billy the Kid killed 21 men in his lifetime.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which President of the United States said the following, You can teach a child to read, and he or her will be able to pass a literacy test.?","George Bush"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which politician said these words, I think gay marriage should be between a man and a woman.?","Arnold Schwarzenegger"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which late President of the United States said the following, The world is more like it is now then it ever has before.?","Dwight D. Eisenhower"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This former member of the pop punk band Blink 182 was quoted as saying that he had never been to Kenya because Thats not a place where Im considered good-looking.","Mark Hoppus"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Prime Minister was quoted as saying A proof is a proof. What kind of proof? Its a proof. And when you have a good proof, its because it is proven.?","Canadian Prime Minister Jean Chretien"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What pro-golfer said, I owe a lot to my parents, especially my mother and father.?","Greg Norman"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What former Vice President of the United States said the following, We understand the importance of having bondage between the parents and their children.?","Dan Quayle"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What brilliant actress said, If youre killed youve lost a very important part of your life.?","Brooke Shields"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous football player stated, The word genius isnt applicable in football. A genius is a guy like Norman Einstein.?","Joe Theisman"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which magazine stated, We are sorry to announce that Mr. Albert Brown has been quite unwell, owing to his recent death, and is taking a short holiday to recover.?","Parish"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dr. Martin Luther King, Jr. graduated with a degree in Sociology from what college?","Morehouse College"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Martin Luther King, Jr. was president of this civil right organization which he led until his assassination.","Southern Christian Leadership Organization"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was Dr. Martin Luther King, Jr. awarded the Nobel Peace Prize?","1964"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The March on Washington for Jobs and Freedom, a large political rally at which Dr. Martin Luther King, Jr. delivered his famous I have a Dream speech, took place on what date?","August 28, 1963"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Letter from Birmingham Jail, an open letter by Dr. Martin Luther King, Jr., was first published in which of the following political magazines?","The New Leader"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which year did Time Magazine name Dr. Martin Luther King, Jr. Man of the Year?","1963"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who stabbed Dr. Martin Luther King, Jr. in the chest while he was autographing his recently published book in Harlem, New York?","Izola Curry"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is the name of the Memphis motel in which Dr. Martin Luther King, Jr. was assassinated on April 4, 1968?","Lorraine Motel"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what age was Dr. Martin Luther King, Jr. ordained a minister at Ebenezer Baptist Church in Atlanta?","19"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Martin Luther King, Jr. was awarded a PhD degree by which university?","Boston University"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This president was in office from 1789 - 1797. He was born in Westmoreland County, Virginia on February 22, 1732 and died of a throat infection on December 14, 1799.","George Washington"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This president was born in Albemarle County, Virginia on April 13, 1743. He was is office 1801 - 1809. He died on July 4, 1826.","Thomas Jefferson"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This U.S. President was in office from 1797 - 1801. He died on July 4, 1826.","John Adams"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This U.S. President is considered to be the Father of the Constitution.","James Madison"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. President made the first transcontinental phone call from the Oval Office?","Woodrow Wilson"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that on October 1909, President William H. Taft became the first President to walk into the Oval Office?","Yes"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dwight D. Eisenhower was in office 1945 - 1953.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is a first ladys correct name?","Elizabeth Virginia Wallace Truman"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When was U.S. president James Buchanan in office?","1857 - 1861"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Before becoming the 34th US President, he served as Supreme Commander of the Allied forces in Europe.","Dwight D. Eisenhower"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who defeated John Adams for reelection and became the third President of the United States?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which President delivered the famous words, Ask not what your country can do for you--ask what you can do for your country.?","John F. Kennedy"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What US President declared the freedom of the slaves?","Abraham Lincoln"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the leader of the Continental Army in the American Revolutionary War, who became the first President of United States.","George Washington"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was President of the US, when American astronauts landed on the moon in 1969?","Richard Nixon"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the first president to have won a Pulitzer Prize?","John F. Kennedy"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who assumed the Presidency in 1933, at the depth of the Great Depression?","Franklin D. Roosevelt"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On a mission over the Pacific as a torpedo bomber pilot this future US President was shot down by Japanese antiaircraft fire.","George H.W. Bush"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This US President was shot by a would-be assassin only 69 days after he assumed office.","Ronald Reagan"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Senator and Vice President Hubert Humphrey died in 1978 after a heroic battle with cancer.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This senator from the state of Washington was nicknamed Scoop and ran unsuccessfully for President.","Henry Jackson"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As a young boy this senator from Hawaii helped the fallen during and after the attack on Pearl Harbor.","Daniel Inouye"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 12, 2006, this senator broke the record for the longest serving senator when he left office at age 100.","Strom Thurmond"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following was invented by Samuel Leeds Allen?","Flexible Flyer"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This was the great invention of Edwin Howard Armstrong.","FM radio"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which name does not belong?","Brian Lee Chambers"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Harry Coover was trying to develop a gunsight lens when he invented this.","Superglue"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following was invented by a banjo player working at a company that made sandpaper?","Adhesive tape"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these men was responsible for the invention of fiberglass?","R. Games Slayter"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This was Stephanie Kwoleks big discovery.","Kevlar"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was B. B. Molloys invention?","Prozac"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Roy J. Plunkett invent?","Teflon"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Genoese explorer sailed off Spain on 3 August 1492 across the Atlantic Ocean and discovered the Americas?","Christopher Columbus"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This British captain explored the Pacific Ocean and was the first to reach New Zealand, Australia and Hawaii.","James Cook"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Venetian explorer, who lived in the 13th-14th century, traveled across Asia and wrote an account of his travels known as Il Milione.","Marco Polo"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the first astronaut to walk on the surface of the moon?","Neil Armstrong"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Scottish missionary and explorer of central Africa was the first European to see the Victoria Falls and name them in honor of Queen Victoria?","David Livingstone"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Portuguese explorer was the first to reach the Cape of Good Hope by sailing from Portugal?","Bartolomeu Dias"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first English explorer to sail around the world and return alive in England in 1580?","Francis Drake"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the Spanish explorer who conquered the Inca Empire?","Francisco Pizarro"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first explorer to reach the South Pole, and also the first person to reach both the North and South Poles?","Roald Amundsen"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Portuguese explorer became the first European to successfully reach India from Europe around the Cape of Good Hope.","Vasco da Gama"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Malcolm Xs father, Earl Little, was a Baptist minister.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many siblings did Malcolm X have?","10"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Malcolm X was a college graduate.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who did Malcolm X marry in 1958?","Betty Shabazz"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happened to Malcolm X in 1965?","He was shot."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Prompted by this person, Malcolm X converted to Islam.","his brother"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the First Lady who shared a name with one of the Muppets?","Mrs. Roosevelt"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Most of U.S. First Ladies belonged to which of the following religious denominations?","Episcopalian"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the First Lady who worked as a nurses aide in 1943?","Nancy Reagan"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["First Lady Mamie Eisenhower liked watching soap operas.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which First Lady was in China during the 1900 Boxer Rebellion?","Mrs. Hoover"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["First Lady Margaret Taylor reportedly prayed nightly for her husbands defeat in elections.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Eleanor Roosevelt, First Lady from 1933 to 1945, once served hot dogs to the King and Queen of England.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the First Lady who reportedly allowed her cows to graze on the White House lawn?","Eliza McCaudle Johnson"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the First Lady who reportedly crocheted 3500 pairs of slippers?","Ida Saxton McKinley"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was American gangster Al Capone born?","Brooklyn, New York, U.S"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the real first name of Al Capone?","Alphonse"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Al Capone led a crime syndicate during the Prohibition Era.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was Al Capone convicted by the US federal government for income-tax evasion?","1931"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Al Capones nickname?","Scarface"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Al Capone had a son known as Sonny.","True"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Al Capone was the boss of a criminal organization known as the Detroit Outfit.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The North Side gang shot into Al Capones entourage while he was having lunch at this place?","The restaurant of “Hawthorne Hotel”"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happened on Saint Valentines Day in 1929?","Al Capone arranged a gangland killing."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Al Capone resumed his criminal activities after completing his term in Alcatraz.","False"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Queen Elizabeth I of England is also known under this nickname.","All of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which wife of King Henry VIII of England was the mother of Queen Elizabeth I?","Anne Boleyn"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the Latin motto Video et taceo, which was one of the favorite mottoes of Queen Elizabeth I and largely defined her political strategy?","I see, and say nothing."],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the first husband of Queen Elizabeth I of England?","None of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What dangerous disease did Queen Elizabeth I survive in 1562?","Smallpox"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name is given to the speech Queen Elizabeth I of England addressed to the Commons on October 30, 1602?","Golden Speech"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What country sent its fleet to England with the intention to invade the country and overthrow Queen Elizabeth I of England, but was defeated in 1588?","Spain"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What celebrated poet worked during the reign of queen Elizabeth I of England, a.k.a. the Elizabethan era?","All of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Pope said of Queen Elizabeth I of England, She is only a woman, only mistress of half an island, and yet she makes herself feared by Spain, by France, by the Empire, by all?","Pope Sixtus V"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actress portrayed Queen Elizabeth I of England in the 1998 movie Elizabeth?","Cate Blanchett"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these crops did the Algonquin people of North America grow?","All of these"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these deities was especially worshiped by the Zuni Native American tribe?","Sun Father"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the oldest field sport in North America, which is practiced by the Choctaw Native American people?","Choctaw stickball"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did the Wyandot peoples of North America mainly provide food for themselves?","By growing crops"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The native American tribe, known as Hopi, called themselves Hopituh Shi-nu-mu. What does this mean?","The Peaceful People"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state did the Seminole nation originally populate?","Florida"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Nipmuc tribe is native to this U.S. state.","Massachusetts"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Mohave indigenous nation of North America called themselves Aha macave. What does this mean in English?","People who live along the river"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sitting Bull, Crazy Horse, Red Cloud, Black Elk and Billy Mills were from this Narive American tribe.","Lakota"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Iroquois nation of North America call themselves Haudenosaunee. What does this literally mean?","They Are Building a Long House"],"tags_json":"[\"trivia\",\"people\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
