{"kind":"deck","format":"deez.nut","version":2,"name":"Sports v6"}
{"kind":"note","note_type":"basic","fields":["This second baseman had a batting average of .424 in 1924 while playing with the St. Louis Cardinals.","Rogers Hornsby"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This second baseman played for the Twins and the Angels during his career.","Rod Carew"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This second baseman, elected to the Hall of Fame in 1989 by the Veterans Committee, played with Stan Musial, another Hall of Famer.","Red Schoendienst"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This second baseman played for the Cincinnati Reds with Pete Rose, Johnny Bench, and Tony Perez.","Joe Morgan"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which second baseman was known as the silent captain of the Red Sox?","Bobby Doerr"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This second baseman played for the Chicago Cubs in the 1980s.","Ryne Sandberg"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This second baseman was part of the New York Yankees murderers row.","Tony Lazzeri"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which two teams had the best NBA records in the 1997-1998 Season?","Chicago Bulls and Utah jazz"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the 1970-1971 season, which Eastern Conference team had the best record and got the Most Valuable Player Award?","Milwaukee Bucks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Los Angeles Clippers (known as the San Diego Clippers until 1984) had the worst record of the 1981-1982 NBA season.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The San Diego Clippers, who moved to Los Angeles, California and changed their name to the Los Angeles Clippers, finished 1984 with what record?","31-51"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What expansion team finished with the NBA worst win/loss record during their first season in 1995–96?","Vancouver Grizzlies"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which two NBA teams had the two best records in 1960-1961?","Boston Celtics and St Louis Hawks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1996-1997 season, which team broke the best record for an NBA season?","Chicago Bulls"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird was born on December 7, 1956.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird was born in French Lick, Indiana.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird graduated from Spring Valley High School.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird graduated from Indiana State in 1978.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird played 13 years with the Boston Celtics.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird was rookie of the year in 1980.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird has a street named after him.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird was a first round draft choice of the Pacers in 1978.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird was voted thirteen times in the All-Star team.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larry Bird never played in the Olympic games.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When keeping a baseball boxscore, which number signifies the shortstop?","6"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This baseball shortstop player donated $3.9 million to renovate the baseball field at The University of Miami and also won two Gold Gloves.","Alex Rodriguiz"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which player broke the record for the most home runs by a shortstop in one season in 2002?","Alex Rodriguez"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This shortstop had a great year in 1962 winning his second consecutive Gold Glove, the NL MVP Award, and hitting a homerun both rightly and lefty in one game.","Maury Wills"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Born in 1931 in Dallas, this player was a fan favorite as well as a Hall of Famer. He wore #14 and played his whole career for one team, a team whose inability to win had nothing to do with its star shortstops ability.","Ernie Banks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Joe Tinker was the shortstop in the famous combination Tinkers to Evers to Chance.“ What was the name of the famous poem that immortalized these three players?","Baseballs Sad Lexicon"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Venezuelan was a great fielding shortstop for the White Sox. On White Sox he teamed with Nellie Fox to form a great fielding duo. Who was this famous #11?","Luis Aparicio"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This college basketball coach won seven straight National Championships between 1967 and 1973. Four times his teams went 30 - 0 and, during a stretch between 1971 and 1974, his team won 88 straight games. He was known as The Wizard of Westwood.","John Wooden"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player, known as Chocolate Thunder, was the first to jump right from high school to the NBA.","Darryl Dawkins"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This two-time MVP player, known as The Mailman, was selected in 1996 as one of the 50 Greatest Players in NBA History.","Karl Malone"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This NHL player, known as Boom Boom, was credited with popularizing the slap shot. He was inducted into the Hockey Hall of Fame in 1972.","Bernie Geoffrion"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These NHL relatives were known as the Rocket and the Pocket Rocket.","Maurice and Henri Richard"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This NHL goalie won the Rookie of the Year in 1952 with the New York Rangers. Known as Gump, he was one of the last goalies to play the position without a mask.","Lorne Worsley"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements about Major League baseball player Marvellous Marv Throneberry is false?","He was chosen by the Mets in the 1961 Expansion Draft."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This switch hitter, known as the Commerce Comet, was inducted into the Hall of Fame in 1974.","Mickey Mantle"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This first baseman, known as Stretch, played 22 seasons of Major League baseball.","Willie McCovey"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This former NFL player, nicknamed Mad Stork, stood 67 and weighed 220 lbs. He began his playing career with the Baltimore Colts in 1969 – 1970.","Ted Hendricks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This NFL defensive back, called Night Train, began his career in 1952 and led the league in interceptions as a rookie. He was elected to the Professional Football Hall of Fame in 1974.","Dick Lane"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This football player, known as Sweetness, spent his entire 13-year career with the same NFL team. He ran for 275 yards in a game in 1977 and is one of the few players to run for, throw for, and catch a touchdown pass in the same game.","Walter Payton"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Both college and professional basketball have four quarters.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is no overtime period in NCAA basketball.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 8-second rule exists in both NBA and NCAA hoops.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["NBA and NCAA regulation courts are the same size.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["NBA and NCAA have the same number of players lined up along the lane while a free throw is being attempted.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When there is a held ball between two players, there is no jump ball in NCAA basketball.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In both the NBA and the NCAA you can choose any number you want for your jersey.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The number of timeouts for non-televised and televised college basketball games is the same.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Babe Ruths birth name was George Henry Ruth.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was Babe Ruth born?","1895"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many major league baseball teams did Babe Ruth play for?","3"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What number did the Babe wear for the New York Yankees?","3"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Babe Ruths second wife?","Claire"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Babe Ruth died in 1948.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Babe Ruth batted from the left side in the batters box.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many home runs did the Babe hit while playing major league baseball?","714"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Babe played his first game in major league baseball in 1914.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["With what team did Babe Ruth finish his major league baseball playing career?","Boston Braves"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement about athlete Danuta Rosani is true?","She was the first athlete in the track and field events to be disqualified in the Olympics for a banned substance."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The actor who played Oddjob in the Bond movie Goldfinger won an Olympic Medal. Which statement is true about him?","His name was Toshiyuki Harold Sakata."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Baseball Hall of Famer is credited with throwing the first curveball?","William Arthur Cummings"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is generally accepted that the phrase red herring, which has been in popular parlance for many years, is derived from which sport?","Fox hunting"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A pair of comedians neither of whom played pro baseball are enshrined in the Baseball Hall of Fame because of one of their routines.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What distinction does Masanori Murakami hold?","The first Japanese-born major league baseball player."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who has the highest ranking in an NFL game?","The Referee"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cleveland Tigers, the Muncie Flyers, the Hammond Pros, and the Dayton Triangles were some of the original teams in which league?","NFL"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which sport would you find Bay Matuka, Blue Charm, Green Highlander, Silver Stoat, and Logie?","Salmon Fishing"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What trophy is awarded to the Super Bowl-winning team?","Vince Lombardi Trophy"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What quarter back led in passing yards in 2002?","Rich Gannon"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who were the first two losing teams in the Super Bowl?","Chiefs and Raiders"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these NFL players played the most career games?","George Blanda"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What uniform number did Walter Payton wear when he played for the Bears?","34"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the first team to both play in and lose four Super Bowls.","Vikings"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was drafted by the Cleveland Browns first overall in the 2000 NFL draft?","Courtney Brown"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first NFL kicker to finish the regular season with a 100% success rate on field goals and extra points?","Gary Anderson"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who had the most touchdown passes in a season before Payton Manning set a new record?","Dan Marino"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What team did Tony Dorsett play for after he left the Cowboys?","Broncons"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the score of the 2008 Super Bowl?","17-14"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who had the most home runs in the 2007 Major League Baseball season?","Alex Rodriguez"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Red Sox swept the Colorado Rockies in the 2007 World Series.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Boston Celtics of 2007-2008 started out with the best start in Boston Celtic franchise history.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Suns traded Shaun Marion and a package of prospects to the struggling Miami Heat for Shaquille ONeal.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2007, the Minnesota Twins traded their ace Johan Santana to the Red Soxs for third baseman Mike Lowell.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what city and year did Muhammad Ali win the Olympic gold medal for the United States of America in the boxing light heavyweight division?","Rome 1960"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Muhammad Ali took up boxing as a result of someone stealing his bicycle.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Although Muhammad Ali was from Louisville, Kentucky he represented this major American city as a junior in the Golden Gloves.","Chicago"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Muhammad Alis first professional fight and victory against?","Tunney Hunsacker"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did Muhammad Ali defeat Sonny Liston to win the World Heavyweight Championship?","February 1964"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of his boxing opponents did Muhammad Ali label The Washer Woman?","George Chuvalo"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During a fight, Muhammad Ali kept asking this boxer, What is my name?.","Ernie Terrell"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Muhammad Alis last opponent before his boxing license was suspended in 1967?","Zora Folley"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who did Muhammad Ali fight against in his come-back match in 1970?","Jerry Quarry"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Joe Frazier defeated Muhammad Ali in the first of their 3 fights.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On his way to fighting George Foreman, Muhammad Ali lost a fight against this boxer.","Ken Norton"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Muhammad Ali get his jaw broken in a fight against Ken Norton in 1973?","Yes"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which African country did Muhammad Ali fight George Foreman in a match referred to as The Rumble in the Jungle?","Zaire"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name was given to the tactic that Muhammad Ali used to defeat George Foreman?","Rope a Dope"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the fight referred to as The Thrilla in Manila?","Ali won by a technical knock out after 14 rounds."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1978, Muhammad Ali lost to this boxer but then defeated him later that year, thus regaining the heavyweight championship title for a record 3rd time.","Leon Spinks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the 1988 Olympics, this lady earned a bronze medal, thus becoming the first African-American to win an Olympic medal.","Debi Thomas"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1989, the Figure Skating World Championships had a new nation as a contender for possible glory. Who was the first Japanese female skater to win the World Championships?","Midori Ito"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Japanese dynamo became the first lady to land a quadruple jump in competition. It was a junior competition, but it still counts as a figure skating first.","Miki Ando"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first lady to perform a successful triple Axel in a figure skating competition?","Midori Ito"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the 1992 Olympics in Albertville, this figure skater became the first Asian-American to medal at the Winter Olympics.","Kristi Yamaguchi"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1999, the reigning World Champion Michelle Kwan lost to a Russian who became the first woman from her country to win a Figure Skating World Championship. Who is she?","Maria Butyrskaya"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1994 in Lilihammer, this lady became the first Chinese skater to win a medal.","Lu Chen"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first Ladies Figure Skating World Champion was crowned in this year.","1906"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first lady to win the Figure Skating World Championships?","Madge Syers-Cave"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2005, Michelle Kwan won her 9th US title, tying the record set by what other American female skater?","Maribel Vinson Owen"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these ladies has 10 Figure Skating World Championship Gold Medals?","Sonja Hennie"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The NFL started out as the Ohio League.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two of the founding members of the NFL are in existence today. What are their original names?","Decatur Staleys and Racine Cardinals"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Detroit Lions entered the NFL in 1929 as the Detroit Lions.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Art Shell of the Oakland Raiders was the first African American head coach in the NFL.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1936, the NFL instituted the first ever draft of college players. Who was the first player ever drafted into the NFL?","Jay Berwanger"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the NFL Players Association formed?","1956"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1960 after being refused entry into the NFL as an owner, Lamar Hunt formed the rival AFL.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was a team in the NFL named the Carpets.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What university did Bob Gibson attend?","Creighton University"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the only Major League Baseball team Bob Gibson played for?","Cardinals"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of pitcher was Bob Gibson?","Starting righthander"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bob Gibson was the second pitcher to strikeout 3,000 batters. Who was the first?","Walter Johnson"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many times did Bob Gibson win a Golden Glove Award?","9"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many Cy Young Awards did Bob Gibson win?","2"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Bob Gibsons primary uniform number?","45"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As Bob Gibson was primarily a relief pitcher, he has not been voted into the Major League Baseball Hall of Fame.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Michael Phelps (USA, swimming) declared he would set a record by winning 8 gold medals at the Olympic Games in Beijing. How many did he actually win?","8"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country was represented by the highest number of athletes at the Olympic Games of 2008?","China"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who became the fastest man by setting a world record of 9.69s at the 2008 Olympics 100m run?","Usain Bolt (Jamaica)"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Athletes representing which discipline were the first to compete during the 2008 Olympic Games?","Football / Soccer"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two of the 2008 Olympic Games competitors, Natalia Partyka (Poland, table tennis) and Natalie du Toit (South Africa, swimming) are known for something very unusual. What do the two Natalys have in common, besides their first names?","They competed both in 2008 Olympic Games and 2008 Summer Paralympics"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country took all medals in the 100m womens sprint race at the Beijing Olympic Games?","Jamaica"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Ara Abrahamian (Sweden, wrestling) do at the medal ceremony for 84kg greco-roman event of the 2008 Summer Olympics?","Stepped from the podium, dropped his medal and walked off"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first days of the 2008 Olympic Games were held in the shadow of a military confrontation between Georgia and Russia. In which event did both countries representatives win medals and embraced on the podium?","Shooting - 10m air pistol, women"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Yelena Isinbayeva has often been referred to as the tsarina of pole vault, so it was not a surprise when she won the event at the Beijing Olympics. She also set a world record, by jumping this high.","5.05"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kirsty Coventry won four medals and set a new world record in the 200m backstroke at the 2008 Summer Olympic Games. Which country did she represent?","Zimbabwe"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Afghanistan, a poor war-torn country, managed to win a medal at the 2008 Summer Olympics. Which discipline was it in?","Taekwondo"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many of the four top-seeded female tennis players made it to the semifinals at 2008 Summer Olympics?","None"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the mens 200m sprint at the Beijing Olympic Games, the second and third athletes were disqualified. What for?","For running outside of their tracks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What two teams competed in the finals of the mens football (soccer) tournament at the Beijing Olympics?","Argentina-Nigeria"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first FA Cup final took place on this date.","16 March 1872"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this year Wembley becomes the official host of the competition.","1923"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This number of trophies have been in use during the competitions long history.","4"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The White Horse Final took place on this date.","28 April 1923"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which team won the most FA cups during the 1909-2005 period?","Manchester United"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Stanley Matthews won his first Ever FA Trophy while on this team.","Blackpool"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This side defeated Herbert Chapmans great Arsenal side 2-0 in 1933.","Walsall"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Clubs from the top divisions and the Premier League join the competition at this stage.","Third Round"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1978, Sir Bobby Robson wins his first FA Cup trophy as a manager of this team.","Ipswich Town"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this year Welmbley ceases from being the official host of the Competition.","2000"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was appointed NFL Commissioner after the retirement of Paul Tagliabue?","Roger Goodell"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1992 this owner and President of the Milwaukee Brewers became Commissioner of Major League baseball.","Allan Selig"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Beginning in 1998 he had a significant role in CBS getting the rights to NFL games through at least 2012. His father was a truly great sportscaster.","Sean McManus"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2002 this man, who was President of Indiana University, became President of the NCAA.","Myles Brand"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This company, with a huge ad budget in the world of sports, has a sports marketing division which creates advertising material for the Super Bowl.","Anheuser-Busch"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This basketball player, drafted by the Cleveland Cavaliers in 2003, is famous for doing commercials for Sprite, Nike, and Upper Deck.","LeBron James"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1986 he became Executive Director of the Major League Baseball Players Association.","Donald Fehr"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He is known as the owner of the Boston Red Sox and Roush Fenway Racing.","John Henry"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This family has had three starting NFL quarterbacks who have won at least two Super Bowls in a row.","Manning"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who purchased the Dallas Cowboys in 1989?","Jerry Jones"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Malcolm Glazer purchased these two teams in 1995 and 2005 respectively.","Tampa Bay Buccaneers and Manchester United"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 2008 owner of the Seattle Seahawks and Portland Trailblazers was a co-founder of this company.","Microsoft"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This prominent sports agent has represented some of the highest-paid baseball players, including","Scott Boras"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He grew up in a suburb of Pittsburgh. In 2002 he became the owner of the Dallas Mavericks.","Mark Cuban"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was born in 1987 and is considered one of the top player in his sport. He was nicknamed The Next One.","Sidney Crosby"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He has been a fine Super Bowl-winning NFL coach, a football commentator and a video game icon.","John Madden"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a bellhop, an aerobics instructor and an amateur boxer. In 1992 he began the UFC for mixed martial arts.","Dana White"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This agent has represented Yao Ming, Tracy McGrady, T.J. Ford, Ben Wallace, Jordan Farmar and Jermaine ONeal.","Arn Tellum"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He moved from running Radio City Music Hall to becoming CEO of The United States Tennis Association.","Arlen Kantarian"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He is one of the most influential sports agents in the NFL. His clients have included Steve Young, Troy Aikman, Warren Moon, and Kordell Stewart.","Leigh Steinberg"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the video, Searching for Animal Chin of successful skate team Bones Brigade, who was Animal Chin?","The master of skateboarding"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1980s Tony Hawks father, Frank Hawk was head of what organization?","The National Skateboard Association"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the two brothers who were both professional skaters in the late 70s, then resurfaced in the 80s to become dominant riders once again?","Steve and Mickey Alba"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This man, born in 1963 in New york, is the inventor of the ollie, a skateboarding move.","Alan Gelfand"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He invented the aerial skateboarding trick, McTwist and first performed it in public in 1984 at the Del-Mar Skatepark contest.","Mike McGill"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What skateboard company switched their focus and skyrocketed to success with their clothing line in the mid eighties?","Vision Street Wear"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In skateboarding, what is a Boneless one?","A classic trick, invented by Garry Scott Davis"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was on the cover of the first issue of Transworld Skateboarding magazine?","Steve Caballero"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Texas artist drew the artwork for Zorlac skateboards and was a regular contributing artist for Thrasher magazine.","Pushead"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the reader mail section of monthly skateboarding magazine, Thrasher, in the 1980s?","Mail Drop"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not one of the colors for the Atlanta Braves team uniforms?","Green"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the previous name of the Chicago Cubs?","Chicago Colts"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these became the Red Soxs home ballpark in 1912?","Fenway Park"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who broke Hank Aarons career home run record?","Barry Bonds"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What baseball team was founded in Manhattan in 1960?","New York Mets"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the cap insignia of the Los Angeles Dodgers?","A over L"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What baseball team played their first game on April 5, 1993?","Colorado Rockies"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which player, nicknamed The Captain, was the 1970 NBA Finals MVP?","Willis Reed"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player, called Cap or Captain, was the 1971 NBA Finals MVP.","Kareem Abdul-Jabbar"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player, nicknamed The Big Dipper, Goliath and Mr.100, became the 1972 NBA Finals MVP.","Wilt Chamberlain"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the 1974 NBA Finals MVP who was nicknamed Hondo.","John Havlicek"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What player nicknamed Greyhound was the NBA Finals MVP in 1975?","Rick Barry"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the NBA Finals MVP in 1976?","JoJo White"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player, nicknamed “Big Red-Head”, was the NBA Finals MVP in 1977?","Bill Walton"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the NBA Finals MVP in 1978?","Wes Unseld"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the NBA Finals MVP in 1979?","Dennis Johnson"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did karate originally begin?","Japan"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the karate terminology, what does kata mean?","Form"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is considered the father of Shotokan Karate?","Gichin Funakoshi"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Karate had a major influence on what other country also known for its martial art?","Korea"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which was the first US state in which karate was taught?","Hawaii"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A major concept of karate is attitude. What is it called in Japanese?","Kokoro"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these cyclists has the most Tour De France wins?","Lance Armstrong"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What golfer won his 18th major championship in 1986?","Jack Nicklaus"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What mens basketball team won their 11th NCAA Championship in 1996?","UCLA"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the listed NBA players has the most career points?","Kareem Abdul-Jabbar"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these former MLB players has the most career strike outs?","Nolan Ryan"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What MLB player set a record for most career hits in 1985?","Pete Rose"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What MLB player won his 7th MVP Award in 2004?","Barry Bonds"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What player won his 7th Cy Young Award in 2004?","Roger Clemens"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these former MLB players has the most career RBIs?","Hank Aaron"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these former NFL quarterbacks has the most passing yards?","Brett Favre"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On May 17, 1998 the Yankees won a perfect game 4-0 over the Twins. Who was the wining pitcher?","David Wells"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Joe Girardi caught a perfect game on July 18, 1999. Who was the winning pitcher?","David Cone"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the first man to catch more than one perfect game?","Ron Hassey"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first perfect game played in Calfornia was played in this city.","Los Angeles"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was the first 40-year-old to pitch a perfect game.","Randy Johnson"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the first team to win more than one perfect game.","Yankees"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first non-American born pitcher to pitch a perfect game?","Dennis Martinez"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first player to play in three perfect games?","Paul ONeil"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the first team to have three perfect games pitched against them.","Dodgers"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1917, a starting pitcher walked the first batter, was ejected and then the relief pitcher pitched perfectly for the rest of the game. Who was the ejected pitcher?","Babe Ruth"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On May 26, 1959 this pitcher pitched 12 perfect innings.","Harvey Haddix"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do these major leaguers have in common: Jim Bibby, Robin Roberts, Curt Simmons, and Woody Fryman?","They all pitched 27 consecutive outs but had perfect games foiled by the first batter."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this movie, the protagonist pitched a perfect game in his first pro baseball game.","The Scout"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pittsburgh Pirates were a great team in baseballs early years. Unfortunately they lost the first modern World Series in 1903 to this team.","Boston Red Sox"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1909 the Pirates won their first World Series versus the Detroit Tigers. This same year they started playing in this Ball Park that would be their home until 1970.","Forbes Field"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This famous actor/singer owned the Pittsburgh Pirates in the 1940s.","Bing Crosby"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On October 13,1960, the Pirates got a homerun from Bill Mazeroski. What is significant about this homerun in baseball history?","It was the first walk off homerun in a World Series Game 7 that won the Series against the Yankees."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pirates were the first team in Major League history to field an all black starting lineup.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This song by Sister Sledge was the anthem of the 1979 World Champion Pittsburgh Pirates.","We Are Family!"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pittsburgh Pirates moved from Three Rivers Stadium to this ball park at the start of the 2001 season.","PNC Park"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This catcher for the 1983 Phillies wore uniform #6. He was killed by a satellite dish that fell on him.","Bo Diaz"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player, nicknamed The Sarge, played left field for the 1983 Phillies and wore #34.","Gary Matthews"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He played 3rd base for the 1983 Phillies and wore uniform #20.","Mike Schmidt"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He played 1st base for the 1983 Phillies and wore uniform #14.","Pete Rose"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This center fielder for the 1983 Phillies was nicknamed Secretary of Defense and wore uniform #31.","Garry Maddox"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What shortstop for the 1983 Phillies wore uniform # 11?","Ivan DeJesus"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the right fielder for the 1983 Phillies who wore #9.","Von Hayes"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What player, wearing uniform #45, pitched the final strike for the 1980 World Champion Philadelphia Phillies?","Tug McGraw"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Stanley Cup at the end of the 1993-1994 season?","New York Rangers"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who were the Stanley Cup champions for the 1994-1995 season?","New Jersey Devils"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who sipped from the Stanley Cup following the 1995-1996 season?","Colorado Avalanche"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the NHL Stanley Cup winner for 1996-1997?","Detroit Red Wings"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which team captured the NHL title and the coveted Stanley Cup for the 1997-1998 season?","Detroit Red Wings"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the Stanley Cup champion in 1998-1999?","Dallas Stars"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which team won the Stanley Cup following the 1999-2000 season?","New Jersey Devils"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the NHLs holy grail for the 2000-2001 season?","Colorado Avalanche"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Stanley Cup went to this team following the 2001-2002 season.","Detroit Red Wings"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who got to take the Stanley Cup home to their families following the 2002-2003 season?","New Jersey Devils"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the Stanley Cup champion following the 2003-2004 NHL season?","Tampa Bay Lightning"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Stanley Cup for the 2004-2005 NHL season?","None of these"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the Stanley Cup winner for 2005-2006?","Carolina Hurricanes"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 2006-2007 NHL Stanley Cup Finals were won by this team.","Anaheim Ducks"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these horses is not a child of thoroughbred race horse, Seabiscuit?","Sea Orbit"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the trainer of thoroughbred race horse, Seabiscuit, that rarely spoke?","Tom Smith"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Barbaro went into the Kentucky Derby undefeated at 5-0.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Golf player A tees off, he mutters a few f-bombs as he watches his ball fly far right into trees and says, Ill play another one. Then he re-tees another ball. His 2nd ball is straighter - in the fairway. Player B claims foul as he did not say he was playing a provisional ball, using those exact words. What should then be done?","Player A is disqualified for illegally playing a shot."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A golf player addresses their ball and is half way through their backswing when a gust of wind rolled the ball back an inch. What is the ruling?","The player takes one penalty stroke and plays the ball as it lies."],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As you are making an attempt to strike the golf ball, the head of the club separates from the shaft on your backswing. You complete the swing but miss the ball. Did you make a stroke?","No"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A golf ball embeds into the side of the hole. How should the player who hit it proceed?","Place the ball on the nearest edge of the hole and play from there"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After marking their ball on the green, a golf player tosses it to their caddie to clean. Thanks to the caddies excellent hand-eye coordination, he dropped it and the ball rolled into a lake. How should the player proceed?","Either retrieve the ball from the lake and play on or take a 2 stroke penalty and continue the hole with a new ball"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You hit your tee shot deep into the woods, where it might be lost. You announce that youll play a provisional and immediately hit before your playing partner. Your buddy says you should be penalized for playing out of turn. What should you do according to golf rules?","Take no penalty because you were not going out of order to give one player an advantage"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["You mark your golf ball on the green with a coin, but when you return the ball to its spot, you realize you stepped on the coin and its now stuck to your shoe. What should you do?","Add 1 stroke to your score and replace it as near as possible to its original position"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After playing an approach shot into the green, you find that some prankster in the group ahead had jammed the flag some 40 feet from where the actual golf hole was. How do you proceed?","Play the ball as it lies"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Hockey Hall of Fame located in Toronto, Ontario, has inducted some of the greatest of hockey players over the years. Which member of the Montreal Canadiens was inducted into the Hockey Hall of Fame in 2006?","The 44th"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is no greater honour for a professional athlete to have his number retired by the franchise for which he used to play. Prior to the 2007-2008 season, how many retired numbers were there in the Montreal Canadiens hockey team?","11"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of all the great players’ numbers retired by the Montreal Canadiens, one number has actually been retired more than once. Which number is it?","12"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Montreal Canadiens Head Coach Guy Carbonneau was once a Habs player. What year was he traded and to which team?","1994 to the St-Louis Blues"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what season did the Montreal Canadiens win their first Stanley Cup?","1915-1916"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the Montreal Canadiens hockey team founded?","1909"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Before the 2009 playoffs began, New York Rangers head coach Tom Renney and this assistant coach were fired.","Perry Pearn"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2009, Tom Renney, ex-head coach of the New York Rangers, became the new assistant coach of what team?","Edmonton Oilers"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following New York Rangers retired after the 2008-09 season?","Markus Naslund"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This former ice hockey defenseman, born in Ontario, Canada, played 465 games as a New York Ranger and wore number 2.","Brad Park"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Glen Sather become President and GM of the New York Rangers?","2000"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1993 playoffs the New York Rangers beat the New Jersey Devils in 7 games in the Conference finals.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2009, New York Rangers defenseman Michal Rozsíval switched to this number.","33"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 2009 US Open Golf Championship was played at Bethpage Black. What was its par?","70"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Open Championship was first played on 17 October 1860 at this golf course.","Prestwick"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tiger Woods was the highest-paid professional athlete in 2008.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the first ever US Masters Golf tournament played?","Augusta National"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is a golfer said to have, if he is entitled to hit off first?","the honour"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Denim clothing is acceptable on most golf courses around the world.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What golf term refers to a score of a 3 on a par 5?","Eagle"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Tiger Woods win the US Open Championship held at Torrey Pines?","2008"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The US Open Tennis Championships were first contested in 1881 as the US National Championships. What events did the players compete in?","mens singles"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The US Open was originally played on grass and clay courts before moving to acrylic hard court.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Arthur Ashe Stadium is named after Arthur Ashe, the African-American tennis player.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What tennis player won the US Open in 1990, becoming the youngest ever US Open champion in mens singles?","Pete Sampras"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not one of the players who have won five US Open titles?","John McEnroe"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many times did Roger Federer defeat an American player in the final during his successive five championship wins (2004-2008)?","2"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did Bob and Mike Bryan win the US Open doubles final for the first time?","2005"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country won the maximum number of US Open championships since the beginning of the Open Era in 1968 until 2008?","United States"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Until 2008, only three Spanish players made it to the finals of the US Open. Manuel Santana and Manuel Orantes lifted the trophy in 1965 and 1975, respectively. Who stayed runner-up in the 2003 final?","Juan Carlos Ferrero"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 2002 mixed doubles US Open final, Bob Bryan, partnering with Lisa Raymond won the title, beating his brother Mike on the opposite side.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The production of the worlds first commercially available bicycles began in what year?","1867"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is generally agreed that riding on off-road paths is safer than riding on the street.","True"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of handlebar would you normally find on a road bike?","Drop handlebar"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Specialized Bicycle Components produce the first mountain bike called the Stumpjumper?","1982"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the mechanism at the bottom of pro-cyclists shoes?","Cleats"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What world famous trail is located near Moab, Utah?","Slickrock Bike Trail"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Looking to expand the alternatives for Bike to Work Day, Jeff Obst coined the phrase B-BOP (Bike, Bus, Or carPool) Day. In what year was this campaign initiated?","1991"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fat Tire Week takes place in what town in the state of Colorado?","Crested Butte"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This chess opening involves up to 3 knight moves in succession before any other piece or pawn is moved.","Alekhine"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This chess opening involves the move P-KB4 (f4) by white, and often the fianchetto of the queens bishop.","Birds Opening"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Fischer Defense to the Kings Gambit involves which of the following moves by black?","P-Q3, P-KN4, P-KR3, B-KN2"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first world champion, Steinitz lost many games against this opening which involves the moves 1 P-K4 P-K4 2 N-KB3 N-QB3 3 B-B4 B-B4 4 P-QN4.","Evans Gambit"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This chess opening was named after a mythical creature.","The Dragon Variation of the Sicilian Defense"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is a Hypermodern opening?","English Opening"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first move by white 1 N-KB3 could result in all of the following openings except which one?","Kings Gambit"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This chess opening involves no pawn moves beyond the third rank.","The Hedgehog Defense"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This defense to the first move P-K4 involves the move P-QB3. It is considered solid, and was a favorite of world champion Anatoly Karpov.","Caro-Kann Defense"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This defense to the first move P-K4 involves the move P-K3. It is a very difficult opening to play and was a favorite of Victor Korchnoi.","The French Defense"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are open, semi-open and closed openings. Which of the following openings would be considered an open game?","The Two Knights Defense"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Andy Corno is known as the starting face off midfielder for this lacrosse team.","Barrage"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these lacrosse teams was founded in Chicago?","Machine"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2004, this company acquired Warrior Lacrosse, the manufacturer of lacrosse equipment.","New Balance"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mens field lacrosse is played with how many players on each team?","10"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After graduating from Duke University, Matt Breslin became the goalie for this Major League Lacrosse team.","The Pride"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these lacrosse teams is paired with the correct city?","Toronto - Nationals"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In lacrosse, a slash is a 30-second penalty.","False"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This player started practicing tennis at the age of 12, choosing the sport over football. He has been given the Prince of Asturias Award for Sports.","Rafael Nadal"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1982, Spain hosted the FIFA World Cup for the first time. How many cities in Spain hosted this world tournament?","14"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many times a Spanish cyclist has won the Tour de France until 2009?","12"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What rank did Spain achieve on the Medal table in the Summer Olympics in 1992?","6th"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many games did Spain lose in the UEFA Euro 2008 Tournament?","0"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A variation of which of these sports is called Killer?","Pool"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country did the disc dog sport, commonly known as frisbee dog, originate?","United States"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what type of environment is the sport called parkour most often practiced?","In urban areas"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what other popular sport is the game called korfball similar?","Basketball"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of body movement is involved in the sport called snowkiting?","Gliding on ice"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which country did the sport called campdrafting originate?","Australia"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of sport is Popinjay, also known as Popingo?","Shooting"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what kind of surface is the sport called bandy practiced?","Ice"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of sport is enduro?","Motorcycle sport"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elements of which sport does the game called pickleball include?","All of these"],"tags_json":"[\"trivia\",\"sports\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
