{"kind":"deck","format":"deez.nut","version":2,"name":"Geography v2"}
{"kind":"note","note_type":"basic","fields":["When was the Skylon Tower, Niagaras most famous landmark, built?","in the 1960s"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Around the year 1859, Jean-François Blondin crossed the gorge below Niagara Falls on a tightrope 1100 feet (335 m) long, 160 feet (50 m) above the water. He made this accomplishment several times including which of the following theatrical variations?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state is nicknamed The Natural State?","Arkansas"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nickname has been given to the U.S. state of Oregon?","Beaver State"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What U.S. state is nicknamed Land of Infinite Variety?","South Dakota"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these nicknames has been given to the U.S. state of Colorado?","Switzerland of America"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these nicknames has been given to the U.S. state of Illinois?","Corn State"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This U.S. state was nicknamed Vacationland, and the nickname is used on license plates.","Maine"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Independence State is one of the nicknames of this U.S. state.","Pennsylvania"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state is nicknamed The Cowboy State?","Wyoming"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nickname has been given to the U.S. state of Rhode Island?","Ocean State"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The nickname Queen State has been given to this U.S. state.","Maryland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country, Slovakia or Slovenia, used to be part of Yugoslavia?","Slovenia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which former empire were both Slovenia and Slovakia part of?","Austria-Hungary"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Slovakia and Slovenia joined the European Union on the same day (May 1, 2004). Which of them was first to accept the euro currency?","Slovenia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital of Slovakia?","Bratislava"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital of Slovenia?","Ljubljana"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country borders both Slovenia and Slovakia?","Austria"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement concerning Slovakia and Slovenia is true?","Slovenia has access to the Adriatic Sea."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Danube river flows through many Central European countries. Which of these statements concerning Slovakia and Slovenia is true?","Of the two countries, only Slovakia has Danubian banks."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements regarding Slovakia and Slovenia is true?","Only Slovenia is an Alpine country."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country, Slovakia or Slovenia, borders a country that did not join the European Union in the period 1951-2007?","Both share borders with countries that did not became EU members during this period."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What design is depicted on the national flag of Switzerland?","Cross"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Switzerland is often associated with this product which is produced at the highest quality in the country.","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the unofficial national motto of Switzerland?","One for all, all for one"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital city of Switzerland?","Bern"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What mountain covers about 65% of the territory of Switzerland?","the Alps"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What language is adopted as official for the territory of Switzerland?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Switzerland?","Swiss Psalm"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the main ingredient of the traditional Swiss dish Rosti?","Potatoes"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest city in Switzerland?","Zurich"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous philosophers was of Swiss descent?","Jean-Jacques Rousseau"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is the capital and the largest city in North Korea?","Pyongyang"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of climate does North Korea have?","Continental"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these seas surrounds the Korean Peninsula, in the northern part of which North Korea is located?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The establishment of the Democratic Peoples Republic of Korea in this year set the official beginning of North Koreas history.","1948"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the division of Korea into two parts?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these natural disasters is known to hit the lands of North Korea on the regular?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language that is spoken in North Korea?","Korean"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these religious movements has many adherents among the people of North Korea?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these musicians became the first US musical group ever to perform in North Korea?","The New York Philharmonic Orchestra"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these events is regularly performed only in North Korea?","Mass games"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What other name is commonly used to refer to the Colorado River in North America?","Red River"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the longest river in the United States of America?","Missouri"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Ohio River does not flow though the territory of this American state.","Virginia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the longest river located entirely within the territory of the state of California?","Sacramento River"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the name of the Mississippi River, which originated from the Ojibwe word misi-ziibi?","Great river"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What ocean fish migrates from the Pacific Ocean to the Columbia River to spawn at the end of their life cycles?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the The Rio Grande river called in Mexico?","Rio Bravo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What river in North America provides food for the largest wintering Bald Eagle population in the continental United States?","Skagit River"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Mohawk name of the Saint Lawrence River, Kaniatarowanenneh, mean?","Big waterway"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["More than half of the Yukon River is located within this American state.","Alaska"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital and largest city of Norway?","Oslo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to some medieval texts, the name of Norway originated from the name of which of the following?","The name of a king"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of government does Norway have?","Constitutional monarchy"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal is depicted on the Coat of Arms of Norway?","Lion"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the predominant form of Christianity in Norway?","Protestantism"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language adopted by the government of Norway?","Norwegian"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Norway?","Yes, We Love This Country"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Bunad?","A Norwegian costume"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the popular Norwegian delicacy called Smalahove made from?","Lamb head"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is present on the national flag of Norway?","Cross"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest carnivorous mammal endemic to the island of Madagascar?","Fossa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about Madagascar?","None of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Madagascar, written by Norbert Raharisoa and composed by Rahajason?","Oh, Our Beloved Fatherland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the colors on the national flag of Madagascar, adopted on October 14, 1958?","White, red and green"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city is the capital and largest city of Madagascar?","Antananarivo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the official languages spoken in Madagascar?","Malagasy, French and English"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name some ecologists use wen referring to Madagascar?","The eight continent"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of traditional ritual is the Famadihana, practiced by the Malagasy people in Madagascar?","Turning of the dead"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of meal is the godro-godro, which is very popular in the Madagascar cuisine?","Pudding"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This tree is a very important part of the Madagascar dry deciduous forests and six species of it are endemic to the island.","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1945 Borneo was the site of horrific acts of brutality. The Japanese forced over 6,000 POWs and island civilians to march to a new camp some 160 miles away. This became known as the Sandakan Death March, as only 200 marchers survived to the end of the war.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many new species of animals and plants were discovered on Borneo between July 2005 and September 2006?","52"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Between the 1980s and 2006 Borneo lost approximately 45 % of its rain forests due to logging.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Borneo is the 3rd largest island in the world.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["From the 1600s to the 1800s, the British and Dutch were interested in Borneo because they wanted control of this resource.","Pepper"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the characteristics below is typical for the buildings on the Greek archipelago of Santorini?","The white-and-blue colouring"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the biggest Greek island ?","Crete"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Navagio Bay (also known as the Shipwreck) is the most popular beach of which Greek island?","Zakynthos"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Halkidiki, one of the Greek peninsulas, has a peculiar form which resembles what?","A trident"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which medieval monument is an essential part of the archaeological sites of the Greek island Rhodes?","The Palace of the Grand Master"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which island is NOT a part of Greece?","Gozo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Corinth Canal separates this Greek peninsula from the mainland of Greece.","Peloponnese"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which is the largest group of Greek islands?","The Cyclades"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cave of Melissani is among the most popular geological landmarks of which Greek island?","Kefallonia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following places in Greece is NOT an island?","Kavala"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Shinsengumi group remained loyal to the Tokugawa shogunate until the end of the Bakamatsu.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the leader of the first squad of Shinsengumi?","Okita Sōji"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At its peak, how many members did the Shinsengumi group have?","300+"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Shinsengumi rules, if the leader of a unit is mortally wounded in a fight, what should the rest of the group do?","All members of the unit must fight and die on the spot."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which city was the Shinsengumi group founded?","Kyoto"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Shinsengumi Commander from 1863 to 1868?","Kondō Isami"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The code of Shinsengumi comprised five rules. What was the punishment for breaking these rules?","Sepuku"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the favorite weapon of Harada Sanosuke, the 10th unit captain of the Shinsengumi?","Spear"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This river flows through the southern part of England and passes through the capital of the country.","The Thames"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What river is considered the longest river on the planet?","The Nile"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the holy river of the Hindu people?","The Ganges"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What river flows through the central part of the French capital, Paris?","Seine"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the longest river in Asia, and the third-longest in the world?","The Yangtze"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This river is the longest in the United States, and it gave its name to one of the states.","The Missouri River"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest river on the planet by volume?","The Amazon"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the river in which Jesus Christ was baptized by John the Baptist?","The Jordan"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This North American river is also called Kaniatarowanenneh, which means big waterway in Mohawk.","Saint Lawrence River"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This European river originates in Germany and empties in the Black Sea via a delta.","The Danube"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is a city in Oklahoma called Moon.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Oklahoma has no cities and communities named after Presidents.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Oklahoma city was the shopping cart invented?","Ardmore"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many of the astronauts who have flown in space between 1959 and 2009 were from Oklahoma?","6"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is a town in Oklahoma called IXL.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A windspeed of 100 feet above the ground was observed in 1999 in what Oklahoma city?","Moore"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Will Rogers World Airport and the Wiley Post Airport were named after people who died in 1935. How did they meet their demise?","in a plane crash"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Carl Albert High School was named after Carl Bert Albert, who was the Speaker of the House of Representatives from 1971 to 1977. What small Oklahoma town did he hail from?","Bugtussle"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Oklahoma has more man-made lakes than any other state.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT an Oklahoma city?","Toledo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Boise City, Oklahoma was the only city within the continental United States to be bombed during World War II.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of the Republic of Botswana is Pula. What does this mean in English?","Rain"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of what country is A Mari Usque Ad Mare, meaning From Sea to Sea in Latin?","Canada"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the national motto of India, Satyameva Jayate, mean in Sanskrit?","Truth Alone Triumphs"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of what country is Peace at Home, Peace in the World?","Turkey"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of this South American country is Libertad o muerte, Spanish for Liberty or Death.","Uruguay"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of the Republic of the Fiji Islands is Rerevaka na Kalou ka Doka na Tui. What does this mean?","Fear God and honor the Queen"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The slogan Sub Umbra Floreo, or Under the Shade I Flourish is the national motto of what Central American country?","Belize"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of what island country is Ever Conscious of God We Aspire, Build and Advance as One People?","Grenada"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The national motto of this Arabic country is God is the greatest.","Iraq"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the national motto of the Republic of Indonesia, Bhinneka Tunggal Ika?","Unity in Diversity"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is the Angel Falls, the highest waterfall on the planet, located?","Venezuela"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is a section of the famous Niagara Falls?","Horseshoe Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what U.S. state is the famous Bridalveil Fall located?","California"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the tallest waterfall made by humans, which is located in Umbria, Italy?","Cascata delle Marmore"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jog Falls is the highest plunge waterfall in this Asian country.","India"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the second-tallest waterfall on the planet?","Tugela Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what European country are the Rhine Falls located?","Switzerland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what U.S. state is the tallest waterfall in the country, Waihilau Falls, located?","Hawaii"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is Jurong Falls, the tallest artificial waterfall in the world, located?","Singapore"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the tallest waterfall in eastern North America?","Pissing Mare Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the old name of the country of Madagascar?","Malagasy Republic"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is Madagascar?","Off the Southeast Coast of Africa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the 2 main languages spoken in Madagascar?","French and Malagasy"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Madagascar is the worlds largest producer and exporter of what product?","Vanilla"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of the 10,000 plants native to Madagascar, what percent are found nowhere else in the world?","90%"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what island is the country of Madagascar located?","Madagascar Island"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT located in the country of Madagascar?","Bodrum"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I am a primate endemic to Madagascar. I have large, reflective eyes. I have a long tail. I have long toes, and opposable thumbs, useful for grasping tree branches. What am I?","A lemur"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Portuguese explorer was the first to sight the island of Madagascar?","Diego Dias"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first people to settle Madagascar came from Africa.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is New Guinea ranked in terms of size, among the islands of the world?","New Guinea is the second largest island in the world."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["New Guinea is an island north of Australia. It is divided into 2 roughly equal halves. What are they?","The western portion is part of Indonesia. The eastern portion is the country called Papua New Guinea."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["New Guinea is the most linguistically diverse area in the world. Approximately how many separate languages are spoken there?","1000"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The island of New Guinea was named after the country of Guinea. Which is Guinea located?","Africa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The country of Papua New Guinea gained its independence from this country in 1975.","Australia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The west half of the island of New Guinea is part of Indonesia, which comprises how many islands?","17,508"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Approximately what percentage of the population of the country of Papua New Guinea lives in rural areas?","86%"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the country of Papua New Guinea, how many children does the average woman give birth to during her lifetime according to 2006 estimates?","4.6"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital city of the country of Papua New Guinea?","Port Moresby"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The islands of the Pacific are collectively termed Oceania. Oceania is divided into several sub-groupings. In which of these is New Guinea located?","Melanesia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal translation of the title of the national anthem of Egypt, Bilady, Bilady, Bilady?","My country, my country, my country"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sea borders Egypt to the east?","Red Sea"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why was Egypt called Kemet, or black land, back in the ancient times?","Because of the black soils"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language spoken in Egypt?","Arabic"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Egyptian city is the largest city not only in Africa, but also in the whole Middle East?","Cairo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal is depicted on Egypts national emblem, which is featured on the national flag of Egypt, adopted in 1984?","Eagle"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was Omar Sharif, one of the most famous Egyptian actors, born?","Alexandria, Egypt"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sport is rated as the most popular sport among Egyptians?","Football (soccer)"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Egyptian territory is calculated to be roughly twice as large as the territory of this European country.","Spain"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What expression is commonly used in Egypt to refer to the annual flooding of the river Nile, the longest river in the world?","The Gift of the Nile"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Luxembourg is bordered by all of the following nations except this one.","Netherlands"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What languages are spoken in Luxembourg?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Luxembourg was not involved in any 20th century war.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following organizations is Luxembourg a member of?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Luxembourg has a population of approximately how many people?","one half million"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why is Luxembourg City one of the wealthiest cities in the world?","It is a banking and administrative center."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official name of Luxembourg?","Grand Duchy of Luxembourg"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does Luxembourg, which is a member of NATO, contribute to NATO?","by maintaining a small army"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the predominant religion in Luxembourg?","Roman Catholic"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The flag of Luxembourg consists of three vertical stripes of red, blue, green.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is Virginia Falls located?","Canada"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the tallest waterfall in Asia?","Hannoki Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Eas a Chual Aluinn is the highest waterfall in this country.","Great Britain"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the English name of the Mosi-oa-Tunya waterfall located between Zambia and Zimbabwe?","Victoria Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is Yumbilla Falls, the fifth-tallest waterfall on the planet, located?","Peru"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is the third-tallest waterfall on the planet, Ramnefjellsfossen, located?","Norway"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the name of the Iguazu Falls, located in South America, mean in English?","Big water"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is Gocta Waterfall located?","Peru"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the highest waterfall in North America?","James Bruce Falls"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which U.S. state is the Multnomah Falls located?","Oregon"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the largest volcano on Earth in terms of area?","Mauna Loa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Asian country is the Mount Unzen volcanic group located?","Japan"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The area around what Italian volcano is the most densely populated volcanic region in the world, making the volcano one of the most dangerous on the planet?","Mount Vesuvius"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Andean stratovolcano in Colombia erupted in 1993, killing 9 people.","Galeras"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Santorini volcanic islands are part of what European country?","Greece"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Russian volcano, located on the Kamchatka Peninsula, is one of the most active volcanoes on the planet.","Avachinsky"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the dangerous active volcano located in the Western Highlands of Guatemala?","Santa Maria"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which of the Philippine islands is the active Taal Volcano located?","Luzon"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which of the Canary Islands is the Mount Teide volcano located?","Tenerife"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This countrys national holidays include:","Cuba"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["None of these could be found in Europe before the Great Geographical Discoveries:","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the highest point in the state of Illinois?","Charles Mound"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Makawao is the capital of the State of Hawaii.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the 16th president of the United States?","Abraham Lincoln"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The city of Saint Louis, nicknamed Gateway to the West, is located in which state?","Missouri"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Malcolm X, the founder of the Organization of Afro-American Unity, was born in what US city?","Omaha"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["President George W. Bush was inaugurated on January 20, 2000.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital of Illinois, the 21st US State?","Springfield"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This city, located in Colorado, is the highest city in the United States.","Leadville"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Amelia Earhart, the first woman to fly solo across the Atlantic, was born in what city and state?","Atchison, Kansas"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Arrange the following oceans by their total area, starting with the largest:","2, 1, 3, 5, 4"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish the lyrics of the official state song of California, I Love You, California written by F. B. Silverwood:","It is home sweet home to me."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In geography, the term desert is used to refer to a region that receives little or no precipitation. Approximately one-third of Earths land surface is desert, with the largest such region being which of these?","Antarctica"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Kalahari Desert, meaning great thirst translated from the local language, is a vast area of red-brown sands, taking up a considerable area of which of these regions?","South Africa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This African desert, famous for its enormous sand dunes, is considered the oldest desert in the world, having endured its current arid conditions for at least 80 million years.","Namib Desert"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rangipo Desert in the central part of New Zealands North Island, does not have its barren and lifeless appearance because of the lack of rain, but rather, due to which of these?","Soil structure"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Atacama Desert of Chile and Peru is one of the driest and most lifeless places on Earth. This virtually rainless plateau is made up of sand, lava flows, and what other substance?","Salt"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Australian desert of nearly 600,000 square kilometres is famous for its spectacular land and rock formations, such as Uluru and Kata Tjuta, its estimated 1,100 parallel dunes running north-south, and the fresh water lake, Rainbow Valley.","Simpson Desert"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The largest natural karst crater on Earth - Ramon Crater, with a length of 40 km (25 miles) and width of 2 to 10 km (1.5 to 6 miles), is situated in the heart of this Middle East desert.","Negev desert"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Leonardo of Pisa or Leonardo Pisano, also known as Fibonacci, was an Italian mathematician and is best known for the discovery of the Fibonacci numbers, which form the following sequence.","8"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these countries is largest in area?","Japan"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following oceans is the worlds largest?","Pacific Ocean"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the United States Census Bureau in 2006, China was the most populated country in the world.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following countries is the worlds smallest continent, and can also be considered an island since it is surrounded by water?","Australia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Russia is the worlds largest country, with a land area of 17,098,242 square kilometers.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the worlds smallest independent state with a population in 2007 of approximately 821.","Vatican City"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pittsburgh is home to many universities and research facilities. One of them is described here:","Carnegie Mellon University"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which central European countrys all pre-1989 neighbors do not exist any more? The country is now bordered by 7 states.","Poland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The African kingdom of Dahomey was powerful in the XVIII century. Which modern day country did it cover?","Benin"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Holy Roman Empire of the German Nation was a loosely coupled union of mostly German speaking principalities. Which part of the union was the driver of the 19th century unification of Germany?","Prussia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the late medieval kingdom of Aragon situated?","Eastern Spain, major islands on the Mediterranean Sea and southern Italy"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Yugoslavia collapsed, one of its republics became an independent state known as FYROM. To which country does the acronym refer?","Macedonia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["By the end of the 16th century, a country called Commonwealth of Both Nations covered almost 1 million square kilometers of Europe. Which two countries formed it?","Poland and Lithuania"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Phoenicia was an ancient civilization that spread maritime trade over the Mediterranean Sea. From where did the Phoenicians originate?","Modern day Liban (Sidon, Tyre)"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Myanmar is a south-eastern Asian country. Under which name was it known before a military junta took over?","Burma"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Ottoman Empire used to rule over North Africa, the Middle East and south-eastern Europe. Which modern day country is the successor of the empire?","Turkey"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which independent country was not a Soviet republic?","Albania"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the monastic state of the Teutonic Knights located?","Northern Poland, southern Lithuania, part of Latvia and the Russian enclave of Kaliningrad"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where were the Boer Republics located?","Across South Africa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish this Irish saying: A tune is more lasting than the song of birds. And a word is more lasting than ________.","the wealth of the world"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the missing word in this Irish saying: Every dog is _____ at his own house door.?","bold"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete this Irish saying: The whole world cannot make a ________ out of a donkey.","race horse"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish the following Irish saying: However long the day it ends with _______.","night"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete this Irish saying: Dont let your ______ cut your throat.","tongue"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the missing word in this Irish saying: ______ is the poor mans doctor.?","Death"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete the following Irish saying: If you want ______, always carry the back tooth of a horse with you.","money"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish this Irish saying: If someone is sick turn his bed so that it faces _________.","north"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish this Irish saying: The far off hills are _______.","the greenest"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish this Irish saying: Often has the likely failed and the unlikely _________.","succeeded"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and largest city of Jamaica?","Kingston"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital city of India?","New Delhi"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tegucigalpa is the capital and largest city of this country.","Honduras"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and largest city of Romania?","Bucharest"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Addis Ababa is the capital of what country?","Ethiopia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and largest city of Lebanon?","Beirut"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kathmandu is the capital city of what country?","Nepal"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital city of Latvia?","Riga"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This city is the capital of the Kingdom of Morocco.","Rabat"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The capital city of what country is called Quito?","Ecuador"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name Zimbabwes capital which is an independent city equivalent to a province.","Harare"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name Moroccos capital that is also the capital of the Rabat-Salé-Zemmour-Zaer region.","Rabat"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bamako is the capital of Madagascar.","False"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and largest city of the Republic of the Congo?","Brazzaville"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ethiopias capital is Addis Ababa.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What port on the Atlantic Ocean is the capital and largest city of Guinea.","Conakry"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and largest commercial city of Libya?","Tripoli"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This city is Kenyas capital and the most populous city in East Africa.","Nairobi"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Victoria is the capital of the Republic of Seychelles.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Alaska used to be part of Russia.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the currency of Russia?","ruble"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How do you say hello in Russian?","Zdravstvuite"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What phrase means I love you in Russian?","Ya lyublyu tebya"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tetris, the popular falling-blocks video game, was invented in Russia.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the first President of the Russian Federation?","Boris Yeltsin"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first person in space was Russian.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who commissioned the St. Basils Cathedral?","Ivan the Terrible"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the capital city of the U.S. state of Wyoming.","Cheyenne"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The U.S. state of Oregon has been nicknamed after this animal, which is the official state animal.","Beaver"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state has been nicknamed The Silver State?","Nevada"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Albuquerque is the largest city of which U.S. state?","New Mexico"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the capital city of the U.S. state of Montana.","Helena"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the name of the U.S. state of Texas literally mean in Caddo?","Friends"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The state of Louisiana is bordered by the Gulf of Mexico on the south and three states. Which state does NOT border Louisiana?","Oklahoma"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When René-Robert Cavelier, Sieur de La Salle (Yikes!) claimed the territory he named it La Louisiane, which means....","Land of Louis or The Lousiana."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the closest definition of Santeria?","A Cuban based religion popular in Lousiana."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first recorded Euroregion, Gronau, was founded in 1958. What countries established it?","Germany and Netherlands"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Beskidy (Beskydy) Euroregion is located in the west part of the Carpathian mountain range. Which three countries does it span?","Czech Republic, Poland, Slovakia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which country is not a member of the Adriatic Euroregion?","Serbia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The ore and coal rich region of Silesia (pol.: Ślask, ger.: Schliesien, cz.: Slezsko) was ruled by Germans, Poles, Czechs and Austrians. To which country does it mostly belong today?","Poland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where would you find the Tornio River Valley Euroregion?","Sweden / Finland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cross Channel Euroregion includes France, the UK and what other country?","Belgium"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The region of Pomerania (ger.: Pomern, pol.: Pomorze) is located in north Germany and Poland. Which river divides the region into two parts?","Oder (Odra)"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The TriRhena Euroregion is spans these three countries crossed by the Rhine River.","France, Germany and Switzerland"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pyrenees-Mediterranean region is located along the border of which two countries?","France - Spain"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where would you find the Ore Mountains Euroregion?","Czech Republic and Germany"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state animal of Colorado and the symbol of Rocky Mountain National Park?","Big Horned Sheep"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was Isabella Bird the first woman to climb Longs Peak, the highest point in Rocky Mountain National Park?","No"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mesa Verde National Park in southern Colorado is best known for which of the following?","The best-preserved cliff dwellings in the U.S."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One the worlds largest silver nuggets was found in Colorado.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Colorado River, the major river of the American southwest, flows through which national landmark?","All of these"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Located at the Peterson Air Force base in Colorado, NORAD is a military organization that tracks aircraft, missiles and space vehicles. It also tracks what fictional character?","Santa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What U.S. interstate runs east and west through Colorado?","I-70"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Today people visit Colorado to go skiing, hiking, mountain biking and to enjoy the scenery. But 100 years ago, tourists more often went to the mountains to do what?","Soak in hot springs"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Early Colorado ranchers raised cattle, sheep, hogs, chickens, and turkeys, with the main focus on cattle.","True"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The huge grain industry in Colorado gives rise to breweries. Which of the following owns the biggest single site brewery located in Golden, Colorado?","Molson Coors Brewing Company"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On May 5, 1920 two Italian-Americans, Nicola Sacco and Bartolomeo Vanzetti, were arrested, tried, and executed for the April 15, 1920 murders of a South Braintree paymaster and security guard and theft of the payroll.","He was at the Italian consulate in Boston."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state motto of Colorado?","Nothing Without the Deity"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the word Colorado mean?","Colored Red"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state fish of Colorado?","Greenback Cutthroat Trout"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city in Colorado is known as the Richest Square Mile on Earth?","Central City, Colorado"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the popular slogan of the Colorado Gold Rush?","Pikes Peak or Bust"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Colorado become a state?","1876"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city boasts the most parks in the US?","Denver, Colorado"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What legendary American frontiersman commanded a major fort in Colorado?","Kit Carson"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Glenwood Springs, Colorado was known for its hot springs and hospital. What famous outlaw and gun slinger expired from Tuberculosis there?","Doc Holliday"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which continent is the famous active volcano Mount Nyiragongo located?","Africa"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which of the islands of Papua New Guinea is the active volcano Ulawun located?","New Britain"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Arabic name of Mount Etna, the second-largest active volcano in Europe, was Jebel Utlamat. What does this mean in English?","Mountain of Fire"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is the active volcano Sakurajima located?","Japan"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the most active volcano in Mexico, located mostly in the Mexican state of Jalisco?","Colima"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Indonesian name of the Mount Merapi volcano, Gunung Merapi, mean in English?","Mountain of Fire"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is the active volcano Koryaksky located?","Russia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what US state is the Fourpeaked Volcano, also known as Fourpeaked Mountain, situated?","Alaska"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the highest volcano in Asia, and the highest point in the Middle East?","Mount Damavand"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the active volcano situated in Skamania County, Washington, USA, 50 miles (80 km) northeast of Portland, Oregon?","Mount St. Helens"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The self-governed region of the Holy Mountain is considered part of the Greek state according to a decree","1913"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of government does Sweden have?","Constitutional monarchy"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these European countries shares a land border with Sweden?","Norway"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the colors of the national flag of Sweden?","Blue and yellow"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language spoken by the citizens of Sweden?","Swedish"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the largest city and capital of Sweden?","Stockholm"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Swedish name of Sweden is Sverige. What does this word literally mean?","Kingdom of the Swedes"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these celebrities is not Swedish?","Lars Ulrich"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of food is the popular Swedish dish called Surstromming?","Fish"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song is used as a de facto anthem of Sweden?","Thou Ancient, Thou Free"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the prevailing religion in Sweden?","Lutheranism"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital city of the Federative Republic of Brazil?","Brasilia"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the Portuguese word brasa from which the name of Brazil possibly originated?","Ember"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is wrong about the wildlife of Brazil?","Brazil is the country with the most endemic species in the world."],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the colors of the national flag of the Federative Republic of Brazil?","White, blue, green and yellow"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language of the Federative Republic of Brazil?","Portuguese"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the most popular sport among the people living in Brazil?","Football"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest and richest city in Brazil?","Sao Paulo"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the national motto of the Federative Republic of Brazil, also featured in the national flag of the country?","Order and Progress"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of food is the traditional Brazilian dish called Moqueca?","Stew"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what day of the week does the parade of the famous Rio Carnival traditionally start?","Sunday"],"tags_json":"[\"trivia\",\"geography\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
