{"kind":"deck","format":"deez.nut","version":2,"name":"Movies v9"}
{"kind":"note","note_type":"basic","fields":["What does Shrek use as a candle in the first Shrek movie?","His ear wax buildup"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the occupation of Doris, one of Cinderellas ugly stepsisters in the Shrek movies?","She is a bartender."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What part of his own body does Prince Charming from the Shrek movies adore the most?","His hair"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song by Madonna does Princess Fiona sing at the end of the first Shrek movie?","Like a Virgin"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What fake product is Rapunzel revealed to wear in the movie Shrek the Third?","Fake hair"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nightmare does Shrek have about his babies when he learns that he is going to be a father in the movie Shrek the Third?","A countless number of babies terrorizes him."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these nominees won the 1980 Golden Raspberry Award for Worst Actor?","Neil Diamond for The Jazz Singer"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Razzie Award for Worst Actor for 1981?","Klinton Spilsbury for The Legend of the Lone Ranger"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor received the Razzie Award for Worst Actor for 1982?","Laurence Olivier for Inchon"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Razzie Award for Worst Actor for 1983?","Christopher Atkins for A Night in Heaven"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Golden Raspberry Award for Worst Actor for 1984?","Sylvester Stallone for Rhinestone"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the winner of the Razzie Award for Worst Actor for 1985.","Sylvester Stallone for Rambo: First Blood Part II and Rocky IV"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the actor who was honored with the Golden Raspberry Award for Worst Actor for 1986.","Prince for Under the Cherry Moon"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor received the Razzie Award for Worst Actor for 1987?","Bill Cosby for Leonard Part 6"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The performance of this actor in a 1988 movie brought him the Golden Raspberry Award for Worst Actor.","Sylvester Stallone in Rambo III"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who received the Golden Raspberry Award for Worst Actor for 1989?","William Shatner for Star Trek V: The Final Frontier"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the nutty saber-toothed male squirrel from Ice Age: Dawn of the Dinosaurs?","Scrat"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the female saber-toothed squirrel that makes a debut appearance in Ice Age 3?","Scratte"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animal character does Ray Romano voice in the Ice Age 3 movie?","Mammoth"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the one-eyed weasel that makes a debut appearance in Ice Age: Dawn of the Dinosaurs?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of dinosaur is Mama Dino, who appears in the movie Ice Age: Dawn of the Dinosaurs?","Tyrannosaurus"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Manny and Ellies daughter that is born in Ice Age: Dawn of the Dinosaurs?","Peaches"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the actress who provides the voice of Ellie from Ice Age: Dawn of the Dinosaurs?","Queen Latifah"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Sid from Ice Age 3 gets jealous of Manny and Ellie, what does he adopt?","Three abandoned eggs"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these actors voices Diego, the saber-tooth tiger from Ice Age 3?","Denis Leary"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the dinosaur that is a mortal enemy of the one-eyed weasel in the 2009 movie Ice Age 3?","Rudy"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin was born in Chicago. Illinois in 1935. He became fascinated with movies after watching this film as a boy.","Citizen Kane"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin began his directorial career doing documentaries and live TV shows. He won several awards for this documentary about a death-row inmate.","The People vs. Paul Crump"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin moved to Hollywood in 1965. In 1967 he released his first feature, Good Times, starring this famous duo.","Sonny and Cher"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin directed several art films after Good Times, including the Golden Globe-nominated film version of this off-Broadway play written by Mart Crowley.","The Boys in the Band"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["1971s The French Connection was the first R-rated movie to win the Academy Award for Best Picture since the introduction of the MPAA film rating system.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin vehemently opposed the casting of Gene Hackman in The French Connection. Which of these actors were NOT considered to play Popeye Doyle?","Lee Marvin"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Warner Brothers approached many directors before signing William Friedkin to direct The Exorcist. Which of these directors was NOT approached?","John Schlesinger"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During filming of The Exorcist, William Friedkin employed many D.W. Griffith-esque manipulations to get desired performances. What did Friedkin do to Reverend William OMalley before the take of him reading last rites to Father Karras?","Slapped him in the face"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was The Exorcist released?","1973"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1977 William Friedkin released this remake of the 1953 French film Le Salaire de la Peur. Steve McQueen was the directors first choice for the film.","Sorcerer"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1978 William Friedkin directed The Brinks Job. The movie was based on the 1950 armed robbery of the Brinks Building in which almost $3 million was stolen. Where did the robbery take place?","Boston, MA"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1980 William Friedkin released Cruising, a controversial movie about a serial killer who targets gay men during the 1970s. What actor starred as Officer Steve Burns in this movie?","Al Pacino"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1983 William Friedkin released this movie that was presented as a latter-day Dr. Strangelove and was blasted by critics.","Deal of the Century"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1985 William Friedkin directed To Live and Die in L.A. It was based on the novel written by former Secret Service agent Gerald Petievich, who co-wrote the screenplay with Friedkin. Who plays master counterfeiter Rick Masters in this movie?","Willem Dafoe"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After fairly positive reviews and minor financial success with 1987s Rampage and 1990s The Guardian, in 1994 William Friedkin released this movie starring David Caruso, Linda Fiorentino, and Chazz Palminteri.","Jade"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2000 William Friedkin directed the movie Rules of Engagement, about a marine colonel who is brought to court-martial after he orders his troops to fire into a crowd in Yemen. Which two actors starred in this movie?","Samuel L. Jackson and Tommy Lee Jones"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Friedkin directed a 2007 episode of this TV drama in which he again worked with To Live and Die in L.A.s star William Petersen.","CSI: Crime Scene Investigation"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2007, William Friedkin directed Bug, a film based on the play by Tracy Letts. The Boston Heralds Stephen Schaefer called the movie One of the most disturbing horror movies imaginable. What actress starred in this movie?","Ashley Judd"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animal character is Don Lino, voiced by Robert De Niro in the 2004 comedy movie Shark Tale?","Shark"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular comedian and actor voiced the characters Ramon and Lovelace in the 2006 animated movie Happy Feet?","Robin Williams"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the character voiced by Michelle Pfeiffer in the 1998 Academy Award-winning animated movie The Prince of Egypt?","Tzipporah"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the 1998 animated movie in which Kevin Spacey voiced an evil grasshopper named Hopper?","A Bugs Life"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what popular animated movie did Matthew Broderick voice the character Simba the lion?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Academy Award-winning actress voiced the Queen Ant in the 2006 animated movie The Ant Bully?","Meryl Streep"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of animal character, named Master Shifu, did Dustin Hoffman voice in the 2008 animated movie Kung Fu Panda?","Red Panda"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Academy Award-winning actress voiced Grendels Mother in the 2007 performance capture movie Beowulf?","Angelina Jolie"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character did actor and director Mel Gibson voice in the 1995 animated movie Pocahontas?","John Smith"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of animated character, named Darlin, did Whoopi Goldberg voice in the 2006 animated movie Everyones Hero?","Baseball bat"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these handsome African American actors stars in the 2003 The Fighting Temptations movie?","Cuba Gooding, Jr."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these beautiful African American singers plays a leading role in the 2003 movie The Fighting Temptations?","Beyonce Knowles"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who did Lilly want to marry back when she was a little girl in the 2003 movie The Fighting Temptations?","Michael Jackson"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Aunt Sally leave to Paulina after her death in The Fighting Temptations 2003 movie?","A collection of church hats"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Bessie from The Fighting Temptations movie want to buy when she becomes rich and famous?","A Benz"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does Paulinas grandson describe Paulinas house to Darrin in the 2003 comedy The Fighting Temptations?","As a no-point-of-living-at-all house"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these songs does Lilly start singing to the inmates of the prison in the 2003 movie The Fighting Temptations?","Swing Low, Sweet Chariot"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these lovely singers plays Darrens mother in the 2003 comedy movie The Fighting Temptations?","Faith Evans"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of MaryAnns song in The Fighting Temptations 2003 movie which Paulina points out to the church members as improper and devils music","Do It To Me Again"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why is everybody teasing Mr. Johnson, one of the convicts in the 2003 comedy The Fighting Temptations?","Because of his very high voice."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What were Anthony, Skip and Jose delivering at the beginning of the movie Dead Presidents?","milk"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Skip say in the movie Dead Presidents when he was told his girlfriend was looking for him?","Im at where Im at, and I be where I be"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did Kirby put his fake leg after fighting Scooter in the movie Dead Presidents?","on the dashboard"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the film Dead Presidents, what was the last name of Anthonys girlfriend, Juanita?","Benson"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kelita Smith plays Delilah in the movie Dead Presidents.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What role did Terrance Howard play in the 1995 movie Dead Presidents?","Cowboy"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Dead Presidents, what part of his body did Jose lose while serving as a demolition expert in the war?","hand"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Cleon doing after the war in the movie Dead Presidents?","preaching"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Dead Presidents, Cutty was Kirbys nephew.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A record by what performer was playing right before Anthony got his revenge in the film Dead Presidents?","James Brown"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In P.T. Andersons There Will Be Blood, which one of the Sunday Family tells Daniel about the oil?","Paul"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does Daniel name the New Boston well after in the movie, There Will Be Blood?","Mary Sunday"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Three murders are committed in the Academy Award-winning film, There Will Be Blood.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Mary said to Britt at the beginning of the movie Another Cinderella Story?","No thank you, Britt. Your mom is going to kill me."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Tami call her orange car in the film Another Cinderella Story?","great pumpkin"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Selena Gomez, the star of Another Cinderella Story, also appeared in this TV show.","all of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who sings the song Tell Me Something I Don’t Know in the movie Another Cinderella Story?","Mary"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The second Another Cinderella Story music video starts with this character relaxing on a bus bench.","Joey"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the musical romantic comedy Another Cinderella Story released?","2008"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Camille Mitchell, Katharine Isabelle, and Jessica Parker Kennedy, who appeared in Another Cinderella Story, have also starred in this TV series.","Smallville"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character in the movie Another Cinderella Story is based on the stepmother from the classic Cinderella story?","Dominique"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song from the Another Cinderella Story is performed by Drew Seeley and Selena Gomez?","New Classic"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Eve of Destruction hit the screen?","1991"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What brand is the little red two-door car, that Eve uses to travel to northern California in the film Eve of Destruction.","Ford Mustang"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Eve of Destruction, after Eve broadsides the road rage driver on the winding road in northern California, what word comes across her creators beeper?","armed"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the film Eve of Destruction, this actor played the aging father of Eve, Bill Simmons, who was hunted down by the robot Eve because of the way he treated Eves mother.","Kevin McCarthy"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Eve of Destruction, Eves creator had a teenage fantasy that Eve attempted to fulfill in a bar and motel in California.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many law enforcement officers were killed at the motel in Northern California in the movie Eve of Destruction?","5"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Renee Soutendijk played Eve and her creator in the movie Eve of Destruction. In which country was Renee born?","The Netherlands"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who wrote the book on which the 2008 western Appaloosa is based?","Robert B. Parker"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year is the movie Appaloosa set?","1882"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the movie Appaloosa set?","New Mexico"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Finish this line delivered by Virgil Cole in the 2008 western Appaloosa: I enforce the law. Killing is sometimes a __________.","byproduct"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Virgil Cole, in the 2008 movie Appaloosa, who or what likes a dead buffalo?","Everything that eats meat"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Appallosa, when the widowed Allison French arrives in Appaloosa, Virgil and Everett help her get this job at the hotel.","Piano player"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What crime is Randall Bragg, played by Jeremy Irons in Appaloosa, accused of?","Murder"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Appaloosa Jeremy Irons plays Randall Bragg, who claims to have a connection with a U.S. President. Which president does he claim to know?","Chester A. Arthur"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the epic movie Appaloosa, Viggo Mortensen displays considerable horseback riding skills. In what movie did he previously co-star with a wild mustang?","Hidalgo"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what movie, featuring Viggo Mortenson, does Ed Harris co-star as the ruthless one-eyed Carl Fogarty?","A History of Violence"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who crucifies Jesus in the 2004 movie The Passion of the Christ?","Mel Gibson"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The line Behold Mother, I make all things new that Jesus speaks in the 2004 movie The Passion of the Christ is taken from what book of the New Testament?","Book of Revelation"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The daughter of what famous Italian singer and actor plays Satan in The Passion of the Christ?","Adriano Celentano"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of what nationality is the actor who plays Pontius Pilate in the 2004 movie The Passion of the Christ?","Bulgarian"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Italian actors plays King Herod Antipas in The Passion of the Christ?","Luca De Dominicis"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Mary Magdalenes reply to Marys question Why is this night different than other nights? in the movie The Passion Of The Christ?","Because once we were slaves and we are slaves no longer."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these scenes is unique for the 2004 movie The Passion Of The Christ, making it different from the traditional story of the Passion?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Mel Gibson, the director of The Passion Of The Christ, intend initially concerning the language of the movie?","He said he would use two old languages without subtitles."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What terrifying accident happened to the assistant director Jan Michelini, and later to actor James Caviezel, during the filming of the 2004 movie The Passion Of The Christ?","They were struck by lightning."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the initial blueprint version of the 2004 movie The Passion Of The Christ?","The Passion"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These 1990 movies were all nominated for the Razzie Award for Worst Picture. Which of them won?","The Adventures of Ford Fairlane"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What 1991 movie won the Golden Raspberry Award for Worst Picture?","Hudson Hawk"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Raspberry Award for Worst Picture for 1992 was given to this movie.","Shining Through"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This 1993 movie was honored with a Golden Raspberry Award for Worst Picture.","Indecent Proposal"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the winner of the 1994 Razzie Award for Worst Picture.","Color of Night"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This 1995 movie was the lucky winner of a Golden Raspberry Award for Worst Picture.","Showgirls"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What 1996 movie received the Golden Raspberry Award for Worst Picture?","Striptease"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these 1997 nominees won the Razzie Award for Worst Picture?","The Postman"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Golden Raspberry Award for Worst Picture for 1998 was given to this movie.","An Alan Smithee Film: Burn Hollywood Burn"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the lucky winner of the 1999 Golden Raspberry Award for Worst Picture.","Wild Wild West"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When was Over Her Dead Body released on DVD in the United States of America?","May 6th 2008"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these actors is not in the movie Over Her Dead Body?","Sarah Hills"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie, Over Her Dead Body, an ice sculpture of a lady falls and kills Kate.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the tagline for the movie Over Her Dead Body?","Just because shes passed on... Doesnt mean shes moving on...."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the psychic that Henry consults in the movie Over Her Dead Body?","Ashley"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who directed the film Over Her Dead Body?","Jeff Lowell"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is one of the film companies that produced the film Over Her Dead Body?","Gold Circle Films"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the movie Over Her Dead Body filmed?","Los Angeles"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Georgian town was the movie Facing the Giants filmed?","Albany"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Facing the Giants, Grant Taylors car battery dies every time on his way home from work.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the Richland Giants head coach in the film Facing the Giants?","Bobby Lee Duke"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that some football players fathers are lobbying to have Grant Taylor fired in Facing the Giants?","Yes"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Facing the Giants, according to Grant Taylors philosophy players need to praise God when they win and when they lose.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What head football coach makes a cameo in the movie Facing the Giants?","Mark Richt"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Facing the Giants, what player transferred to Shiloh after being kicked out of Westview High School?","Matt Prater"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happens to Grant Taylors wife in the movie Facing the Giants after Grant creates his new philosophy?","She gets pregnant."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The director, writer and star of the movie Facing the Giants is an associate pastor.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fill in the missing word in this quote from Bee Movie.","Jesus"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What singer and actress portrayed Gregs mother in the 2004 comedy movie Meet the Fockers?","Barbra Streisand"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What goes wrong at the airport when Greg and Pamela take the plane at the the beginning of the 2004 movie Meet the Fockers?","None of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Bernie and Roz Fockers little dog in the 2004 comedy movie Meet the Fockers?","Moses"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Jack suspect about Greg in the 2004 comedy movie Meet the Fockers?","That he has a son"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What revelation is made about Pamela, played by Teri Polo, in the 2004 move Meet the Fockers?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What offensive word does little Jack pick up from Greg in the 2004 comedy movie Meet the Fockers?","Asshole"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what actor are Greg and his supposed son Jorge compared in the 2004 movie Meet the Fockers?","Marlon Brando"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the wall created by Gregs father to celebrate his achievements in the 2004 movie Meet the Fockers?","Wall of Gaylord"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Bernard Fockers occupation before he became a father according to the 2004 comedy movie Meet the Fockers?","He was an attorney."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What fact about Gaylord does little Jack find very amusing in the 2004 comedy movie Meet the Fockers?","That he is a nurse"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The movie 2001 Maniacs begins with college friends Anderson Lee, Cory Jones and Nelson Elliot traveling south for Spring Break. Where were they heading?","Daytona Beach"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie 2001 maniacs, the teens take a detour that leads them to the town of Pleasant Valley, Georgia and are invited to stay for the towns celebration. What is the name of the celebration?","Guts and Glory Jubilee"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie 2001 Maniacs, at the BBQ, Anderson and the mayor fight. What happens when Anderson lifts the mayors eye patch?","Maggots falls from his eye socket."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Near the end of the movie 2001 Maniacs, Anderson and Joey jump on Malcolms motorcycle and speed off. They alert the police and find out what?","Pleasant Valley is a cemetery."],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played Cochise in Broken Arrow?","Jeff Chandler"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was Broken Arrow a black-and-white movie?","No"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these movies has monster producer Jerry Bruckheimer worked on, apart from the 2009 3-D action comedy G-Force?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fluffy leader of the G-Force secret agents team?","Darwin"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animals does the G-force team primarily consist of?","Guinea pigs"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What beautiful actress voices Juarez in G-Force?","Penelope Cruz"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie G-Force, what kind of animal is secret agent Mooch?","Fly"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A song by what famous rapper was featured in the soundtrack of the G-Force 2009 movie?","Flo Rida"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of character does actor Nicolas Cage voice in the 2009s G-Force?","Mole"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the special power of agent Juarez from the 3-D action comedy G-Force?","Martial arts"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What advice do the three mice from the pet shop in G-Force give to Blaster when a boy takes him from his cage?","Poop on his hand! Poop on his hand!"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What phrase is Blaster from the G-Force 2009 comedy movie famous for?","Im pretty sure this is animal cruelty... But I love it!"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of character does Beyonce play in the 2001 movie Carmen: A Hip Hopera?","Aspiring actress"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these artists appears in the Carmen: A Hip Hopera?","Bow Wow"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fancy Carmen: A Hip Hopera club where Carmen meets Blaze for the first time?","The Spot"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What artist plays a fortune teller in the movie Carmen: A Hip Hopera?","Wyclef Jean"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Carmen: A Hip Hopera , what do the tarot cards of the fortune teller read for Carmen?","Death"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What female rapper plays one of Carmens best friends in the movie Carmen: A Hip Hopera?","Rah Digga"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Mekhi Phifers character in the movie Carmen: A Hip Hopera?","Derek"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What scary thing happens to Carmen when she gets out of the bathtub in Carmen: A Hip Hopera?","A stereo falls into the bathtub"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who kills Carmen Brown in Carmen: A Hip Hopera?","Lieutenant Miller"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who plays the role of the narrator in the 2001 movie Carmen: A Hip Hopera?","Da Brat"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does WALL-E use to escape the cell in Diagnostics?","Laser beam"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who voices the main computer on the Axiom in the movie WALL-E?","Sigourney Weaver"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the first person WALL-E comes in contact with on the Axiom?","John"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the captain of the Axiom in the film WALL-E?","Captain B. McCrea"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What music is playing when the Captain stands for the first time in the movie WALL-E?","2001 A Space Odyssey"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie WALL-E, the Captain disables the Auto Pilot by ordering him to give him control.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the robot repairing on the outside of the ship in the movie WALL-E?","a light"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fictional planet that Anakin and Obi-Wan battle each other on?","Mustafar"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the viceroy for the Trade Federation in the Star wars saga?","Nute Gunray"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where do the Jedi and the Sith store their secrets?","holocron"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is Han Solos partner in smuggling in the Star Wars saga?","Chewbacca"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Star Wars saga, there is a Tusken Raider who is a Jedi master.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Star Wars character did the Kaminoans clone to make the clone army for the Republic?","Jango"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following films was not directed by Bernardo Bertolucci?","The Prestige"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The movie “The Last Emperor” follows Puyis life from his ascension to the throne as a small boy to his imprisonment and political rehabilitation.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What genre is Bernardo Betoluccis movie “The Conformist”?","Political drama"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which popular film directed by Bernardo Bertolucci portrays the life of an American widower?","Last Tango in Paris"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who plays Siddhartha in Bernardo Bertoluccis movie Little Buddha?","Keanu Reeves"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of these Bernardo Bertolucci films does Liv Tyler play a leading role?","Stealing Beauty"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bernardo Bertoluccis film La Luna focuses on the troubled life of a teenage boy.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What 2003 drama film directed by Bernardo Bertolucci is based on Gilbert Adairs novel The Holy Innocents?","The Dreamers"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which movie is Bernardo Bertoluccis directorial debut?","La commare secca (The Grim Reaper)"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this drama film by Bernardo Bertolucci, a couple journey to northern Africa to rekindle their marriage.","The Sheltering Sky"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the proud winner of the Razzie Award for Worst Actor for 1990.","Andrew Dice Clay for The Adventures of Ford Fairlane"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Razzie Award for Worst actor for 1991?","Kevin Costner for Robin Hood: Prince of Thieves"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actor was voted Worst Actor for 1992 at the Golden Raspberry Awards.","Sylvester Stallone in Stop! Or My Mom Will Shoot!"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Golden Raspberry Award for Worst Actor in 1994?","Burt Reynolds in Cop and a Half"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the lucky winner of the Golden Raspberry Award for Worst Actor for 1994.","Kevin Costner for Wyatt Earp"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the winner of the Golden Raspberry Award for Worst Actor for 1995.","Pauly Shore for Jury Duty"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who received the Golden Raspberry Award for Worst Actor for 1996?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Golden Raspberry Award for Worst Actor for his outstanding performance in a 1997 movie?","Kevin Costner in The Postman"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the lucky winner of the Razzie Award for Worst Actor for 1998?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actor received the Golden Raspberry Award for Worst Actor for his performance in a 1999 movie.","Adam Sandler for Big Daddy"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the host of the 72nd Academy Awards ceremony held on March 26, 2000?","Billy Crystal"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who won the Oscar for Best Actress in a Leading Role at the 72nd Academy Awards 2000?","Hilary Swank"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What outfits did the creators of the animated sitcom South Park, Trey Parker and Matt Stone, wear at the 72nd Academy Awards ceremony in 2000?","Evening dresses"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor took the award for Best Actor in a Leading Role at the 72nd Academy Awards 2000?","Kevin Spacey"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie was nominated in eight categories at the 72nd Academy Awards 2000?","American Beauty"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actress won the Oscar for Best Actress in a Supporting Role at the 72nd Academy Awards 2000?","Angelina Jolie"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who performed the the Oscar-nominated song Blame Canada, from the movie South Park: Bigger, Longer Uncut, at the 72nd Academy Awards ceremony in 2000?","Robin Williams"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor received the award for Best Actor in a Supporting Role at the 72nd Academy Awards 2000?","Michael Caine"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie won the awards for Best Sound, Best Editing, Best Sound Effects Editing and Best Visual Effects at the 72nd Academy Awards 2000?","The Matrix"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie won the Oscar for Best Picture at the 72nd Academy Awards 2000?","American Beauty"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song does the movie High School Musical 3 start out with?","Now or Never"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do Troy and Gabriella go to prom together in High School Musical 3?","No"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the play the students preform in High School Musical 3?","Senior Year"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Troy travel to see Gabriella in High School Musical 3?","by truck"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Scarlett Johansson make her film debut?","1994"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of the following movies did Scarlett Johansson appear?","All of these"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country was Scarlett Johansson born?","In the USA"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of these movies did Scarlett Johansson have a minor role in 1997?","Home Alone 3"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In early 2009, Scarlett Johansson was announced as the face of the new make-up collection by which of the following?","Dolce Gabbana"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scarlett Johansson released her first music album in 2008.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what movie did Scarlett Johansson play a character named Katherine Kay Lake?","The Black Dahlia"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What politician did Scarlett Johansson campaign for in the 2004 US presidential election?","John Kerry"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Scarlett Johansson marry Canadian actor Ryan Reynolds?","in 2008"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Woody Allen movie Vicky Cristina Barcelona, Scarlett Johanssons character is in Barcelona to complete her masters in Catalan identity.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Disney Channel movie Princess Protection Program premiered in the US on July 27, 2009.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who plays Rosie in the movie Princess Protection Program?","Demi Lovato"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who portrays Carter in the Disney movie Princess Protection Program?","Selena Gomez"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that in the movie Princess Protection Program Carter and Rosies high school is called Lake Monroe High School?","Yes"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney movie Princess Protection Program, Rosies first job was in a smoothie shop.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, is Carter a princess?","No"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What color dress was Rosie wearing when her crown was shot off her head in the movie Princess Protection Program?","yellow"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, Rosie comes from an island called Costa Luna.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What weapon was used to shoot the crown off Rosies head in the movie Princess Protection Program?","sword"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is trying to take over Costa Luna in the film Princess Protection Program?","General Kane"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, Carter has a crush on Donny.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Carter from Princess Protection Program work at the bait shop?","Yes"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, is Rosies dad in Costa Luna?","No"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Rosie, the protagonist of Princess Protection Program, leave her home country because someone attempted to assassinate her?","Yes"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the number of the bowling lane Rosie bowled in in the movie Princess Protection Program?","18"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, Rosie received a necklace from her mother.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the school bus driver in the movie Princess Protection Program?","Helen"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of words does Rosie never use in the movie Princess Protection Program?","contractions"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many languages does Rosie, the protagonist of Princess Protection Program, speak?","6"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, Rosie has to count worms.","True"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Rosie make a boat for Carter and her father in the movie Princess Protection Program?","No"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What size are Carters bowling shoes in the movie Princess Protection Program?","7/8"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Brooke and Megan are the names of the two mean girls in the movie Princess Protection Program.","False"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, Rosie poses as a regular girl from this state.","Iowa"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What color is Carters prom dress in the movie Princess Protection Program?","blue"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Princess Protection Program, is Brooke the first to find out Rosies secret?","Yes"],"tags_json":"[\"trivia\",\"movies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
