{"kind":"deck","format":"deez.nut","version":2,"name":"Television v11"}
{"kind":"note","note_type":"basic","fields":["In the teen series iCarly, is Carlys brother an artist?","Yes"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following bands appeared in an episode of the first season of iCarly?","Plain White Ts"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many chicks were in the iCarly episode in which Carly and Sam work on a science project?","6"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the series iCarly, Sam pays a lot attention to her boyfriend Jonah.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which three-time daytime Emmy award winning actor played the original Lucky Spencer from 1993-1999?","Jonathan Jackson"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rebecca Herbst, who plays the role of Elizabeth Webber on General Hospital, married another GH cast member. He has since left the show but his characters name was Juan Santiago. Which actor played him?","Michael Saucedo"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How is Jasper Jacks related to the madman James Craig who held the Metro Court hotel guests hostage for twelve hours?","His brother"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Actress Kimberly McCullough (Robin Scorpio) also played the role of Patty Hollawell on the TV show Charmed.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On General Hospital, who has lawyer Alexis Davis not been romantically involved with?","Jasper (Jax) Jacks"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 4 Musketeers, Elizabeth and Lucky Spencer, Emily Quartermaine and Nicholas Cassadine, often eat dinner together with ribs from what restaurant?","Elis"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Laura Spencer had two children.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sarah Brown originated the role of Caroline Benson (aka Carly Corinthos) on General Hospital.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the soap opera General Hospital, Elizabeth has two children, Cameron and Jake. Jake is named with his father Jasons initials (Jacob Martin, Jason Morgan). But who is Cameron named after?","His grandfather"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On Canaidan TV show, Degrassi: The Next Generation, what actress playes the role of Paige Michalchuk?","Lauren Collins"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Degrassi: The Next Generation character, played by actress Cassie Steele, was more or less Emma Nelsons sidekick in the first two seasons, but in season three debuted a new look and personality?","Manny"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The American broadcaster of Degrassi: The Next Generation, The-N, has repeatedly censored episodes, editing them in ways to make them, in their opinion, more acceptable to the American audience.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Degrassi: The Next Generation is the indirect result of Degrassi Junior High, which aired on CBC in Canada and PBS in the United States, in what year?","1987"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Christine Spike Nelson is a hairdresser and mother of Emma, with whom she was pregnant in the original series of Degrassi: The Next Generation.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Degrassi: The Next Generation characters does the following description best fit? The good-looking and quiet daughter of a widowed father, she has insecurities about her appearance, due to the fact that she is more curvaceous than her thin peers.","Terri MacGregor"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This alien had horrible laser and x-ray vision and super strength. He didnt need his UFO to fly. He was made of steel and often disguised himself as human. Who was this being from another planet?","Superman"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This half-human alien had pointed ears, green blood and could incapacitate his victims with a simple touch. He flew around in an unidentified flying object invading other planets throughout space, or the final frontier, (as his captain referred to it).","Mr. Spock"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This horribly disfigured creature from a galaxy far away used to look human before he took on his true alien form as cyborg (after a particularly bad beating from another alien). He rose to second in command of The Galactic Empire.","Darth Vader"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Alien could easily hide in a bowl of Jello Pudding, but if you ate that bowl you might be eating a considerable amount of human flesh!","The Blob"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The aliens from this movie forced a simple man to build a facsimile of the Devils Tower out of his mashed potatoes. What is the name of the movie where this horrible event takes place?","Close Encounters of the Third Kind"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first lesson on the Monty Python sketch How Not to Be Seen?","Not to stand up"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Monty Pythons Flying Circus debut on the BBC?","1969"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dennis Moore, the forgetful highwayman from Monty Pythons Flying Circus, carries a bag in which to put the loot. What is written on the side of this bag?","Swag"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This member of Python, who played King Arthur in Monty Python and the Holy Grail, was wont to play authority figures on the Monty Python show.","Graham Chapman"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To which political party does Monty Python character Jethro Q. Walrust*tty belong?","Silly"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Monty Python’s Flying Circus, what kind of animal is John Cleese attempting to return to Michael Palins pet shop?","A parrot"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous composer wrote the classic Liberty Bell March that is the theme song to the show Monty Python’s Flying Circus?","John Philip Sousa"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who attempts to have a debate with John Cleese in the sketch Argument Clinic?","Michael Palin"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character on That 70s Show is based on the adolescence of show creator Mark Brazill?","Eric"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Midge and Bob Pinciotti from the sitcom That 70s Show were born in the same year.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that in the pilot episode of That 70s Show, Red said he would love to drive a Toyota?","No"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The actress who played Midge on That 70s Show, also was on Charlies Angels.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was Teenage Wasteland the working title for That 70s Show?","Yes"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When the South Park episode, “Cartman Joins NAMBLA” was produced, what was the only problem Comedy Central had, content-wise, before airing?","The John Denver joke"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the South Park Season 3 DVD Mini-Commentaries, what is Danny DeVito’s favorite episode?","World Wide Recorder Concert"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first episode of South Park that allowed the usage of the word fag?","It Hits the Fan"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What world-famous line from South Park delivered by the character Cartman, was almost taken out of the show?","No, Kitty, this is MY potpie!"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What episode of South Park, aired 5 days after the premiere of Team America: World Police, was produced in less than 3 days?","Douche and Turd"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Hollywood director had two of his movies parodied in two South Park episodes in a row?","Zak Snyder"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these episodes of South Park has NOT been nominated for a Primetime Emmy?","Goobacks"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what two South Park episodes was the C word uttered uncensored?","Something You Can Do With Your Finger and Raisins"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these episodes of South Park has not been aired on Comedy Central since its original premiere?","Jared Has Aides"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these bands did NOT appear on the South Park music album, Chef Aid?","Styx"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What song was featured in the South Park episode “Mr. Hankey’s Christmas Classics,” but NOT featured on the album that followed it?","Jesus and Santas Duet"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What episode of South Park does NOT have any mention or references to Crab People?","Make Love, Not Warcraft"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What co-star of the film BASEketball supplies a voice in the two-part episodes of South Park, “Do the Handicapped Go to Hell?” and “Probably”?","Dian Bachar"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Season 6 of South Park, what destroys society?","Bebes boobs"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did the popular cartoon character Pluto make his debut?","1930"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first animated film in which Pluto appeared?","The Chain Gang"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Plutos first owner?","Minnie Mouse"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these voice actors did not voice Pluto?","Daws Butler"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these characters was not an enemy of Pluto?","Dinah the Dachshund"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Plutos son?","Pluto, Jr."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Plutos kid brother?","K.B."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these was a friend of Plutos?","Fifi the Pekingese"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which voice actor started voicing Pluto in 1990?","Bill Farmer"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Between 1952 and 1962, Pluto appeared in ten issues of the Four Color Comics series.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the very popular writer of screenplays who said, There is no reason to confuse television news with journalism.","Nora Ephron"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What TV personality said, People always assume that you cant be shy and be on television. Theyre wrong.?","Diane Sawyer"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who delivered these words: Television has brought murder back to the home where it belongs.?","Alfred Hitchcock"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is NOT a quote by the New Zealand writer /comic Tony Folliani?","Why do they call TV a medium? Because its rare when its well done."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This panelist on an early TV quiz show stated, Television is the triumph of machine over people.?","Fred Allen"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which quote is by the Australian-born wit Clive James?","Television is simultaneously blamed often by the same people, for worsening the world and for being powerless to change it."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Moral passion without entertainment is propaganda and propaganda without moral passion is television. Name the author who delivered these words.","Rita Mae Brown"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who made the statement, Television is chewing gum for the eyes.?","Frank Lloyd Wright"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who said, Television has done much for psychiatry, spreading information about it as well as the need for it.?","Alfred Hitchcock"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did The White Shadow run on TV?","1978-1981"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who starred as The White Shadow in the TV show of the same name?","Ken Howard"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the basketball coach in the TV series The White Shadow?","Coach Reeves"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was Carver High School located on the CBS show The White Shadow?","South Central Los Angeles, California"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the TV show The White Shadow, the Coach was cut from which NBA team?","Chicago Bulls"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the TV series The White Shadow, the Carver High Principal and the Coach attended the same college. Which one?","Boston College"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the starting center on the Carver High team in the series The White Shadow?","Warren Coolidge"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the pilot episode of The White Shadow, the Coach played Coolidge and Thorpe, two against one, and beat them.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the only member of the team on the show The White Shadow who recognized the Coach as a former NBA player?","Abner Goldstein"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played Mario Salami Petrinno in the TV series The White Shadow?","Tim Van Patten"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which cast member of The White Shadow directed Save the Last Dance and Coach Carter?","Thomas Carter"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which cast member of The White Shadow directed 16 episodes of The Sopranos and 4 episodes of Sex And the City?","Tim Van Patten"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The White Shadow is considered the first prime time show with a predominantly black cast.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The cast members of The White Shadow did their own singing in the shower scenes.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character from the White Shadow appeared on the show St. Elsewhere?","Coollidge"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Coach and Coolidge from The White Shadow did a TV commercial for which TV station?","ESPN"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement concerning the show The White Shadow is not correct?","Carver High won the Chicago High School Championship twice during the shows run."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the candy counter girl on the Disney show The Suite Life of Zack Cody?","Maddie"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The actors who play Zack and Cody on the popular self-titled show are brothers in real life.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the hotel manager on the show The Suite Life of Zack Cody?","Moseby"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the prison nickname of Lincoln Burrows, a character from the Prison Break TV series, portrayed by Dominic Purcell?","Linc the Sink"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Michael Scofield, a character in the TV series, Prison Break, who pretends to be a type I diabetic, needs what medicine to block the action of insulin?","Pugnac"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lincoln Burrows from Prison Break had to write the names of the observers of his execution. Whose name did he put in the application form?","None of these"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What number is the cell of Michael Scofield and his cellmate Sucre in the Fox TV series Prison Break?","40"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did Michael and his brother Lincoln from Prison Break meet, before they both got into the Prison Industries?","in the chapel"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the TV series Prison Break, while running away from violent prisoners who took over the infirmary, Sara wondered how Michael Scofield could be so familiar with the prison layout. What was his explanation?","He said that that one of the P.I. (Prison Industries) assignments was to clean the toxic mold in that part of the prison"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character from TV series Prison Break helped the group of escape-planning inmates by setting the guards break room on fire?","Westmoreland"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On Prison Break, C-Notes wife believes that the postcards she receives are from which country?","Iraq"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Prison Break TV series, when Sara visited Michael Scofields psychologist, she found out that Michael suffered from what?","Low-latent inhibition"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the man, who witnessed Filly Falzones crime in the Fox series Prison Break?","Fibonacci"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the relationship between look alikes, Tony and Andre DiMera?","Andre was Tonys cousin, plastic surgery made him Tonys twin."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What stopped Marlena from marrying Don Craig on their original wedding date?","Donna Temple called her at the church and threatens to commit suicide."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Knowing that Renee was Stefanos daughter, why did Andre kill Renee?","Andre was impersonating Tony and was afraid that Renee knew the truth."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the Dragons reason for his murder spree?","The victims were all members of the royal family in the way between him and the throne of England."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Select the correct age order of these characters (not based on current stories but on their actual appearance on the show).","Melissa, Janice, Hope then Jennifer"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the logic used by the Salem Strangler for choosing his victims?","He killed anyone he considered impure."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following actors/personalities did not appear on Days Of Our Lives?","Crystal Gayle"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Heres an easy one: Andrea Barber, best known for her role as Kimmy Gibler on Full House was introduced to the people of Salem as Roman Bradys long lost daughter Carrie, back from the dead.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Marlena was first introduced, what was everyone afraid Mickey would do to his new shrink?","Try to kill her, he was attacking blonde women."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many children did Mickey Horton father?","0"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Edward Mallory was the first and only Bill Horton.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Don Craig left Salem after a successful bid for the state senate?","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did the Newhart Show go off the air?","1978"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Bobs last name on The Newhart Show?","Hartley"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of doctor is Bob on The Newhart Show?","Psychologist"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor played the part of orthodontist Jerry Robinson who has an office on the same floor as Bob on The Newhart Show?","Peter Bonerz"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On The Newhart Show, Bill Daily played Bob and Emilys eccentric neighbor Howard Borden. On what other successful sitcom did he have a supporting role?","I Dream of Jeannie"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Howard Bordens profession on The Newhart Show?","Airline navigator"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played Bobs wife Emily on the 1970s sitcom The Newhart Show?","Suzanne Pleshette"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Marcia Wallce, who played Carol, Bobs receptionist on The Newhart Show, does the voice of what Simpsons character?","Edna Krabappel"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The actress who played Emily Hartley on The Newhart Show also appeared in the movie The Birds.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Suzanne Pleshettes third marriage was to a cast member on one of the Newhart Shows. What was his name?","Tom Poston"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There were three shows titled the Newhart Show from the 1960s to the 1990s.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what major city does the 1970s sitcom The Newhart Show take place?","Chicago"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many seasons did Xena: Warrior Princess grace the airwaves?","6"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Princess Dianas biggest fear when trying to pretend to be Xena in the series Xena: Warrior Princess?","She had never left the palace before."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following has not been used by various characters in Xena: Warrior Princess to describe the chakrum?","Disk of death"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of Joxer, Xena and Gabrielle, who did not die at least once during the series Xena: Warrior Princess?","They all died"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did the occult classic Dark Shadows premiere?","1966"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What network originally aired Dark Shadows?","ABC"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ghosts were introduced on the show Dark Shadows before the vampire.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played the part of Barnabus Collins in the series Dark Shadows.","Jonathan Frid"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dark Shadows is the only long running soap opera that is not on video for home viewing.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many feature films were spawned from the series Dark Shadows in the 1970s?","2"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Johnny Depp has stated that he was so obsessed with the series Dark Shadows that he wanted to be Barnabus Collins.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did Dark Shadows end its original run?","April 2, 1971"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the TV show Friends, Joeys middle name is Frank.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Friends episode TOW All the Cheesecakes, what kind of cake did Rachel tell Joey she was eating?","Tofu"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Has Friends character Rachel kissed all of her five friends?","Yes"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Ross and Monicas family newsletter on the TV show Friends?","The Geller Yeller"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ross had a date with a woman called Elizabeth Hornswaggle, a name that reminded Chandler of what childrens program?","Fraggle Rock"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is pizza the favorite food of fictional character Joey Tribbiani?","No"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the TV sitcom Friends, Rachels middle name is Karen.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Phoebes gay husband on Friends?","Duncan"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that on the TV show Friends, Janice has slept with Joey, Chandler and Ross?","No"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Monicas cats name on the TV show Friends?","Fluffy Meowington"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Peter Krause plays the part of David Fisher in the TV series Six Feet Under.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of the following characters did Ruth Fisher not date in the TV series Six Feet Under?","Rico"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the TV show Six Feet Under, the patriarch of the Fisher household, Nathaniel Samuel Fisher, was killed by a gunshot wound to the chest.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the TV series Six Feet Under, all of the following were Fisher siblings except for whom?","Lisa"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of drink was found in Lisas car after she went missing in Six Feet Under?","Dr. Pepper"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Claire from the HBO series Six Feet Under had an abortion.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character from Six Feet Under said this: Well, well. The prodigal returns. This is what youve been running away from your whole life, buddy boy. Scared the crap out of you when you were growing up, didnt it? And you thought youd escape, well guess what, nobody escapes.","Nathaniel Fisher"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Drew and Kate were romantically involved at one point in The Drew Carey Show, but did not get married for what reason?","Drew wanted children, but Kate did not."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Oswalds full name on The Drew Carey Show?","Oswald Lee Harvey"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is Drews pool table located on the sitcom The Drew Carey Show?","In his backyard."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who wrote Cleveland Rocks, one of the opening songs for the The Drew Carey Show?","Ian Hunter"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Drews brother Steve is a cross-dresser on The Drew Carey Show.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Drews full name on The Drew Carey Show?","Drew Allison Carey"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On The Drew Carey Show, Drew often wears a Ghoulardi T-shirt on the show. Who is Ghoulardi?","a late night horror show host"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What company did Lewis work for on The Drew Carey Show?","DrugCo."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this episode of Greys Anatomy, Alex meets Annie, a patient with an extraordinarily large tumor, and they become friendly. Annie trusts only Alex until she overhears him making fun of her. Derek chooses Meredith to help him with a grouchy Parkinsons patient. Bailey finds out about this and tries to make Merediths life hell.","If Tomorrow Never Comes"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tired, Meredith assists Burke with a heart transplant only to find out that her surgical glove ripped and she may have punctured the heart with her fingernail. Izzie throws a party at Merediths house for her new boyfriend so he can meet all her friends and then winds up missing the party because she gets stuck in surgery. This is the plot of which Greys Anatomy episode.","Shake Your Groove Thing"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this Greys Anatomy episode, Chief Webber calls a meeting with his staff about an outbreak of Syphillis at Seattle Grace. Izzie and Cristina wind up doing an unauthorized autopsy on a patient. Meredith and Derek get ready to go out on their first official date but are interrupted by an unexpected visitor: Dereks wife Addison.","Whos Zoomin Who"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this episode of the Greys Anatomy series, Meredith and the other interns report for their first day of work at Seattle Grace Hospital. Meredith finds out that her new boss, Derek Shepherd, is the man with whom she had a one night stand the previous night. Meredith and her fellow interns find out just how difficult life is for doctors, and what its like to work 48 hour shifts without any sleep.","A Hard Days Night"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Meredith and Derek are in charge of treating a patient who needs life-saving surgery, only to find out that her father is very religious and very against the surgery without a visit from their shaman. Meredith finds out about her mothers affair with Chief Webber. George and Alex get stuck in an elevator with a patient who needs immediate surgery, which George performs with directions from Dr. Burke. All this happened in which episode of Greys Anatomy.","Bring the Pain"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Meredith has a one night stand with a guy named Steve, who winds up a patient at Seattle Grace for a very disturbing problem...he has an erection that wont go away. An expectant mother of quintuplets finds out that most of her unborn children have potentially life-threatening problems. This is the plot of which Greys Anatomy episode?","Much Too Much"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this Greys Anatomy episode, Bonnie and Tom, two complete strangers, wind up as patients at Seattle Grace. They are both impaled to the same pole after an accident. Cristina is given the task of tracking down a patients missing leg. Alex begins to question his future as a doctor.","Into You Like a Train"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this episode of the Greys Anatomy series, Izzie meets Denny Duquette, a patient that is awaiting a heart transplant. George treats a teenage hermaphrodite named Bex.","Begin the Begin"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this Greys Anatomy episode, Meredith wakes up feeling like she is going to have a bad day. She turns out to be right when a patient arrives at the hospital with a bomb in his chest cavity, threatening the lives of the entire staff.","Its the End of the World"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Greys Anatomy episode has the following plot?","What Have I Done to Deserve This?"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this episode of Greys Anatomy, the nurses union at Seattle Grace goes on strike, as does George, leaving the doctors to fend for themselves. Meredith makes a critical mistake while treating a patient, which is witnessed by the patients friends. Izzie confides a big secret from her past to a young pregnant woman.","Break on Through"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cristina finds herself in charge of the ER. Time is running out for Denny. Derek comes to terms with the fact that a friends life is in his hands. This is part of the plot of which Greys Anatomy episode?","Deterioration of the Fight or Flight Response"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this episode of Greys Anatomy, Izzie interrogates George about his personal life. Addison takes Alex to task about a sensitive case. Burke has to deal with treating his musical hero.","Blues for Sister Someone"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Despite the hospitals code black, and assistance from the bomb squad, the dangerous situation at Seattle Grace escalates. Meredith works with the bomb squad to save the lives of everyone in the hospital. Derek must perform surgery under pressure of learning that Meredith is the girl with the bomb. This is part of the plot of what episode of the medical drama Greys Anatomy?","As We Know It"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many episodes of the Dark Shadows program were made?","1245"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["June Bennett starred on dark Shadows as Elizabeth Collins Stoddard from 1966-1970.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was the Dark Shadows Theme written by Robert Cobert?","Yes"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played Roger Collins on the Gothic soap opera Dark Shadows?","Louis Edmonds"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kathryn Leigh Scott played Maggie Evans on Dark Shadows.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did the series Lancelot Link, Secret Chimp appear on the TV air waves?","1970"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the TV series Lancelot Link, Secret Chimp, Lancelot worked for what agency?","A. P. E."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Lancelot Links partner in the monkey spy parody Lancelot Link ,Secret Chimp?","Mata Hairi"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does A. P. E. stand for in the TV series Lancelot Link, Secret Chimp?","Agency to Prevent Evil"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was in charge of A. P. E. in the TV series Lancelot Link, Secret Chimp?","Commander Darwin"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the real name of the chimpanzee that portrayed Lancelot Link in the TV series of the same name?","Tonga"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was in charge of C. H. U. M. P in the Lancelot Link, Secret Chimp series?","Baron Von Butcher"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does C. H. U. M. P. stand for on the TV series Lancelot Link, Secret Chimp?","Criminal Headquarters for Underworld Master Plan"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the groovy rock band that often appeared on the Lancelot Link, Secret Chimp TV series?","The Evolution Revolution"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Lancelot Link, Secret Chimp go off the air?","1972"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ricky Gervais and this man, created the British comedy series The Office.","Stephen Merchant"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these countries did not have a remake of the British show The Office?","Spain"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which Borough of Berkshire, England does the sitcom The Office take place?","Slough"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the assistant to the regional manager, played by Mackenzie Crook in the British show The Office?","Gareth Keenan"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Tim Canterburys co-worker and love interest in the British sitcom The Office?","Dawn"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the characters from the British series The Office has a birthday in the third episode The Quiz?","Tim Canterbury"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which actor plays the annoying boss David Brent in the British sitcom The Office?","Ricky Gervais"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the band, in which the character David Brent from the sitcom The Office performed?","Foregone Conclusion"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Office is the first British comedy to win this prestigious American award.","Golden Globe"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the theme song for the British sitcom The Office, originally performed by Chris Farlowe?","Handbags and Gladrags"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Marlenas first husband on the soap opera Days of our Lives?","Don Craig"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following Days of Our Lives characters gave into the charms of Liz Chandler and cheated on Marlena?","Don Craig"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the long-running sitcom Days of Our Lives, Don, Roman and John, have been married to Marlena, but they all had children with other women.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these men did Marlena cheat on on Days of Our Lives?","Roman Brady"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these men was Marlenas first love on the popular TV show Days of Our Lives?","Paul Whitman"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When TV characters Don Craig and Marlena Evans first met, she refused to go out with him because she thought he was in love with another woman.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Marlena first met Roman on days of Our Lives, she fell in love with him at first sight.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of Marlenas men couldnt tell the difference between Marlena and her twin sister, Samantha, and ended up sleeping with Sam.","False"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of Marlenas men, who is the first one that has been portrayed by more than one actor?","Roman Brady"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the TV show Days of Our Lives, John, Roman, Paul and Don have all professed undying love for Marlena.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which list depicts the targets for each season of HBOs The Wire in order?","Avon Barksdale, Frank Sobotka, Stringer Bell, Marlo Stansfield"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which cast member sings lead vocals on the theme song in season five of HBOs The Wire?","Steve Earle"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The theme song from Get a Life was a hit song from what musical group?","R.E.M."],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from the TV show Cashmere Mafia is a magazine publisher?","Mia Mason"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Caitlin Dowd, one of the main characters on Cashmere Mafia, is a confused lesbian/bisexual.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Juliet Drapers ex-husbands name in the TV series Cashmere Mafia?","Davis"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mia Mason, one of the protagonists on the Cashmere Mafia show, was engaged to this man for a week.","Jack Cutling"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the show Casmere Mafia, Mia was attracted to Eric and Zoes sexy manny? What was his name?","Adam"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city is the show Cashmere Mafia set in?","New York"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Caitlins girlfriends name on Cashmere Mafia?","Alicia Lawson"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many episodes were aired during the first season of Cashmere Mafia?","7"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What season of the Power Rangers series is titled Power Rangers: Time Force?","9th"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the colors of the Time Force Power Rangers?","Red, Blue, Green, Pink, Yellow"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Special Ranger in Power Rangers: Time Force.","Quantum"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these isnt a Time Force villain?","Fenix"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which two teams did the Time Force Rangers team up with?","Lightspeed Rescue and Wild Force"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Zord in Power Rangers: Time Force is operated through voice activation by the Quantum Ranger and is incapable of combining with other Zords?","The Quantasaurus-Rex"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete these lyrics from the theme song of Power Rangers: Time Force:","Fire and Thunder"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What century are the Time Force Rangers from?","31st"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are two Red Rangers in Power Rangers: Time Force.","True"],"tags_json":"[\"trivia\",\"television\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
