{"kind":"deck","format":"deez.nut","version":2,"name":"Religion & Faith v2"}
{"kind":"note","note_type":"basic","fields":["At Nazareth, this Biblical figure grew and waxed in spirit. His name means the anointed one.","Jesus Christ"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible, people are reconciled with God because of His Sons death at the cross in Mount Golgotha.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible, Jesus turned water to wine in this wedding feast that He had attended in Cana. Which of His miracles was this?","first miracle"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible, who should believers use as mediator between them and God when they pray?","Jesus Christ"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which epistle states that there is one mediator between God and men?","Timothy"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the King James Version of the Bible, what did God command people to do always, day and night?","praying"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Bible, are there any verses that strictly mention “trinity” as a term?","No"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What three things does the religious concept of the Trimurti represent?","Creator, Protector, and Destructor"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Biology divides cellular life forms into three basic life domains. What are they?","Archaea, Bacteria, and Eucaryota"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is Nona the goddess of death in the Roman myth of the triple spinning fate goddesses?","No"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In biology, is the Great Apes family a species trinity comprising of chimpanzees, gorillas, and orangutans?","No"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these three basic chemical compounds can turn the blue litmus into red?","Acid"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["St. Nicholas the Wonderworker is the patron saint of which of the following?","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["St. Nicholas is revered by both Orthodox and Catholic Christians.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Nicholas is one of the sources of the holiday figure of Santa Claus.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the historical Saint Nicholas born?","Asia Minor"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["St. Nicholas is believed to have made a pilgrimage to the Holy Land.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Nicholas was released from prison in 313, after this emperor issued the Edict of Milan, extending official tolerance to Christianity.","Constantine the Great"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Nicholas died on 6 December.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The splendid Basilica di San Nicola (Basilica of Saint Nicholas) is in Rome.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The historical Saint Nocholas was a Greek Bishop of what ancient town?","Myra"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to legend Saint Nicholas provided dowries to three young women who could not afford to marry.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Brigitta was a Swedish nun and founder of the Bridgettine Order.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nicknamed Black Angel, he was a prominent commander in the Chechen separatist movement against Russia.","Ruslan Gelayev"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["His name means King of Kings and he ruled the Malian Empire for over twenty years.","Mansa Musa"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What statement is true about Saint Godric of Finchale?","Both of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was an African-American Muslim minister and an advocate for the rights of African Americans.","Malcolm X"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["James, one of the Twelve Apostles of Jesus, was known by which of these names?","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Junichiro Koizumi is a politician who served as Prime Minister of Japan.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a Supreme Pontiff of the Roman Catholic Church and Sovereign of Vatican City from 1978 until his death in 2005.","Pope John Paul II"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Margery Kempe was an English religious mystic whose autobiography is one of the earliest in English literature.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Spanish knight founded the Society of Jesus in 1534.","Ignatius of Loyola"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He wrote the third Gospel and the Acts of the Apostles.","Luke the Evangelist"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a Christian saint from Egypt and a prominent leader among the Desert Fathers.","Anthony the Great"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What statement is true about Ignatius Loyola, a Spanish knight from a Basque noble family?","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["St Anicetus was the first Roman Bishop to forbid Montanism.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Leo IX launched a dispute regarding celibacy of the clergy.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mary Faustina Kowalska was a Russian nun and mystic, venerated by the Roman Catholic Church as a saint.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Christian tradition, this saint attached a silver hand to the icon of Theotokos, which has since then been known as Three-handed?","John of Damascus"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Vladimir the Great converted to Christianity and baptised all of Kievan Rus.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Stephen is often depicted with a crown for martyrdom.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Helena was Roman empress and the mother of Emperor Constantine the Great.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the earliest identified Christian house church?","Dura-Europos church"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Megiddo church, one of the oldest church buildings discovered by archaeologists, is located in Israel.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Coptic Orthodox monastery is located in an oasis in the Eastern Desert of Egypt.","St. Anthony Monastery"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement is true about Saint-Pierre-aux-Nonnains basilica in Metz, France?","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Church of Our Lady Mary of Zion is an Ethiopian Orthodox Church.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the oldest cathedral in Germany?","Cathedral of Trier"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Church of Saint Simeon Stylites is located in Syria.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these churches was designed by Isidore of Miletus and Anthemius of Tralles, who were professors of geometry at the University of Constantinople?","Hagia Sophia"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which monastery lies at the foot of Mount Sinai, where, according to the Hebrew Bible, Moses received the Ten Commandments from God?","Saint Catherine’s Monastery"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What church was built over the cave that tradition marks as the birthplace of Jesus of Nazareth?","Church of the Nativity, Bethlehem"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emanuel Swedenborg is a Dutch scientist, philosopher, mystic and theologian.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Emanuel Swedenborg claim?","all of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emanuel Swedenborg claimed that he could talk with angels, demons and other spirits.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What prominent Swedish author called Emanuel Swedenborg nothing but a fool?","Johan Henrik Kellgren"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1710, Emanuel Swedenborg made a grand tour through the Netherlands, France, and Germany.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emanuel Swedenborg lived in the 19th century.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emanuel Swedenborg supported the Christian doctrine of the Trinity.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is a work by Emanuel Swedenborg?","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happened in April 1745, when Emanuel Swedenborg was having dinner in a private room at a London tavern.","All of these"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many saints are recognized in Judaism ?","0"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first five books of the Old Testament are referred to as what?","The Torah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Judaism, who is considered to be the first Jew ?","Abraham"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why is the city of Hebron so important to Judaism ?","It is believed that Abraham, Sarah, Issac, Rebekkah, Leah and Jacob are buried there"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the context of Judaism, who was Abrahams wife ?","Sarah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many laws are in the first five books of the Old Testament?","613"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why will Jews not eat pork?","Pigs do not chew their cud and they do not have cloven hoofs"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Judaism, what do we call food that is permissible to be eaten?","Kosher"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Judaism, what work is permissible on Sunday?","Any work"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the word Rabbi mean?","My teacher"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The witch hunts started as a result of the superstitions of some Catholic Monks. This Dominican monk is considered to be the initiator of the witch hunts as he prepared a detailed manual of deviltry for the Church. It did not take long before women in Southern France were sent to the stake, condemned for cohabitation with the devil.","Thomas Aquinas"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first woman accused of witchcraft was burned around 1275. This was the reason for her condemnation.","Having intercourse with the devil"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Many of witchcraft confessions were extorted by means of torture, called ordeal. This method of torture was not used during the process of the ordeal.","The sound of trickling water"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Burning women who were supposedly witches was a common practice on the European continent. In England, however, they punished witches in this way.","Hanged them"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Most of the victims of the witch hunts were women. However, there were some men also burned, accused of being witches. This is why.","They tried to protect women accused of witchcraft"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As the witch hunts expanded, any woman could be tried as a witch, but in the beginning these were the most common victims of the Holy Inquisition.","Old, lonely women"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was a common conception that the number of people involved in the witchcraft activities could be boundless. For example, in 1609 the witch hunting French official Pierre de Lancre stated that all 30,000 dwellers of the French region Labourd were witches, including these people.","Priests"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The famous Salem Witch trial started with an incident in January, 1692. A Caribbean-born slave was accused of initiating the witch phenomenon. Twenty more people were killed as no one of them confessed to being a witch. What was the reason that triggered the Salem witch craze?","Eight little girls from the town got ill with strange symptoms such as convulsions, incomprehensible speech, and trance-like states"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This was a common torture method used in Scotland, which made the accused witch confess her deeds. The method caused hallucinations and made it easy for the inquisitors to extort confessions to flying, turning into animals, meeting the devil and taking part in witches’ Sabbaths.","Sleep deprivation"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Witch hunts still exist today. In 1981 a woman was killed by the mob, throwing stones at her as they believed she was a witch. This was the reason for stoning her to death.","Her sorcery incited the attack upon Pope John Paul II"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Old Testament, the prophet Hosea was instructed by God to marry a prostitute.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Psalm 119 is the longest psalm in the Bible. How many verses does it contain?","176"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Old Testament, Moses was 105 years old when he died.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is stated in the Old Testament that Jeremiah, Hosea, Jonah, and Job were prophets.","False"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to The Old Testament, the prophet Jonah was sent to which city to warn its inhabitants of the coming judgment on them?","Ninevah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The prophet Haggai is mentioned in the book of Ezra.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Book of Genesis, what did G-D create last, on the sixth day, as almost an afterthought?","Adam"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Abrahams first wife?","Sarah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Issacs wife according to Genesis?","Rebecca"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Judaism has three Patriarchs -Abraham, Issac, and Jacob. Who are the four Matriarchs?","Sarah, Rebecca, Leah, Rachel"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not one of Jacobs twelve sons?","Ephraim"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Jacobs only daughter according to Genesis?","Dina"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Book of Genesis contains the first Biblical reference to someone being put into prison. Who was put into prison?","Joseph"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the third son of Adam and Eve, sometimes described as the quiet one?","Seth"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Hebrew people lived in the first ghetto when they were in Egypt. Where was this place?","Goshen"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the genealogy of Jesus, who was the father of Jesse?","Obed"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of the following lands did Job live when he was first mentioned in the book of Job?","Uz"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was king of Judaea during the birth of Jesus?","King Herod"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible, how old was Joseph when he was put in charge of the whole land of Egypt, as Pharaoh had ordered.","30 years old"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible after Sarahs death, Abraham married another woman. What was her name?","Keturah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["From what tribe of Israel was Samson according to the Bible?","Dan"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Biblical character is Jacobs father-in-law as well as father of Rachel and Leah.","Laban"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which is the sixth book of the New Testament?","Romans"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Bible, when Naomi told her two daughters-in-law to leave her and go to their homes, which daughter-in-law decided to stay?","Ruth"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following did Jesus call first to be his disciple?","Simon"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of person may you call Judas?","A friend who betrayed you"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following events can be referred to as an Armageddon?","The last and completely destructive battle"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which use of Goliath is correct?","The local grocery successfully competed against the nearby Goliath supermaket"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How would you describe a Samaritan?","A person who helps people in need"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the salt of the earth?","Decent, reliable people"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who can be best described as doubting Thomas?","Someone who believes only what he sees"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following can be described as a prodigal son?","A young man who wastes his parents money on parties"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the sentence Ann was the apple of Marks eye tell us about the relation between those two?","Mark is deeply in love with Ann."],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What characteristic is commonly attributed to King Solomon?","Wisdom"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What message am I conveying, if I say I dont know him from Adam?","The person is completely unknown to me."],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the phrase of biblical proportions mean?","of a vast, enormous scale"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If John knows Mary in the biblical sense, what can we say about the pair?","They have had sex."],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Biblical character said the following?","Esther"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following words belong to this biblical figure:","Job"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Biblical hero delivered these words?","Samson"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Biblical character asked the following question?","Jesus"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from the Bible said the following? Get rid of that slave woman and her son, for that slave womans son will never share in the inheritance with my son Isaac.","Sarah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who said the following: It is not the healthy who need a doctor, but the sick. But go and learn what this means: I desire mercy, not sacrifice. For I have not come to call the righteous, but sinners.","Jesus"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Biblical figure said this?","Issac"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Biblical character who delivered these words: Pick me up and throw me into the sea, and it will become calm, I know that is is my fault that this great storm has come upon you.","Jonah"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from the Bible said this?","Martha"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who delivered these words: Suppose I go to the Israelites and say to them, The God of your fathers has sent me to you, and they ask me, ‘What is his name? Then what shall I tell them?","Moses"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the symbol of the dhamma (dharma)?","wheel"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Buddhist term refers to the cycle of reincarnation or rebirth?","Samsara"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the word buddha mean?","awake"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the path to happiness in Buddhism?","middle way"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Buddhism what are the3 evil roots/defilements that hide the truth from us?","delusion, hatred, greed"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Buddhism which of these beings inhabit Hells?","Naraka beings"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Buddhism, life is or leads to suffering in one way or another.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is generally accepted that the last words of the Buddha were: All component things are transient, work out your salvation with diligence.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kamma is only one of the 5 natural laws that Buddha spoke about.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Buddhism there are realms of existences other than human and animal realm.","True"],"tags_json":"[\"trivia\",\"religion-faith\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
