{"kind":"deck","format":"deez.nut","version":2,"name":"Hobbies v3"}
{"kind":"note","note_type":"basic","fields":["What type of rice is used for the preparation of the traditional Vietnamese dish Com tam?","Broken rice"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the main ingredient of the traditional Vietnamese dish Tiet canh?","Blood"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which part of the world are living animals traditionally and commonly eaten?","Far East"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does Islam treat the consumption of bat meat?","Bats are forbidden food."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The slaughter of what animal is forbidden in almost all states in India by law?","Cow"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Although there are Chinese, English, Polish, Spanish, Italian, and Turkish variations of this game, played on a board of black and red square spaces, its origins can be traced back to 1600 BC ancient Egypt.","Checkers"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This childrens pursuit board game, sold by toy and game manufacturer, Parker Brothers, is based on the ancient Indian game, Pachisi.","Sorry!"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the oldest games in recorded history, this strategy board game, where the moves are defined by the roll of two dice, is believed to have originated in ancient Mesopotamia. Excavations and literary references indicate that it was also popular in ancient Greece, Rome, Persia, and the Far East.","Backgammon"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This game was independently developed by two great mathematicians of the 20th century, John Nash and Piet Hein. The life and work of the former was the inspiration for the Academy Award winning film A Beautiful Mind. Name the game.","Hex"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This game, which requires complexity of strategy and a great deal of concentration, was initially created by ancient Chinese warlords and generals more than 2000 years ago to map out possible attacking positions.","Go"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Since 1977, there has been an annual world championship of this game, which requires a strategy of much planning and looking further ahead in your opponent’s possible moves. Goro Hasegawa popularized the game in Japan in 1975.","Othello"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The term for the conclusive position in one of the worlds most popular board games - chess, comes from the Persian phrase Shah Mat, which means what?","The king is dead."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Scrabble, a popular family board game created by architect Alfred Mosher Butts in 1938, words are formed on a 15x15 game board, with each letter giving the player different number of points (the rarer the letter, the more points it gives). How many points does the letter w award according to standard scrabble rules?","4"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This board game, first published by the Milton Bradley Company in 1931, derived from a guessing paper and pencil game, and has also a one-person puzzle version.","Battleship"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Monopoly, one of the best-selling commercial board games in the world named after the well-know economic term, the course of the game is determined mainly by which two of these factors?","Chance and decision-making"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happens if you play all of your letters during the game of Scrabble?","You get an extra 50 points"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To make this dish you would: leave your cheese outside covered with loose cheesecloth, allow flies to lay their eggs inside the cheese, the maggots will hatch and then spread it on toast. Enjoy!","Maggot-cheese"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Philippine blood stew is made by using the heart and blood of a pig.","Diniguan"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This speciality comes straight from the outbacks of Australia. It is the white larvae of the ghost moth that are often found in trunks and roots of trees.","Witchetty grubs"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is a special Eskimo dish. They gut this animal and stuff it with dead seagulls. Its left underground to mature for a while and then they would have a dinner feasts.","Gull-stuffed walrus"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In India, they consider this body fluid a sedative, especially if it comes from an animal like the ox. Some people who study yoga will use the human form of it.","Urine"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This was a common dish in England at the beginning of the century. It contains raisins, sugar, chestnuts, rice, and 3 quarts of pork blood.","Blood Pudding"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dish of fresh squid is eaten alive and raw, even at the moment of swallowing it.","Ika sashimi"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dish is prepared in Norway. Its name means cod soaked in plutonium. It is dried whitefish soaked in lye, a strong solution of sodium or potassium hydroxide.","Lutefisk"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the dictionarys meaning of this meal: stuffed derma; roasted fowl intestines with a seasoned filling of matzo meal and suet.","Kishke"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To eat this meal you would: wait for a fertilized egg until the 16th day of incubation, open it and swallow the fetus without removing anything from it except some feathers from your teeth.","Balut"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this board game moves are determined by dice rolls. Each player attempts to move around the board, from point to point, to get home.","Backgammon"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this card game, which is a predecessor to bridge, there is a trump suit, that can vary from hand to hand.","Whist"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the popular solitaire game, in which you alternate suits building down, and build up in the same suit on the aces?","Klondike"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this game, played with 2 decks, you can make melds. Red and black threes have special significance and some cards are wild.","Canasta"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is a betting game in which two cards are initially dealt. The player may ask for an additional card, hoping to reach the ideal score of nine.","Chemin de Fer"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of the following card games is the Queen of Spades to be avoided?","Hearts"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this board game, neither player can see the value of the other players men.","Stratego"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this game, you make melds of 3 or more cards. You can go out with 10 points or less. If your opponent undercuts you, you lose the difference in your points.","Gin Rummy"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This two-player board game is a race, but sometimes you can win by getting farther behind.","Backgammon"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This card game is played by four players one of which is a dummy.","Bridge"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This powerful tonic herb is recommended for supporting the long term energy of the body. It enhances the resistance against toxic stress reactions that cause exhaustion and improves physical and mental vitality. The plant is often used as a home remedy in Russia and China.","Siberian eleuthero"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is generally accepted that this drink, introduced in England by the Greek professor Servopoulos, acts as a stimulant. It invigorates the body, enhances the mental activity and fights drowsiness and fatigue.","Coffee"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This food, made by bees from the nectar of flowers, gives great energy to the body. This energy is used mainly for blood formation.","Honey"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The leaves of this plant have been chewed by people in the Andes for centuries. It has been used particularly in high mountainous regions, where oxygen is scarce, because the plant gives a boost of energy and acts as a stimulant.","Coca"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This plant, which is native to Venezuela and northern Brazil, is named after a tribe. It is used for producing drinks with energizing and stimulating effect.","Guarana"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The main components of this slow-growing perennial plant, often used as a general tonic, affect the physical and mental activity of the body, providing revitalising properties. The English word of the plant derives from a Chinese term meaning man root.","Ginseng"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Studies have shown that this plant, known as Camellia sinensis, contains a chemical that boosts bodily defense systems. It also contains small quantities of caffeine and tannins that mildly energise the body and mind.","Tea"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This nut, used in a number of cola drinks both for its aroma and refreshing qualities, contains caffeine, which explains its energizing effect.","Kola nut"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This deciduous tree, popular as Maidenhair Tree, was first used in China as a stimulant. It is generally accepted that it increases blood flow to the brain, stimulating memory, mental alertness and reducing mental fatigue.","Ginkgo"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These are people who do not eat anything that is derived from animals.","Vegans"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This religion encourages vegetarianism.","Buddhism"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is a widespread myth that vegetarians cannot provide this to their body, because it could only be supplied from meat. However, it is found in soy, beans, nuts, milk, cheese, eggs, etc.","Protein"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Vegetarian diet is rich in these agents, found mostly in fruits and vegetables. They are known to fight free radicals, thus slowing down the process of aging.","Antioxidants"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the reason why vegetarian diet is good for humans.","Anatomically, humans resemble herbivores"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This part of the worlds population is on a vegetarian diet.","1/4"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is how much the risk of breast cancer increases, if a woman eats meat daily, as opposed to once a week only.","3.8 times"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["High consumption of meat protein deprives the body of calcium. Lack of calcium causes this disease.","Osteoporosis"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The breast milk of a meat-eating mother can be this much more contaminated with pesticides, compared to the milk of a vegetarian mother.","35 times"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the vitamin that vegetarians should take, as it is not found in plants.","B 12"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The term roasting is often used interchangeably with this word.","Baking"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which term does not belong with the others?","Poaching"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why are foods basted?","To prevent them from drying out"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these cooking methods does not involve hot oil or fat?","Boiling"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The terms sweating and steaming refer to one and the same method of cooking.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these foods is generally poached in white wine?","Fish"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When you broil, where is the direct heat source?","Above the food"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Stir frying is a term used to describe two fast Chinese cooking techniques: chǎo and bào.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is no difference between blanching and parboiling.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many pleats are on a traditional Chefs hat (the Grand Toque)?","100"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The only ingredients in a basic mayonnaise are oil and a whole egg.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dessert was made in honor of a famous singer.","Peach Melba"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is regarded as the first internationally recognized celebrity chef?","Marie-Antoine Carême"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Julie Child, known to many as The French Chef, was not French.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Chef Jeff Smith of the Frugal Gourmet fame was removed from his TV show amid accusations of which of the following?","sexual harrasment"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Chef Wolfgang Puck is of German descent.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the measure for hotness of a chili pepper?","Scoville scale"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which ingredient for bread hurts the leavening (rising) ability?","salt"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of meat is used in Chateaubriand?","beef"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Origami is a hobby and an art of Chinese origin that uses solely what material for its creations?","Paper"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The city of Stoke-on-Trent, Staffordshire, England is known as the home of what popular craft and hobby?","Pottery"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of these hobbies is the hacky sack used?","Circle kicking"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the British Overseas Territory of Bermuda, kite flying is not just a hobby, but also an important part of which holiday?","Easter"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Letterboxing is usually what type of hobby?","Outdoor"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The American Philatelic Society is the U.S. organization of the fans of one of the worlds most popular hobbies. Which is it?","Stamp collecting"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Herpetoculture is a hobby related to keeping a collection of what kind of animals?","Reptiles"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The popular number placement puzzle Sudoku was invented in 1979 in which country?","USA"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the hobby of collecting matchboxes and different match-related items called?","Phillumeny"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This sign is positioned between the horse and the dragon. In ancient China it was associated with wisdom and aesthetic beauty.","Snake"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["2006 is the year of this sign, described as a noble and honest creature.","Dog"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Personalities of this sign are either leaders or rebels. Unless in a position of authority, males of this sign are outspoken critics of those above them.","Tiger"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is a sign of power, wealth and success.","Dragon"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is a Yin Sign associated with the Wood Element, that some people like as a pet. The sign before it can be fierce and the sign which follows it can fly.","Rabbit"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Yin Sign associated with the Fire Element. People born under that sign are genuinely nice people.","Goat"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The sign comes second. Its personality is descibed as steady and supportive..","Ox"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is the ninth Sign of the Chinese Zodiac. It is best described as this.","Active and Agile"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first Sign of the Chinese Zodiac. It is a Yang Sign commonly associated with the Water Element.","Rat"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is the 12th Sign of the Chinese Zodiac. It is a Yin Sign associated with the Water Element.","Pig"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The campaign for real ale, CAMRA, was founded in Ireland to revitalize British beer.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This nation brews and drinks the most varied and numerous collection of beers in the world varying from the popular pale lager to the esoteric appeal of lambic.","Belgium"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["By law German beer can only be made from these four ingredients:","Water, hops, malted barley, yeast"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This country has the most full sized breweries:","Germany"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This country leads the world in per capita beer consumption:","The Czech Republic"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The worlds largest brewer is based in:","Belgium"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Order a Budweiser in Britain and you will get a beer from:","the Czech Republic or the USA"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Michael Jackson---","wrote the book - The World of Beer."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This country consumes the most beer.","China"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the the following is not a step in the brewing of beer?","steeping"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following colors is not used in the card game Magic: The Gathering?","Orange"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is the most expensive card in the game Magic: The Gathering?","Black Lotus"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who created the collectible card game Magic: The Gathering?","Richard Garfield"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A player begins a game of Magic: The Gathering with 40 life points.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following spells in the card game Magic: The Gatheringcan destroy both creatures and enchantments?","Mortify"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following cards in the game Magic: the Gathering is from the Onslaught Block?","Visara, the Dreadful"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the card game Magic: The Gathering, if your opponent casts Rend Flesh at your Hand of Honor, which spell could you use to save your creature?","Ghostway"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following cards has a converted mana cost of 2 in the game Magic: The Gathering?","Disenchant"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not a Magic: The Gathering game format?","One Eyed Cyclops"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of alcohol is used for the preparation of the Bacardi cocktail?","Rum"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A wedge of what fruit is traditionally used as a garnish of the Cuba Libre cocktail?","Lime"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what time of the year is the Tom and Jerry cocktail served traditionally in the United States?","Christmas"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country did the Kamikaze cocktail reportedly originate?","Japan"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This cocktail was reportedly the first drink the American astronauts had when they returned to Earth in 1969.","Moonwalk"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular cocktail is made simply by mixing vodka and orange juice?","Screwdriver"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is often put on the glass rim when serving a Margarita cocktail?","Salt"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular herb is added to the Mojito cocktail for a refreshing flavor?","Mint"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The juice of what fruit is used for the preparation of the Cosmopolitan cocktail?","Cranberry"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of alcohol is used as a base to make the popular Manhattan cocktail?","Whiskey"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This plant can be used as a herbal medicine to treat gastric and intestinal problems, migraine, asthma, anemia, depression, anxiety and nervous ailments, among others.","Saint Johns Wort"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This well known plant derives its scientific name from Atropos, one of the Fates in Greek mythology, who held the shears to cut the thread of human life. The plant grows shiny black berries that are sweet to the taste but very toxic.","Deadly Nightshade"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This perennial herb from the mint family, that grows in wet soil, comes in two forms, a creeping variety and a more upright one.","Pennyroyal"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name this small tree also known as the Apalachin, whose leaves are used to prepare a strong infusion that contains large amounts of caffeine.","Yaupon"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This perennial herb was once used to make absinthe.","Wormwood"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This very unusual plant, seen quite frequently during the Yuletide season, is a parasite growing on the branches of trees and deriving its nourishment from them.","All of the these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This plant has a long and colorful history and its legal status varies from country to country.","Cannabis"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name this plant grown worldwide in parks, gardens, and greenhouses as an ornamental fixture with large colorful flowers also known as Wedding Bells and Heavenly Blue.","Morning Glory"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This plant grows wild in the dry, desert ground of Texas and Mexico and is one of the very few spineless varieties among some two thousand different types of cacti growing in the world.","Peyote"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cultivated on a huge scale for the brewery industry, this plant grows separate as male and female.","Hops"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which country was coffee first roasted and brewed?","Ethiopia"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the fruit of the coffee plant called?","Cherry"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After harvesting, coffee beans must be dried.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Green coffee beans stay acceptably fresh for how long?","Several years"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Once ground, how long does it take before coffee begins to stale?","Minutes"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Green coffee beans can be roasted on the stovetop in a frying pan.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Green coffee beans can be roasted at home in less than 30 minutes.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After roasting, one pound (0.5 kg) of green coffee beans yields how much dried coffee?","Slightly less than one pound / 0.5 kg"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Island coffees are some of the smoothest and most expensive in the world. Where do they come from?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The world’s most expensive coffee, Kopi Luwak, goes through a unique harvesting process. In Indonesian, “kopi” means coffee and “luwak” means what?","Civet"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is the clothing brand Lacoste originally from?","France"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the founder of the clothing brand Lacoste?","René Lacoste"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do Lacoste have shoes as part of their collections?","Yes"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aspiration is one of the Lacoste perfumes for women.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does the clothing brand Lacoste offer ophthalmic glasses as well as sunglasses?","Yes"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lacoste offers clothing for kids, men and women.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are no stores of the clothing brand Lacoste in Canada.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The name of the clothing brand Lacoste literally means the cost in French.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are Lacoste boutiques in Europe.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the general term used for the food that is forbidden by the Jewish dietary laws?","Treif"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The consumption of which of these mammals is forbidden by Jewish laws?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The consumption of what type of birds is forbidden by Jewish dietary laws?","Birds of prey"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of fish may be consumed according to Jewish dietary laws?","Fish with fins and scales"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What types of food should not be mixed, consumed or stored together according to Jewish dietary laws?","Meat and dairy products"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What part of any animal is absolutely forbidden for consumption by Jewish laws?","Blood"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The consumption of what type of insects is allowed by Jewish dietary laws?","Locust"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of food should be at least partly prepared by Jews to be considered suitable for consumption according to Jewish laws?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The consumption of what type of bread is forbidden on the holiday of Passover according to Jewish laws?","Leavened bread"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what way should an animal be slaughtered in order to be suitable for eating according to Jewish dietary laws?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rose hips, the fruit of the rose plant, are rich in what vitamin?","Vitamin C"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the correct term for the sharp protuberances growing out of the stem of the rose plant?","Prickles"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Rose Valley is located near the town of Kazanlak, in what major world producer of rose oil?","Bulgaria"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what continent is the rose species commonly known as Gallic Rose native?","Europe"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Belgian artist dedicated his life to painting roses and other flowers and plants?","Pierre-Joseph Redoute"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these countries has adopted the rose as its national flower?","England"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The red rose is a symbol of this political ideology.","Socialism"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city in the state of Oregon is known as The City of Roses?","Portland"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the common name for the rose species Rosa Chinensis?","China rose"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Popeyes opened their 1000th restaurant in New Orleans, LA.","False"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many calories does 1 piece of mild chicken breast, offered in Popeyes, have?","350 calories"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was the first Popeyes restaurant opened?","1972"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who sang the Popeyes trademark jingle Love that Chicken?","Dr. John"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who are the founders of Popeyes Chicken Biscuits?","Al Copeland and Jerome Pentsky"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Popeyes franchising began in 1976.","True"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Popeyes merge with KFC in 1989?","No"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many calories does one biscuit from Popeyes have?","240"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Popeyes go global?","1984"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many prestigious industry awards did Popeyes Chicken Biscuits win at their 30th anniversary?","2"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The precise number of people killed at Hiroshima by the atomic bomb is not known due to destruction of records, etc.","80,000"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The peach tree belongs to the Prunus genus which is indigenous to this country.","China"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Prunus genus, to which peaches belong, does not includes which one of these trees?","Apple"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Peach trees bloom in beautiful aromatic flowers in this season.","Early spring"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the usual color of the flowers of the peach tree?","Pink"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This American state produces about 65% of the peaches grown for commercial production in the U.S.A.","California"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Apart from China and the United States, which other country produces peaches on a large scale?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American president was known for having an orchard garden with peach trees at his Moticello estate?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nectarines are often mistakenly thought to be a crossbreed between peaches and these fruits.","Plums"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about storing peaches?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these methods is the best for planting a peach tree?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Black Diamond, Black Pearl and Nightfall are cultivars from this fruit.","Blackberry"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What other name is commonly used for the wolfberry?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Raspberries are especially high in this vitamin.","Vitamin C"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cranberries are known for preventing infections of this system in the human body.","Urinary system"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state is the largest producer of blueberries in the world?","Maine"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the usual color of the gooseberry fruit?","Green"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which U.S. state has the huckleberry for its state fruit?","Idaho"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The dewberry is closely related to this other berry fruit.","Blackberry"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of plant is the mulberry?","Tree"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of oil is used for the preparation of the bread variety called Tiger bread?","Sesame oil"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country did the Damper bread variety originate?","Australia"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How is the traditional Jamaican bread called Bammy prepared?","By frying"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of bread is the German bread variety called Dampfnudel?","White bread"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what major holiday is the sweet bread Tsoureki eaten in Greece?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Arab country did the Sangak bread variety originate?","Iran"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What makes the Vienna bread so light and airy?","Steam is used during baking."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country did the bread called Pane carasau originate?","Italy"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of flour is used for the preparation of the Thai bread Khanom bueang?","Rice flour"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Asian country was the Melonpan bread variety invented?","Japan"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What important health benefit does cooked sweet corn provide?","It is rich in antioxidants."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What essential vitamin is supplied through the consumption of carrots?","Vitamin A"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The regular consumption of cauliflower is proven to prevent this disease.","Cancer"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nutrient essential for the human body does spinach contain in large quantities?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Onions will not prove beneficial for treating which of the following conditions?","Stomach ulcer"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Eggplant, also known as aubergine, is a close relative of this other plant.","Tobacco"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why should the consumption of celery seeds and oil be avoided during pregnancy?","They may trigger uterine contractions."],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What important vitamin does asparagus contain?","Vitamin B9"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the treatment of what medical condition are radishes used in alternative medicine?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why would Romans and Egyptians eat some lettuce leaves after dinner?","To stimulate sleep"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of meat is used for the preparation of the traditional Spanish dish Cocido Madrileno?","All of these"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what holiday is the Spanish dessert called turron traditionally eaten?","Christmas"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of pasta is used for the making of the popular Spanish dish Fideua?","Vermicelli"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What vegetable is the main ingredient of the traditional Spanish soup Gazpacho?","Tomato"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what shape is the Spanish dessert Tortell traditionally prepared?","O-shape"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of food is the Spanish dish called Escalivada, which originated in Catalonia, Spain?","Salad"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is used to color the traditional Spanish dish Arroz negro, or paella negra, black?","Cephalopod ink"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of nuts is used for the preparation of the traditional Spanish pie Tarta de Santiago?","Almonds"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What vegetables are used for the preparation of the traditional Spanish stew Fabada Asturiana?","Beans"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of fish is traditionally used for the making of the Spanish stew called Marmitako?","Tuna"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why was the Angel food cake, also known as Angel Cake, called so?","Because it is very light"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of fat is used for the preparation of the popular Chiffon cake?","Butter"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country did the recipe for the Tiramisu cake originate?","Italy"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What fruits are added between the layers as well as on top of the Black Forest cake?","Cherries"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What vegetable is used for the preparation of the Passion Cake, which probably originated in the United Kingdom?","Carrot"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the other name for the sponge cake called Battenberg cake?","Window cake"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is added to the ingredients of the Devils food cake to raise the pH level of the batter and deepen its color?","Baking soda"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what country is the popular Spice cake believed to have originated?","the United States"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the famous Hungarian cake, called Dobos torte, topped with?","Caramel slices"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of cake is also known as the King of Cakes?","Baumkuchen"],"tags_json":"[\"trivia\",\"hobbies\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
