{"kind":"deck","format":"deez.nut","version":2,"name":"For Kids v2"}
{"kind":"note","note_type":"basic","fields":["What is the name of Luna Lovegoods father in the Harry Potter books?","Xenophilius"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Professor Snape is the Potions Master in Harry Potter and the Half-Blood Prince.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was Grindelwald defeated by Dumbledore in the Harry Potter series?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Harry Potter marries Hermione.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Voldemort have a rat named Nagini?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney movie, The Beauty and the Beast, all of the residents of the Beasts castle were mystical creatures.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emma Watson plays Hermione Granger in the Harry Potter film series.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What English actor portrays Harry Potters best friend, Ron Weasley?","Rupert Grint"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Gryffindor House ghost does John Cleese play in the Harry Potter film series?","Nearly Headless Nick"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What member of the Order of the Phoenix is portrayed by actor Robbie Coltrane?","Rubeus Hagrid"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the first actor who played Professor Dumbledore in the Harry Potter film series.","Richard Harris"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who portrays Draco Malfoy, one of the antagonists in the Harry Potter series?","Tom Felton"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What actor is not correctly paired with the character they played in the Harry Potter films?","Jason Isaacs - Lord Voldemort"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which potion in the Harry Potter series increases the luck of the drinker?","Felix Felicis"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This potion from the Harry Potter books induces a deep dreamless sleep in the drinker.","Sleeping Draught"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What potion in the Harry Potter series helps stop bleeding and heal wounds?","Essence of Dittany"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What potion relieves the symptoms of lycanthropy in the Harry Potter series?","Wolfsbane Potion"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This potion is described by J.K. Rowling as so powerful that three drops would have you spilling your innermost secrets for the entire class to hear.","Veritaserum"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Harry Potter books, this potion causes the drinker to become infatuated or obsessed with the one who gave it to them.","Love Potion"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This potion, mentioned in the Harry Potter books, allows the drinker to assume the appearance of another person.","Polyjuice Potion"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What potion is used to help treat colds in the Harry Potter books?","Pepperup Potion"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which potion, introduced in Harry Potter and the Philosophers Stone, lengthens the lifespan of the drinker as long as they keep drinking it?","Elixir of Life"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What potion from the Harry Potter books causes the drinker to become older?","Aging Potion"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Death Eater killed Fred Weasley in Harry Potter and the Deathly Hallows?","unknown by exact text"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fictional character Severus Snape was a Death Eater when he died.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Death Eater bit Lupin?","Fenrir Greyback"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fictional character Augustus Rookwood worked in the Department of Mysteries.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the answer to the riddle the sphinx gives to Harry Potter in the maze for the third task of of the Triwizard Tournament?","spider"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fourth champion of the fictional Triwizard Tournament?","Harry Potter"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the chapter in Harry Potter and the Goblet of Fire in which Cedric Diggory dies?","Flesh, Blood, and Bone"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Harry Potter fight a dementor in the maze in the third task of the Triwizard Tournament?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the dragon Viktor Krum has to fight for the first task of the Triwizard Tournament?","Chinese Fireball"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Harry Potter do to be able to breathe underwater for the second task of the Triwizard Tournament?","eats gillyweed"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is Harry Potter when he finds out what the second task of the Triwizard Tournament is about?","prefects bathroom"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Harry Potter wins 10,000 galleons for winning the Triwizard Tournament.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was the novel Anne of Green Gables published?","1908"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the location of the orphanage from which Anne was adopted in the book Anne of Green Gables?","Nova Scotia"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the relationship between Matthew and Marilla, the couple who adopted Anne in Lucy Montgomerys book?","Brother and Sister"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many books are there in the L. M. Montgomery Anne series?","8"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book Anne of Green Gables Anne gets herself into many predicaments. Which of the following is NOT one of them?","She mistook a bottle of currant wine for the raspberry cordial she was supposed to serve for tea and got drunk."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Canadian province do Marilla and Matthew Cuthbert live in the book Anne of Green Gables?","Prince Edward Island"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fictional town in which the story of Anne of Green Gables unfolds?","Avonlea"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is Annes surname in the book Anne of Green Gables?","Shirley"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Diana Barry is Annes best friend in the book Anne of Green Gables. How did Anne describe their friendship?","Bosom friends"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When was Anne of Green Gables - The Musical performed for the first time?","1964"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Early in the story of Anne of Green Gables, Marilla proudly presents Anne with three new dresses which she has made to replace the shabby, orphanage issued clothes but is very annoyed when it becomes obvious that Anne doesnt like them. Why doesnt Anne like them?","They dont have puffed sleeves."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the theater in which Anne of Green Gables - The Musical plays every summer?","The Confederation Center of the Arts"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Emmy Award-winning actress played Marilla in the 1985 television production of Anne of Green Gables, written and directed by Kevin Sullivan.","Colleen Dewhurst"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What adjective best describes the character of Mrs. Rachel Lynde from the book Anne of Green Gables?","All of these"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the end of the novel Anne of Green Gables, Matthew Cuthbert dies from complications related to pneumonia.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sam had $3.00, Bob had $9.50, Joe had $5.25, and Jim had $7.25. How much is all of their money together worth?","$25.00"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these numbers does not fit in the sequence: 2 4 6 7 9 12 11?","12"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do you get when you divide 123 by 10?","12.3"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are three digits in this number. The first digit (of the hundreds) is 8. Divide it by two, that is your second digit, divide the result again by two, that is your third digit. What is the number?","842"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do all of these numbers fit the sequence: 1, 2, 3, 5, 7, 9?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How much is 765 divided by 10?","76.5"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following numbers doesnt belong to the others: 3, 9, 15, 20?","20"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A person owned 8 dogs and as many cats. What is the total amount of pets owned by that somebody?","16"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first Horcrux found in Harry Potter and the Deathly Hallows?","The locket"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Harry Potter destroy Tom Riddles diary in the second book because he knew it was a Horcrux?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Ron and Hermione use to destroy Hufflepuffs cup?","Basilisk Fangs"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the Horcruxes in the Harry Potter books is Ravenclaws cup.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many Horcruxes did Tom Riddle make?","7"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Harry Potter series of books, any object can be a Horcrux.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If one of Voldemorts Horcruxes is destroyed, will he know?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nagini, one of Voldemorts Horcruxes, is a snake.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How old was Charlotte, the protagonist of The True Confessions of Charlotte Doyle, when she took the trip from England to her home on Rhode Island?","13"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the ship that Charlotte boarded in the book The True Confessions of Charlotte Doyle?","The Seahawk"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The True Confessions of Charlotte Doyle, the crew wanted to get revenge on the Captain.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Charlotte was the only female on the ship in the book The True Confessions of Charlotte Doyle.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The True Confessions of Charlotte Doyle, the men from the crew plan to kill Charlotte because she supported the Captain.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Zachariah, a character from the book The True Confessions of Charlotte Doyle, is brutally beaten to death by the Captain and Mr. Hollybrass.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does the Captain blame for the murder of Mr. Hollybrass in the book The True Confessions of Charlotte Doyle?","Charlotte"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the book The True Confessions of Charlotte Doyle, what is the penalty for murder of a ships First Mate?","hanging"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Captain in the book The True Confessions of Charlotte Doyle dies.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Sea Witch want from the Little Mermaid in exchange for the magic potion in Andersens fairy tale The Little Mermaid?","Her tongue/voice"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of a falling star according to the late grandmother in Andersens The Little Match Girl?","Someone is dying"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happens to the pea after the prince marries the princess in the fairy tale The Princess and the Pea?","They put it in the Royal Museum"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Elisa forbidden to do until she finishes knitting the eleven nettle shirts in Hans Christian Andersens fairy tale The Wild Swans?","Speak"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the word that Kai has to spell using pieces of ice in order to regain his freedom in Andersens fairy tale The Snow Queen?","Eternity"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What new name is Thumbelina given at the end of the fairy tale Thumbelina?","Maya"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animals mock the little duck in Hans Christian Andersens fairy tale The Ugly Duckling?","Cat and hen"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of people are unable to see the clothes of the emperor according to the frauds in the fairy tale The Emperors New Clothes?","Stupid people"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to The Steadfast Tin Soldier, what do the tin soldier and the paper ballerina have in common that makes the soldier fall in love?","They are both standing on one leg"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why does Death decide to spare the Chinese Emperors life in the fairy tale The Nightingale by Hans Christian Andersen?","He is moved by the song of the bird"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many people died in the fictional Battle of Hogwarts?","54"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many people are in the fictional student organisation known as Dumbledores Army?","28"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many siblings does Ron Weasley have?","6"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many people were selected for the Triwizard Tournament in Harry Potter and the Goblet of Fire?","4"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many O.W.L.s did Hermione Granger get in the Harry Potter books?","10"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many dementors attacked Harry and Hermione in the end of Book 3 of the Harry Potter series?","50"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many floors are in the fictional Hogwarts school?(excluding the dungeons)","7"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what day did Harry Potter discover the Mirror of Erised?","December 25th"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what floor of the fictional Hogwarts school do you find the Room of Requirement?","7th"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many people died in the book Harry Potter and the Sorcerers Stone?","3"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Harrys first line in the book Harry Potter and the Deathly Hallows?","What the?"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fictional character Rita Skeeter wrote a book titled Albus Dumbledore, His Life and Lies.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Was Albus Dumbledores sister named Areida?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does Hermione Granger fly with when leaving Privet Drive?","Kingsley Shacklebolt"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What spell does Hermione not approve of according to the book Harry Potter and the Deathly Hallows?","Muffliato"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Harry Potter and the Deathly Hallows, Ron leaves the group when they are in the forest of Dean.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character first discovered that the name Voldemort was cursed?","Ron"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is mentioned in Harry Potter and the Deathly Hallows that Bill had a real knack for guessing the passwords for the radio.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does Harry first use the Imperius curse on in Harry Potter and the Deathly Hallows?","A goblin"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Harry Potter books, Fleur Delacours middle name is Clemence.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the spell that multiplies objects in the Harry Potter books?","Gemino"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the chapter of Harry Potter and the Deadly Hallows, titled The Princes Tale, Lily states that these two boys idea of humor is, just evil.","Mulciber and Avery"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What characters screams at the end of Harry Potter and the Deadly Hallows on learning of Harrys apparent death.","McGonagall"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Voldemort tell Neville that he has spirit and bravery in the last book of the Harry Potter series?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sleeping Beauty was the last fairy tale produced by Walt Disney. When was it released?","January 29, 1959"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sleeping Beautys musical score and songs were inspired by Pyotr Ilyich Tchaikovskys Sleeping Beauty ballet.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney movie Sleeping Beauty, Princess Aurora is born to King Stefan and Queen Leah and they name her Aurora after what Roman goddess?","The goddess of the dawn"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the popular Disney animated film Maleficent curses baby Aurora: she will die when she pricks her finger on a spinning wheels spindle. Why does Maleficent arrive and curse the child?","She was not invited to the christening."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the gift of the third fairy in the Disney movie Sleeping Beauty?","She weakens the curse so Aurora will only fall into a deep sleep."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The three fairies in the animated film Sleeping Beauty decide to conceal Aurora in a cabin in the woods until her 16th birthday passes, but before the fairies take Aurora to the woods, what does the King do to stop the curse?","commands all spinning wheels be destroyed"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do the fairies rename Aurora in the Disney movie Sleeping Beauty?","Briar Rose"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the animated movie Sleeping Beauty, just prior to Auroras 16th birthday, Maleficent is furious that she and her evil henchmen still cannot find Aurora. What does Maleficent do?","She sends out her raven Diablo to find Aurora."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Sleeping Beauty, on Auroras 16th birthday, the fairies decide to make two presents, but their attempts fail and they use their wands, thus giving away their location. What two items were the fairies making for Aurora?","A cake and a gown"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney movie Sleeping Beauty, when Aurora returns to the cabin, the fairies tell her who she really is and take her to the castle to see her parents.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie Sleeping Beauty, back at home in the castle, Aurora finds a spinning wheel in the castles tower, pricks her finger on the spindle and falls into a deep sleep. Who finds Aurora?","The fairies"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney movie Sleeping Beauty, once Aurora falls into her deep sleep, the fairies freeze time until the spell is broken.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Disney film Sleeping Beauty, the fairies find out that Prince Phillip is the man Aurora loves and the only one who can break the spell, but Maleficents henchmen capture him and take him to Maleficents castle. What is the castle called?","The Forbidden Mountain"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the animated movie Sleeping Beauty, the fairies enter Maleficents castle and free the prince and give him these two magical objects.","A sword and a shield"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After Maleficent dies in the film Sleeping Beauty, Prince Phillip rushes to Aurora and removes the curse with a kiss. The two enter the palaces ballroom and see Auroras parents. Is this the first time Aurora has seen her parents since she was an infant?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the animated film Sleeping Beauty, Aurora and Prince Phillip dance a waltz and do not notice the fairies magically changing the color of Auroras ball gown. As the book closes, Auroras gown turns this color and remains this color.","Pink"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sleeping Beauty was re-released theatrically in 1970, 1971, 1986, 1993, 1995, and 2008. How much did it gross in theatres in the period 1959-2009, when adjusted for ticket price inflation?","$478.22 million"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why did actress Emma Watson, who plays Hermione in the Harry Potter series, keep her role in the sixth movie, Harry Potter and the Half-Blood Prince 2009, after initially deciding to quit?","She couldnt bear to see anyone else play Hermione."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did actor Jim Broadbent describe his character, Horace Slughorn, from the sixth Harry Potter movie, Harry Potter and the Half-Blood Prince 2009?","Comic character"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actress reportedly accepted the role of Narcissa Malfoy for the 2009 movie Harry Potter and the Half-Blood Prince, but her agent stated that the rumors were not true.","Naomi Watts"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who turns out to be the Half-Blood Prince in the sixth Harry Potter movie Harry Potter and the Half-Blood Prince?","Severus Snape"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the nickname of Sirius Black, whose younger brother Regulus Black appears in a photograph owned by Horace Slughorn in the movie Harry Potter and the Half-Blood Prince 2009?","Padfoot"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["With whom does Harry Potter form a relationship in the 2009 movie Harry Potter and the Half-Blood Prince?","Ginny Weasley"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the differences between the original plot of the book and the script of 2009 movie Harry Potter and the Half-Blood Prince?","Both the battle in the castle and Dumbledores funeral were not in the script."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular personality did actor Daniel Radcliffe portray in his debut movie?","David Copperfield"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of character did actor Rupert Grint from the 2009 Harry Potter and the Half-Blood Prince depict in a play based on the story of Noahs Ark when he was little?","A fish"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these cast members of the 2009 movie Harry Potter and the Half-Blood Prince was born in Paris, France?","Emma Watson"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of bird is the character from Oscar Wildes fairy tale The Happy Prince?","Swallow"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does the nightingale from Oscar Wildes story The Nightingale and the Rose find a red rose for the poor student?","It paints a white rose with its blood"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happens to the beautiful garden of the giant when he builds a wall to keep children off in Oscar Wildes fairy tale The Selfish Giant?","Eternal winter sets in the garden"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Hans from Oscar Wildes fairy tale The Devoted Friend do for a living?","Hes a gardener"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why does the rocket from Oscar Wildes story The Remarkable Rocket fail to ignite?","It gets wet"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why does the shepherd from Oscar Wildes fairy tale The Young King refuse to wear the royal raiment?","He has nightmares of where it came from"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the last line of the Infanta from Oscar Wildes story The Birthday of the Infanta?","For the future, let those who come to play with me have no hearts."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Soul want from the fisherman in Oscar Wildes fairy tale The Fisherman and his Soul?","His heart"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the mother of the Star-Child from Oscar Wildes fairy tale The Star-Child?","A beggar"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the beautiful Star-Child transformed into in Oscar Wildes fairy tale The Star-Child?","A cross between a snake and a toad"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Harry Potter, Voldemort, and Dumbledore have connected wands.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these fictional characters is the leader of the Death Eaters?","Voldemort"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first name of the animated 1980s hero Blackstar?","John"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Blackstar from the animated series of the same name get stranded in the alien world?","After falling in a black hole"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year were the Blackstar animated series first broadcast on American television?","1981"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Blackstar animates series, which of these was not a name of the little people known as the Trobbits?","Dargo"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many episodes of the animated series Blackstar ran on American television?","13"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Wind in the Willows was published in 1908 without much notice. What famous author and playwright, best known for Winnie the Pooh, adapted part of the book for the stage in 1929, thus making the book famous?","A. A. Milne"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the beginning of the book The Wind in the Willows, what is Mole doing when he gets angry and goes above ground to the river?","spring cleaning"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from The Wind in the Willows becomes easily obsessed with items, only to forget about them soon after acquiring them?","Mr. Toad"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Wind in the Willows was first published in 1908. What Scottish-born writer and author of the story The Reluctant Dragon wrote this book?","Kenneth Grahame"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from The Wind in the Willows gets lost in Wild Wood while looking for Badgers house?","Mole"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Wind in the Willows, Toad has crashed 6 cars, been put in the hospital for injuries 3 times, and has spent a great deal of money on fines. Toads friends decide to do this to save Toad since he has no sense when it comes to his obsessions.","Put him under house arrest"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Wind in the Willows, while Mr. Toad is in jail, this person becomes fond of him and helps him escape.","The jailers daughter"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In order to escape, Toad from The Wind in the Willows is dressed in disguise. What is he disguised as?","A washerwoman"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Wind in the Willows, shortly after his escape and still in disguise, Mr. Toad meets a bargewoman and tricks her into giving him a job. The bargewoman discovers Toads trick and throws him overboard. He steals her horse and sells it to a Gypsy for what?","Money and stew"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The Wind in the Willows, Mr. Toad tries to hitchhike back to the River Bank community. What is the significance of the car and driver that give Toad a ride?","It is the same car that Toad stole earlier"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After his jail escape, The Wind in the Willows character, Toad, learns from Ratty that Toad Hall has been taken over by these Wild Wood animals.","the weasels, stoats and ferrets"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1949 Disney released their animated versions of The Wind in the Willows and this short story.","The Legend of Sleepy Hollow"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1967 this British rock band released their first album. It was titled after Chapter 7 of The Wind in the Willows: The Piper at the Gates of Dawn.","Pink Floyd"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Based on Mr. Toads car driving in The Wind in the Willows, Mr. Toads Wild Ride was established in 1955. What is it?","a ride at Disneyland"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where does Peter live in the childrens novel Peter and the Shadow Thieves?","Mollusk Island"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Peter and the Shadow Thieves, what is the name of Fighting Prawns oldest daughter?","Shining Pearl"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Peter, the main character in Peter and the Shadow Thieves, wear shoes?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the mermaid that flirts with Peter in the book Peter and the Shadow Thieves?","Teacher"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who does Peter have to warn about Ombra in the childrens novel Peter and the Shadow Thieves?","Molly"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Peter and the Shadow Thieves, Slank is one of the Aster guards.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does Peter get to London in the book Peter and the Shadow Thieves?","He goes by boat."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book Peter and the Shadow Thieves, the starstuff was in what tower?","White Tower"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the childrens novel Peter and the Shadow Thieves, James and Thomas are the two fastest Lost boys.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which fairy is Peters guardian in the book Peter and the Shadow Thieves?","Tinker Bell"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Harry Potter and the Half-Blood Prince, when Harry is visiting Weasleys Wizard Wheezes, what is the last product mentioned before he followed Draco Malfoy into Knockturn Alley?","Pygmy Puff"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of tree does Harry Potter sit under after Dumbledores funeral?","Beech"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first time Harry Potter encounters a little girl outside the room of requirement, she drops a bottle of what?","Toadspawn"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Bellatrix Lestranges wand made of?","Walnut"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Zoeys last name on the TV show Zoey 101?","Brooks"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the sitcom Zoey 101, Zoeys brothers name is Todd.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Lola pretend to be a freaky goth chick on the show Zoey 101?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Has Chase had a crush on Zoey on the sitcom Zoey 101?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did the TV series Zoey 101 hit the airwaves?","2005"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the principal of the high school on Zoey 101?","Dean Rivers"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Zoeys high school on Zoey 101?","PCA"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Zoeys brainiac friend on the sitcom Zoey 101?","Quinn"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What happened to Nicole on the TV show Zoey 101?","She went to an all girls school."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Logan Ryan is the spoiled rich boy on Zoey 101.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Zoey 101 character has a lisp?","Stacey"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did Zoey start dating James when Chase went to England.","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Has Quinn dated Marc on the show Zoey 101?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did Zoey 101 end its original run?","2008"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jamie Lynn Spears plays Zoey on Zoey 101.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is there a host for the Arcade on Webkinz?","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of animal is the school superintendent on Webkinz?","cow"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On Webkinz, there is a host for the Tournament Area.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many tokens do you need to access the Wish Machine in Webkinz World?","10"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dr. Quacks Clinic is the doctors office in Webkinz world.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Webkinz World, What is the maximum amount of Kinzcash (from the tips can) that Arte will accept?","100"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the 150th to last word in Harry Potter and the Deathly Hallows?","Both"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Harry Potter and the Deathly Hallows, there is a chapter called The Bribe. What is the 138th word in this chapter?","They"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This word is the 367th word of Hermiones Secret in Harry Potter and the Prisoner of Azkaban.","By"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the 120th word in Grim Defeat, a chapter of Harry Potter and the Prisoner of Azkaban.","Send"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the 105th to last word in Diagon Alley, a chapter in Harry Potter and the Sorcerers/Philosophers Stone?","Great"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This word is the 224th word of the chapter, titled The Midnight Duel in Harry Potter and the Sorcerers/Philosophers Stone.","Everyone"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Harry Potter and the Chamber of Secrets has a chapter called The Chamber of Secrets. What is the 83rd to last word in this chapter?","Serpents"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Dueling Club, a chapter in Harry Potter and the Chamber of Secrets, what is the 251st to last word?","Tongue"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is word number 230 in the chapter Elf Tails in Harry Potter and the Half-Blood Prince.","Throat"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Whats the last line of the nursery rhyme Little Bo Peep:","Wagging their tails behind them"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fill in the missing words in the nursery rhyme Hush, Little Baby:","A diamond ring"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the following division problem, the quotient is 2:","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If your dog is licking him/herself, he/she is actually doing this.","Taking a bath"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kittens use the litter box as a place to what?","Use the bathroom in"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When dogs lick you, to them it is the same as kissing you.","No"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT true about an adverb?","modifies nouns"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the participle in the following sentence? Jane noticed her father walking along the shoreline.","walking"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following words can be used as an adjective?","lazy"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two words can be brought together as a compound word. They can be written together (one way), written as one word (hairstylist) or written with a hyphen (forty-two). Which of the following sentences is a correct usage of a hyphen?","Josh was driving down a one-way street."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The word effect is used as what part of speech in the following sentence? Will lack of sleep have an effect on your performance at work?","noun"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following sentences uses a comma incorrectly?","Preparing and submitting his report to the review board for evaluation and possible publication, was one of the most difficult tasks Bill had ever attempted."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what Disney film does the following exchange take place:","Beauty and the Beast"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Disney film is this dialogue from:","The Emperors New Groove"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did the animated series The Adventures of Jimmy Neutron: Boy Genius 1st air?","2002"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who are Jimmys best friends on the show The Adventures of Jimmy Neutron: Boy Genius?","Carl and Sheen"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are Libbys and Cindys last names on the animated show The Adventures of Jimmy Neutron: Boy Genius?","Folfax and Vortex"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what episode of The Adventures of Jimmy Neutron: Boy Genius are Jimmy and friends diagnosed with superpowers?","The N-Men"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On the animated show The Adventures of Jimmy Neutron: Boy Genius, who is Sheens favorite superhero?","UltraLord"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city do Jimmy and his friends live in on the show The Adventures of Jimmy Neutron: Boy Genius?","Retroville"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the series The Adventures of Jimmy Neutron: Boy Genius, Jimmy has a crush on Cindy.","True"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Jimmys dads name on The Adventures of Jimmy Neutron: Boy Genius?","Hugh"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Jimmys dads favorite food on The Adventures of Jimmy Neutron: Boy Genius?","pie"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the teacher of fictional character Jimmy Neutron?","Ms. Fowl"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does animated character Jimmy Neutron have a brother?","Yes"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is a rational fear according to the book the The Wide Window by Lemony Snicket?","Fear of monsters under your bed"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Austere Academy, when Carmelita Spats called the Baudelaires cakesniffers, Mr. Poe said that was very rude of her.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which book by Lemony Snicket does the phrase, It takes a village to raise a child, affect the Baudelaires?","The Vile Village"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which statement is true about some of the pages of the book The Ersatz Elevator?","They are just rectangles of black."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which book of A Series of Unfortunate Events are there two pages that are almost identical?","The Carnivorous Carnival"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Every book of A Series of Unfortunate Events is dedicated to Beatrice, followed by a short message. Which of the following sentences was never written on the dedication page?","To Beatrice, I always used to sleep late on weekends. Alas, now you do, also."],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Decode the name of this fruit:","Nectarine"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the Beatrice that writer Lemony Snicket always dedicates his books to?","Beatrice Baudelaire"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 13th book of A Series of Unfortunate Events ends with the Baudelaires doing what?","Sailing on a boat"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The final 13th book of A Series of Unfortunate Events has 13 chapters and ends with an About the author... section.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which set of characters from A Series of Unfortunate Events contains only people who lived through the entire series?","Klaus Baudelaire, Sunny Baudelaire, Duncan Quagmire"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Esme Squalors evilness was due to her boyfriend, Count Olaf.","False"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In A Series of Unfortunate Events, what type of game did Fionas brother invent?","Card game"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which three names can J.S. stand for in the books of A Series of Unfortunate Events?","Jaques Snicket, Jerome Squalor, Justice Strauss"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which book of A Series of Unfortunate Events did Klauss glasses break?","Book 4"],"tags_json":"[\"trivia\",\"for-kids\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
