{"kind":"deck","format":"deez.nut","version":2,"name":"World v10"}
{"kind":"note","note_type":"basic","fields":["In 1926, Singapore, Penang, and this settlement were combined to form the Straits Settlements.","Malacca"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How long did the fight for Singapore last during WWII?","6 days"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Singapore renamed to during the Japanese occupation (1942-1945)?","Syonan-to"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Singapore created a constitution on June 3, 1959 after achieving full internal self-government.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Singapores first prime minister?","Lee Kwan Yew"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How long did Lee Kwan Yew serve as prime minister of Singapore?","25 years"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1963, Singapore became part of Malaysia.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Taiwan is the largest island of what country","Republic of China"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the island on which the country known as Taiwan is situated?","Taiwan"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital and largest city of Taiwan?","Taipei"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language recognized by the government of Taiwan?","Mandarin Chinese"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What design is depicted on the national emblem of Taiwan?","Sun"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What religion has the largest number of followers among the population of Taiwan?","Buddhism"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these bird species is endemic to Taiwan?","All of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Grass jelly is a popular desert in Taiwan and other countries in Southeast Asia. What is it made from?","Herbs"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Taiwan?","None of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the color of the national flag of Taiwan?","Red"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The name Morocco originated from the Berber expression Mur-Akush,. What does it mean?","Land of God"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of governmental control has Morocco established?","Constitutional monarchy"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official language spoken in Morocco?","Arabic"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What design is depicted on the national flag of Morocco?","Star"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Morocco?","Hymn of the Sharif"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the most popular traditional drink in Morocco?","Green tea with mint"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the only two African countries that share borders with Morocco.","Algeria and Mauritania"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which water basin is the island of Ibiza located?","Mediterranean Sea"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ibiza belongs to the Balearic Islands, an autonomous community of which European country?","Spain"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ibiza is most well-known for which of the following?","Night life"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The island of Ibiza is unique in having which of the following?","The largest club in the world"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The monument called The Egg, located in Saint Antonio, Ibiza, was erected in honor of which great explorer?","Christopher Columbus"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The capital of the island country Ibiza is its largest city - Eiviss Cuidad (Ibiza City).","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following novels does not use the island of Ibiza as setting to its action?","They all do"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is named after the island of Ibiza?","A music genre"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following music formations had a resident of Ibiza among its members?","Engima"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ibizas name dates back to 654 BC when Phoenician settlers founded a port called Ibossim. What is the meaning of this name?","It is a dedication to a god of music and dance"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Ushiku Daibutsu, which depicts Amitabha Buddha, is located in this country.","Japan"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This statue, which was enshrined in 2005, is 108-metre (354 ft) tall.","Buddhist statue of Guanyin, Sanya, China"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A statue of two ancient emperors, named Huangdi and Yandi, is located in China.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is a memorial of the Great Patriotic War (1941-1945)?","Motherland, Kiev, Ukraine"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What statue was designed by Georgian designer Zurab Tsereteli to commemorate 300 years of the Russian Navy?","Peter the Great Statue in Moscow"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which colossal statue was given to the United States by France in 1886?","The Statue of Liberty"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Motherland Calls is a statue designed to commemorate the Soviet victory in the Eastern Front of World War II.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At the time of its construction this statue of Buddha was the tallest statue in the world.","Statue of Lanshan Buddha, Lanshan, China"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which monumental statues were destroyed by the Taliban in 2001 because they were considered “idols”.","The Buddhas of Bamyan, Afghanistan"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Christ the Redeemer is a statue located at the peak of the Corcovado mountain.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of food is the Pavlova, very popular in Australia and New Zealand?","Dessert"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cougnou Christmas bread is traditionally shaped like what?","Baby"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of fish is traditionally consumed smoked at Christmas in France?","Salmon"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of dessert is the Pandoro, very popular in Italy around Christmas and New Year?","Sweet bread"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What meat is traditionally consumed at Christmas in Mexico?","Turkey"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The dessert called bibingka is traditionally prepared during Christmas in what country?","Philippines"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The dish Pigs in a blanket, traditionally prepared for Christmas in the United Kingdom, is also known by what name?","All of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sea food is traditionally present on the Christmas table in Spain?","Shrimp"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What drink is very popular during Christmas in the United States?","Eggnog"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Christmas fruit cake stollen comes from what country?","Germany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nickname has been given to the US state of Virginia?","Mother of Presidents"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital city of the US state of Virginia?","Richmond"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state bird and symbol of the US state of Virginia?","Cardinal"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The official Latin motto of the US state of Virginia is Sic semper tyrannis. What does this mean in English?","Thus always to tyrants"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the color of the official state flag of the US state of Virginia, officially known as the Commonwealth of Virginia?","Blue"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state flower and one of the symbols of the US state of Virginia?","Dogwood"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the prevailing Christian denomination in the US state of Virginia?","Baptist"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous American actresses was born in the U.S. state of Virginia?","Sandra Bullock"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what month are the Virginia State Fair and the Neptune Festival held annually in the U.S. state of Virginia?","September"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is a soccer team from the U.S. state of Virginia?","Hampton Roads Piranhas"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital and the largest city of the U.S. state of Arizona?","Phoenix"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what sport are the Arizona Diamondbacks team competing?","Baseball"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The official state motto of the U.S. state of Arizona is Ditat Deus. What does this mean in English?","God enriches"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state mammal of the U.S. state of Arizona?","Ring-tailed cat"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nickname has been given to the U.S. state of Arizona?","The Copper State"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What design is depicted on the official state flag of the U.S. state of Arizona?","Star"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these celebrities was not born in the U.S. state of Arizona?","Steven Spielberg"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the name Arizona mean according to some historians?","Small spring"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state gemstone of the U.S. state of Arizona?","Turquoise"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Hollywood actor starred in the 1993 movie Arizona Dream, filmed in Douglas, Arizona?","Johnny Depp"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The word rhode in the name of the U.S. state of Rhode Island has which of the following meanings?","Red"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official state bird of the U.S. state of Rhode Island?","Chicken"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these nicknames refers to the U.S. state of Rhode Island?","None of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous Hollywood actresses grew up in the U.S. state of Rhode Island?","Debra Messing"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The U.S. state of Rhode Island became the first in North America to prohibit which of the following?","Slavery"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements about the U.S. state of Rhode Island is true?","None of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state flower of the U.S. state of Rhode Island?","Violet"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Dominican Republic is located on the island of Hispaniola.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous explorer reached the territory of the Dominican Republic in 1492?","Christopher Columbus"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the capital of the Dominican Republic?","Santo Domingo"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the motto of the Dominican Republic?","God, Homeland, Liberty"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the most popular sport in the Dominican Republic?","Baseball"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Christianity is the predominant religion in the The Dominican Republic.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did the Dominican Republic declare independence from Haiti?","1844"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the climate in the Dominican Republic?","Tropical"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When do the people of the Dominican republic celebrate New Year’s Day?","On January 1"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does the dog get the pigeons off the antenna at Lake Minnewahwahs mountain in the game Dogs Life?","He gets a bird feeder to get them down."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Independence Day a celebration of?","Declaration of Independence"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following famous persons was not born on July 4?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1996 a movie called Independence Day (starring Will Smith) was released. What was it about?","Attempted alien takeover of the Earth"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one was first to recognize Independence Day?","Massachusetts"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The American independence was recognized by Great Britain on September 3, 1783, by the Treaty of London.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following pairs is wrong? It is the representative who took part in writing the draft of the declaration and their state.","Roger Sherman - New York"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the most spectacular ways to celebrate July 4th is through colorful fireworks. Which of these types of fireworks is prohibited?","Cherry bombs"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Decorating a Christmas tree, perhaps the most popular tradition related to Christmas celebrations, originated in which country?","Germany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Joel Roberts Poinsett imported the popular decorative Christmas plants, poinsettias from this Central American country, where he worked as a US ambassador in the 19th century.","Mexico"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At Christmas, children usually put stockings or shoes by the fireplace, by the door or by the windowsill. In which country do children fill their shoes with hay and carrots for Santa’s horse?","Holland"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Carols are popular Christmas songs, performed on Christmas day. What was the original meaning of the word carol?","Round dance"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is generally considered that Santa Claus was a real person who lived in Myra in about 400 AD. In which present-day country is this place located?","Turkey"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The story of Rudolph the Red-Nosed Reindeer, that guides Santas sleigh, was written in what year?","1939"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Twelve Days of Christmas is the period from Christmas day to January 6. Which festival takes place on the last day of this period?","Epiphany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who accompanies Grandfather Frost, the Russian equivalent of Santa Claus?","Snow Maiden"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which traditional Christmas plant is sometimes called the vampire plant?","Mistletoe"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 27th Amendment, which deals with congressional pay raises, was adopted in this year.","1992"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Three of these Amendments have been adopted during the 1920s. Which is the odd one?","15th Amendment"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The following excerpt is taken from the 13th Amendment.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Nineteenth Amendment to the United States Constitution is known as this.","The Susan B. Anthony Amendment"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Twenty-second Amendment to the United States Constitution set this limit for the President of the United States.","Two-term limit"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Eleventh Amendment to the United States Constitution stated this.","States themselves did not enjoy sovereign immunity from suits made by citizens of other states."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the following pairs (Amendment - the year in which it was adopted) is wrong.","Third Amendment - 1792"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 12th Amendment deals with this.","Electoral College"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Up to the beginning of the 20th century, this number of Amendments were ratified.","15"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did congress approve the Declaration of Independence, making the 13 colonies a land of a sovereign nation?","1776"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One year after the Declaration was approved, the citizens of this city commemorated the event by setting off fireworks, ringing bells and firing their guns.","Philadelphia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Each year a Liberty Medal is given on July 4th to a prominent world leader in honor of Independence Day. Which award is the medal accompanied by?","$100, 000"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many towns in the USA have liberty in their names?","30"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Boston, July 4th replaced this major holiday, as the most celebrated.","March 5"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This prominent symbol associated with early American history and the battle for American independence summoned citizens for the reading of the Declaration of Independence on July 8, 1976.","The Liberty Bell"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was not a single signature appended to the Declaration of Independence until the 4th of July. Thomas McKean, one of the signers, did not sign the Declaration until this year.","1781"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the author of the Declaration of Independence?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In order to make the Declaration official, this President of the Continental Congress had to sign it.","John Hancock"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what day did American colonies actually declare their independent from Britain?","July 2"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The United States Marine Corps motto, Semper Fidelis means what in Latin?","Always Faithful"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous U.S. Army general said: If it werent for these crazy, foolhardy, vulgar, wild, gutsy, braggarts who joined the Marine Corps, we would not have a country, a free country. A free country that allows others to call us names. We have protected this country and died for you?","George Patton"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was the longest-serving Commandant of the Marine Corps, often referred to as the grand old man of the Marine Corps.","Archibald Henderson"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These are the most elite Special Operation Forces of the US navy. They have fought in major conflicts, including Operation Enduring Freedom - the military response to the terrorist attacks on September 11, 2001.","SEAL"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Special Operation Force of the US Army is officially referred to as the Combat Application Group. It was featured in Ridley Scot’s movie, ‘Black Hawk Down’.","Delta Force"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This specialized paramilitary police unit in the USA, created in the city of Delano, California, in the 1960s, is often called upon for dangerous operations.","SWAT"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This elite combat frogman force, formerly called Decima Flottiglia MAS, is part of the Italian special forces.","COMSUBIN"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This unit, formed in 1941, is part of the UK special forces. Its badge depicts a sword with an inscription: ‘Who dares wins’.","SAS"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Foreign Legion, founded in 1831, is an elite rapid deployment force which consists mainly of foreign volunteers. It is a military formation within the army of which country?","France"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The fictional character John Rambo, portrayed on the big screen by actor Sylvester Stallone, belongs to what US special forces?","Green Berets"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Australian special force deals with reconnaissance and counter-terrorism. It played a significant role in providing security during the Sydney Olympic Games in 2000.","SASR"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["GEK Cobra, founded in 1972 to protect Jewish immigrants from Palestinian terrorists, is the counter-terrorist unit of this country.","Austria"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The counter-terrorism unit, GSG-9, established on April 17, 1973 and considered to be among the best of such units in the world, is part of the federal police of which country?","Germany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["October is one of 7 months with 31 days.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Thanksgiving is celebrated on the second Monday of October in Canada.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following African countries gained its independence from the United Kingdom on October 1, 1960?","Nigeria"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On July 16, 1999, John F. Kennedy Jr. died in a plane crash together with what other members of his family?","His wife and her sister"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these members of rock band Lynyrd Skynyrd survived the plane crash in Mississippi on October 20, 1977?","Artimus Pyle"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 2001, RB singer and actress Aaliyah was killed in a plane crash right after take-off in which part of the world?","The Bahamas"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The mother of which popular American singer was killed in a plane crash in California on January 6, 1977?","Frank Sinatra"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did Yuri Gagarin, the first man in space, die in a plane crash on a training mission east of Moscow?","March, 1968"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How old was singer Otis Redding when he was killed in a plane crash into Lake Monona, Wisconsin, in 1967?","26"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which city was blues guitarist Stevie Ray Vaughan expected to arrive, when his helicopter crashed killing everyone on board in 1990?","Chicago"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This famous Norwegian explorer, the first man to reach the South Pole, died in a plane crash in the Barens Sea on June 18, 1928.","Roald Amundsen"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which musicians were killed in the crash on February 3, 1959, a day widely known as The Day The Music Died?","Buddy Holly, the Big Bopper, Ritchie Valens"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["American singer Patsy Cline died in a plane crash in Tennessee together with what other popular country singer?","Cowboy Copas"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which is the capital city of Scotland?","Edinburgh"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Shetland Islands, which belong to Scotland, were once Norwegian.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animal is the haggis?","It is not an animal"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did monarchs sit on the Stone of Scone in Scotland?","during a coronation ceremony"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Scottish island Fair Isle is famous for what?","colourful, patterned knitwear"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is rumoured that there are two monsters in Scotland.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is the village of Berwick in Scotland?","No"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are Berwick cockles?","sweets"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Broons are a fictional Scottish family.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was on the cover of the first issue of Rolling Stone magazine?","John Lennon"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dr. Hook and the Medicine Show finally got their name on the cover of the March 29, 1973 issue of Rolling Stone magazine.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The December 9, 2004 issue of Rolling Stone magazine was a special collectors issue titled The 500 Greatest Songs of All Time. This song, which was voted # 1, was written by a twenty-four-year old singer/songwriter whose voice spoke for many of his generation. Al Kooper played organ and Paul Butterfield played guitar. What was the song?","Like a Rolling Stone"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dumping in the context of trade law is observed when this takes place.","A manufacturer in one country exports a product to another country at an unfairly low price."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A small business is defined as business whose number of employees is under 1000.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["NAFTA includes three of these four countries. Which is the odd one?","Cuba"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Free Trade can refer to goods, services, labour and capital.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Protectionism is an economic policy of promoting domestic industries through debunking foreign goods.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Prices of goods rise when quantity diminishes.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Although St. Valentines Day was declared a Church holiday as early as 496, it was not until the 14th century, in medieval England and France, that it was associated with romantic love. What was believed to occur on February 14th, to cause this association?","Birds started pairing off."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Saint Valentine, a kind-hearted priest who according to legends lived in Rome during the third century AD, was sentenced to death, as he disobeyed the orders of which Roman emperor?","Claudius II"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cupid, one of the major symbols in St. Valentines Day celebrations, is a mythological character, son of which goddess?","Venus"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to ancient legends, the phrase Your Valentine, popular among lovers today, derived from St. Valentines expression of love for his sweetheart, shortly before he died. How did he express his love?","In a love note"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This female character, depicted by Shakespeare, delivers the following line in her insane speech: Tomorrow is Saint Valentines Day.","Ophelia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the symbolic language of flowers, a rose of purple color given to someone on St. Valentines Day, signifies what?","Love at first sight"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the United States, this holiday is the humorous and somewhat sarcastic alternative to St. Valentines Day, also celebrated on February 14, but by those without a significant other.","Singles Awareness Day"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The day of February 14, 1929 remained in history not with its romantic atmosphere, but with one of the most publicized murders in the United States. Which famous American gangster stood behind these murders?","Al Capone"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This holiday is the Chinese equivalent of the Western, Saint Valentines Day.","The Night of Sevens"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This little beauty had three deuces and a four speed and a 389. Ronnie and the Daytonas","Pontiac"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what song did Prince advise Baby Ure much 2 fast; U got to slow down.?","Little Red Corvette"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He passed me on Doheny then I began to swerve","XKE"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Everybody says that there is nobody meaner than this little old grandma from Pasadena.","Super Stock Dodge"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["She should have gone to the library like she told her old man but shes too busy makin the Indy 500 look like a Roman chariot race, now. Too bad cause Daddy got wise (you shouldnt have lied, you shouldnt have lied) and there isnt going to be anymore Fun, Fun, Fun. What make of car did Daddy take away?","T-Bird"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which US state hosts the school known as the CIA?","New York"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one is the second-oldest institution of higher education in the United States?","William and Mary"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Freud came to visit the USA, he lectured at this college.","Clark"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which college was eleventh to join the Big Ten Conference?","The Pennsylvania State University"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This college hosts the Institute for Advanced Study, one of the worlds leading centers for theoretical research and intellectual inquiry.","Princeton"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these institutions has the lowest reported level of alcohol drinking on campus ?","Brigham Young University"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was at an abandoned part of the athletic fields of this U.S. college, that the first nuclear reactor was developed by Enrico Fermi.","University of Chicago"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the only US state to have two Ivy League colleges.","New York"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which US state is Washington University located in?","Missouri"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the only school to win the NCAA basketball Championship and the NIT basketball tournaments in the same year.","City College of New York"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which two states have an Albany State University?","New York and Georgia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lucy Hobbs was the first female dentist in America. From which school did she get her degree?","The Ohio College of Dental Surgery"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Elizabeth Swallow was the first woman professional chemist in America. From what school did she get her B.S. degree?","MIT"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What English city was actually the Titanics home port?","Liverpool"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was a visual difference between the Titanic and its sister ship, the Olympic.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Titanic had one steam turbine engine and two conventional steam engines.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which funnel on the RMS Titanic was a dummy?","the fourth"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What were the Titanics wireless call letters?","MGY"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which first class passenger on the Titanic was a famous dress designer known as Lucile?","Lady Cosmo Duff Gordon"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the Titanics officers is rumored to have killed himself?","Murdoch"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the funnel color of the White Star shipping company?","black and buff"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the relationship between Thomas Andrews, Titanics chief designer and Lord Pirrie, chairman of Harland and Wolff, the shipyard that built Titanic?","nephew/uncle"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the three colors of the Jamaican flag?","Black, Yellow, and Green"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are 52 stars on the United States flag.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What three colors are on the flag of France?","Red, White and Blue"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are two stars on the Panama flag.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The flags of what two countries look almost the same?","Italy and Mexico"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pakistans flag has a star and what other symbol?","crescent moon"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The letter R was found in the middle of the old Rwanda flag.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is pictured in the middle of the Lebanon flag?","Tree"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the GTO first offered as an option package for a Pontiac vehicle?","1964"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the mid-late 60s Royal Pontiac (a car dealer in Royal Oaks, Michigan) offered a special tune-up package for the GTO 389 engine. What was the name of that performance package?","Bobcat"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did General Motors decide to drop the GTO as an option package and add it to their vehicle lineup as a separate model series?","1966"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did General Motors decide to drop GTO as a separate model and reinstate the GTO as an option package for the LeMans and LeMans sport coupes?","1972"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What nationality were the immigrants that brought versions of the Halloween tradition to North America during the 1840s?","Irish"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Gaelic festival of the dead from which Halloween originated.","Samhain"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Helloween, one of the pioneering power metal bands, was formed in this country.","Germany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is common lore that the Jack olantern originated from the tale of a drunkard known as Stingy Jack or Jack the Smith. Who did Jack manage to trap?","the Devil"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What fictional character, created by Charles M. Schulz, believes in the Great Pumpkin and says, There are three things I have learned never to discuss with people: religion, politics, and the Great Pumpkin.?","Linus van Pelt"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The night before Halloween, known as Devils Night, is an integral part of this 1994 action-thriller film, set in Detroit.","The Crow"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these characters that have become part of the imagery surrounding Halloween is not correctly matched with the author who depicted him?","All of them are correctly matched."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["An old Irish Halloween tradition was to serve a dish called ‘colcannon’ with prizes hidden in it. What are the main ingredients of this traditional Irish dish?","mashed potatoes and cabbage"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Halloween events is not correctly matched with the place where it is held?","Terror Behind the Walls - Madison, Wisconsin"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What English author wrote the novel Halloween Party in which a girl is drowned in an apple-bobbing tub?","Agatha Christie"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the US President when the Berlin Wall fell?","George Bush Sr."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the leader of the legendary Solidarność (Solidarity) labor union that led the efforts to end communist rule in Poland?","Lech Wałęsa"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the last leader of the Soviet Union?","Mikhail Gorbachev"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Chancellor united Germany in 1990?","Helmut Kohl"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Pope was the spiritual leader of the anti-communist opposition in one of the former Eastern block countries in 1980s?","John Paul II - because he was Polish and wanted to see his country free"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these events was first in the avalanche that swept away communist governments in Europe?","the peaceful establishment of non-communist government in Poland"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which former Soviet Republic was first to declare independence from the USSR?","Lithuania"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which term refers to the fall of communism in Czechoslovakia?","Velvet Revolution"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["All revolutions of the 1989 Autumn of Nations in Europe were rather peaceful. Which country was the only one to overthrow their communist regime violently?","Romania"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which countrys all three neighbors were dissolved between 1990 and 1993?","Poland"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After 1989, with the dissolution of the Soviet Union, Czechoslovakia and Yugoslavia, many new countries appeared on the map of Europe. Which is not one of them?","Hungary"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The final act of the fall of communism in Europe was the accession of many former Eastern block countries to NATO and the European Union. When did the EU admit 8 of those countries?","1 May 2004"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first documented Thanksgiving ceremony in what was to become the United States of America took place in 1565 when a group of European settlers landed at St. Augustine, Florida. What nationality were these settlers?","Spanish"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Pilgrims, who established Plymouth Colony in 1620, were fleeing religious persecution in England, which was ruled at that time by this king.","James I"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the Latin word ‘pelegrinus’ from which the word ‘pilgrim’ originates?","foreigner"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements regarding Thanksgiving was made by an American President?","All of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In his satirical book “The Devils Dictionary”, this American journalist and writer defined turkey as “a large bird whose flesh, when eaten on certain religious anniversaries has the peculiar property of attesting piety and gratitude”.","Ambrose Bierce"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Benjamin Franklin considered the turkey a much more respectable bird than the Bald Eagle. He expressed his disapproval with the choice of the Bald Eagle as the national emblem in a letter to whom?","his daughter"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What US President refused to issue Thanksgiving proclamations during his Presidency?","Thomas Jefferson"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Native American tribe is said to have celebrated with the colonists the 1621 harvest festival, known as the First Thanksgiving Day”?","Wampanoag"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Academy Award and Grammy Award-winning song expresses the Native American belief that the earth is a living entity and people are connected to everything in nature?","Colors of the Wind"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the USA, Black Friday, the day after Thanksgiving, is one of the busiest retail shopping days of the year. What neologism refers to the Monday immediately following Black Friday?","Cyber Monday"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these movies tells a story that takes place within a 12-month period beginning and ending at Thanksgiving?","Hannah and Her Sisters"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Thanksgiving poem is an example of which of the following?","acrostic"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The origins of Thanksgiving Day can be traced back to harvest festivals that have been celebrated since ancient times. What is the meaning of the Anglo-Saxon word from which the word ‘harvest’ is derived?","autumn"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What holiday observed in the US coincides with Thanksgiving Day in Canada?","Columbus Day"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Starting in 1970, what annual protest is held on Thanksgiving Day in the US?","The National Day of Mourning"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What poet, known as “The Woman in White”, wrote a Thanksgiving poem opening with these lines?","Emily Dickinson"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the movie “Scent of a Woman”, Lieutenant Colonel Frank Slade reveals to young Charlie, that his plan for the Thanksgiving holiday is: to stay in a first-class hotel, eat an agreeable meal, drink a nice glass of wine, visit his elder brother, make love to a terrific woman and then blow his brains out. Name the two actors who star in the movie.","Al Pacino and Chris ODonnell"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the dominant type of Native American living structure in the Eastern United States and Canada?","The wigwam"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Native American group often built homes that were 100 feet in length.","Iroquois"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Non-Native Americans refer to this group as Delaware.","Lenni-Lenape"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these groups is the most populous in the USA?","Navajo"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the 2003 US Census Bureau statistics, about how many Americans classify themselves as Native Americans?","2,786,652"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In order for a Native American group to be recognized, it must be submitted to extensive genealogical investigation.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these states has no recognized Native American tribes?","Virginia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Sitting Bulls original name?","Slow"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which native American tribe was lead by Sitting Bull?","Hunkpapa Sioux"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the college football and track coach of Native American Jim Thorpe, one of the great athletes in world history?","Pop Warner"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does this Southern Paiute word wiitokuchumpunkuruganiyugwivantumu mean?","They -who-are -going-to-sit-and-cut-up-a-black-female-Buffalo-with-knives"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How are nouns classified in Native American languages?","Animate and inanimate"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are petroglyphs?","Rock carvings made by the Anasazi"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the seat of government for the Navajo Nation?","Window Rock"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Article 1of the U.S. Constitution deal with?","Legislative Branch"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Article 2 of the U.S. Constitution deal with?","Executive Branch"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Article 3 of the U.S. Constitution deal with?","Judicial Branch"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Article deals with Ratification of the U.S. Constitution?","7"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which section of the Legislative Branch gives U.S. Congress its powers?","8"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Article 4 of the U.S. Constitution deals with Relations Among the States.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Amendment to the U.S. Constitution was ratified in 1992?","27"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These two Oxford students were members of Monty Python.","Michael Palin and Terry Jones"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar wrote The Wealth of Nations.","Adam Smith"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford graduate wrote Lord of the Flies.","William Golding"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford graduate wrote The Leviathan, a classic work on legitimate government and society.","Thomas Hobbes"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This English philosopher wrote Two Treatises on Government , a philosophical work that had a great influence on the writers of the US Declaration of Independence and the US Constitution.","John Locke"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This neurologist was an Oxford grad who became famous for his athletic ability.","Roger Bannister"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar was a master of satire. He wrote A Modest Proposal, and An Argument Against Abolishing Christianity.","Jonathan Swift"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar dared to try spread freedom and was assassinated as a result.","Benazir Bhutto"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford graduate wrote the screenplay for the movie The Third Man.","Graham Greene"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Romantic poet lived 1788-1824. Among his best works are Don Juan and When We Two Parted.","Lord Byron"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar is credited with making the first mechanical computer.","Charles Babbage"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This great scientist was able to show the equivalence of electricity, magnetism and light via a set of equations that carry his name.","James Clerk Maxwell"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar is the author of a series of books about a teddy bear .","A.A. Milne"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a great British mathematician, scientist, and philosopher. His attempt to give mathematics a complete axiomatic basis was foiled. In 1950 he won the Nobel Prize in Literature.","Bertrand Russell"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar and Indian Prime Minister was assassinated in 1984.","Indira Gandhi"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was, arguably, the greatest architect in British history. He designed St. Pauls Cathedral in London.","Christopher Wren"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a great British explorer, an orientalist, and, probably, the first non-Muslim to visit Mecca and Medina.","Richard Burton"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who wrote The Spy Who Came in From the Cold and The Constant Gardener?","John Le Carre"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Oxford scholar is given credit for developing the World Wide Web.","Vannevar Bush"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ah, beauty and brains! This British beauty attended Oxford but left before graduation to become an actress. She was seen in Pearl Harbor, Laural Canyon, and Serendipidy.","Kate Beckinsale"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This English author depicts an Oxford scholar (Clerk) as one of the pilgrims in his most famous work.","Chaucer"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 in 1661 Issac Newton was admitted to which college?","Trinity College, Cambridge"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 in the year 70, the Romans first broke through the walls of Jerusalem. Who was their leader?","Titus"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Denmark became a constitutional monarchy on June 5 in what year?","1849"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 in 1851 The Natonal Era began publishing a serial that took ten months to finish. The serial which treated slavery was made into a very popular book. Who was the author?","Harriet Beecher Stowe"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 in 1833 the first person acknowledged to be a computer programmer met the person considered the father of modern computing. Who met whom?","Ada Lovelace met Charles Babbage"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The USA began a program of Army registration day for World War I, on June 5 in what year?","1917"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first fax across the Atlantic to Europe was sent on June 5 in what year?","1924"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 during World War II, Rome was liberated from the Fascists. In what year did this happen?","1944"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Unknown Rebel halted an entire column of Chinese tanks in Tiananmen Square on June 5 in what year?","1989"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On June 5 in 1956 young Elvis Presley introduced his version of Hound Dog during his third appearance on a TV show. What was the show?","Milton Berle Show"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these events did not occur on a June 5?","Robert Blake was found liable for the death of his wife in a civil trial in 2000."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On October 12th 1492, after sailing across the Atlantic Ocean, Spanish explorer Christopher Columbus landed on a Bahamian island, thinking he had reached the Spice Islands of East Asia. He claimed the land for Isabella and Ferdinand of Spain, regardless of the indigenous population living there.","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On October 12th, 1998, this University of Wyoming student was robbed, tortured and left for dead by two attackers outside of Laramie, Wyoming.","Matthew Shepard"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 12 October in 1810, the first Oktoberfest was held to celebrate the marriage of then Bavarian Crown Prince Louis (Ludwig) and his bride, Princess Therese von Sachsen-Hildburghausen. Near what city were the festivities held?","Munich"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 12 October in 1945, PFC Desmond T. Doss won the Congressional Medal of Honor for outstanding bravery as a medical corpsman and became the first conscientious objector in American history to receive the nations highest military award.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["12th October 1582 does not exist in Italy.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did children attending American public schools do for the first time on October 12, 1892?","said the Pledge of Allegiance"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On 12 October, 1960, Nikita Khrushchev pounded this on a desk at the United Nations General Assembly meeting.","his shoe"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Communications Act of 1912 forced amateur operators to take lengthy tests before a Department of Commerce examiner and issued commercial ship-to-shore call signs to early broadcasting stations. Name the Secretary of Commerce that oversaw this first step toward communication regulation in the United States.","Herbert Hoover"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Radio Nederland, the BBC and Radio Berlin were three of the very few short wave radio stations broadcasting to international audiences before the 1930s. Short Wave referred to the wavelength of the radio frequencies such broadcasters used because they were much shorter than the typical 300 meter AM band used for commercial broadcasting.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The first licensed commercial radio station in the United States was KDKA in Pittsburgh.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where is the headquarters of NATO?","Brussels"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the two countries referenced in the title of the Two Plus Four Treaty, which resulted in the first expansion of NATO after the Cold War?","East Germany and Federal Republic of Germany"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was the North Atlantic Treaty signed on April 4, 1949?","Washington"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The International Security Assistance Force (10), that started on 20 December 2001, is a NATO-led mission for security and development in what country?","Afghanistan"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Operation Essential Harvest, meant to disarm ethnic Albanian groups, was carried out in what country?","Macedonia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who chairs the North Atlantic Council, the most senior political governing body of NATO?","the Secretary General"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the NATO ACCS Management Agency responsible for?","Air control"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What states are eligible for NATO membership?","European"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Gladio refer to?","a NATO operation"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What NATO member state does not have its own standing army?","Iceland"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name this Dutch shortwave radio program that runned for a total of 77 years on Radio Nederland and its predecessor?","The Happy Station"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A commercial radio stations first job is to educate its audience","False"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The reason for GEs purchase of the NBC Television Network is ironic - GE was forced to sell its RCA stock because RCA owned the fledgling broadcasting chain in the 1930s.","True"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is the following information true?","Yes"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Radio did not die when pictures were added just before World War I (Britain) or just after it (U.S.). How did it survive?","Created the combo-man (engineer and host) and began programming music to specific demographic cells."],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sounded the death knell for radio news on commercial radio stations?","Radio Deregulation Act of 1981"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why can one company own more than 200 radio stations in the United States?","To better present potential and existing sponsors (national, regional and local) the ability to easily purchase listeners in a market"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these colors is not present on the national flag of the Bahamas?","Green"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the color of the star featured on the national flag of Morocco?","Green"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the only country in the world whose national flag is not rectangular?","Nepal"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What interesting object is featured on the national flag of Grenada?","Clove of nutmeg"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What bird is featured on the national flag of Papua New Guinea?","Raggiana Bird of Paradise"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these colors is not present on the Seychelles flag?","Black"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What country has a crown depicted in the upper left corner of its flag?","Liechtenstein"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the only country in the world whose flag features a building?","Cambodia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The island of Tasmania has been called by this beautiful nickname.","Island of inspiration"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal which became extinct in the 20th century is depicted on the Coat of arms of Tasmania?","All of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the state capital of the Australian state of Tasmania?","Hobart"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the island of Tasmania named after?","Explorer"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tasmania is famous for the production of this alcoholic beverage.","Wine"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What celebrated Hollywood actor was born on the island of Tasmania?","Errol Flynn"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal became one of the symbols of the island and state of Tasmania?","Tasmanian Devil"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official motto of the Australian state of Tasmania?","Fertility and Faithfulness"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many distinct seasons are characteristic of the climate of Tasmania?","Four seasons"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the colors of the official state flag of Tasmania?","Blue, white and red"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Bayamo Anthem is the title of the national anthem of this island country.","Cuba"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Japan?","May Your Reign Last Forever"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What country has a national anthem entitled Chosen Land?","The Philippines"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The title of the national anthem of India is Jana Gana Mana. What does this mean?","Thou Art the Ruler of the Minds of All People"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Oh, Bright Dawn of May is the national anthem of this European country.","Montenegro"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What country adopted The March of Independence as its national anthem?","Turkey"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title of the national anthem of Australia?","Advance Australia Fair"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["My Fatherland, My Happiness and Joy is the title of the national anthem of this country.","Estonia"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of Hatikvah, the title of the national anthem of Israel?","The Hope"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["God Is Great is the title of the national anthem of this African country.","Libya"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the U.S. state of Wisconsin named after?","A river"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the capital city of the U.S. state of Wisconsin?","Madison"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal nickname was given to the U.S. state of Wisconsin?","Badger State"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The U.S. state of Wisconsin is well-known for the production of which of the following?","Cheese"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official state beverage of the U.S. state of Wisconsin?","Milk"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these famous actors was born in the U.S. state of Wisconsin?","Willem Dafoe"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The state of Wisconsin does not share a border with this U.S. state.","All of these"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the official one-word state motto of the U.S. state of Wisconsin?","Forward"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the state bird of the U.S. state of Wisconsin?","Robin"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of festival is the Summerfest, held annually in Milwaukee, Wisconsin, US?","Music festival"],"tags_json":"[\"trivia\",\"world\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
