{"kind":"deck","format":"deez.nut","version":2,"name":"Humanities v3"}
{"kind":"note","note_type":"basic","fields":["In which culture is pressing noses used as a greeting?","Maori (New Zealand)"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Two words that can be interchanged in a context are said to be antonyms.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What word means the same as meager?","paltry"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Constant means changing.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sick is the same as ill.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these words is a synonym of research?","investigate"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There many words that have the same meaning as low. Which of the following is NOT one of them?","escape"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The words barbed, biting, nipping or pungent could mean what?","sarcastic"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Whats the name of the singer who was involved with bicyclist Lance Armstrong?","Sheryl Crow"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This prolific author was also a screenwriter, penning the likes of I Dream of Jeannie, Hart to Hart and The Patty Duke Show.","Sidney Sheldon"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Jeffersons TV series, starring Sherman Hemsley, was a spinoff of All In The Family.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The group S.H.E plays country music in China.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In chemistry SHE stands for Standard Helium Electrode.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This actress is best known for playing Olive Oyl in 1979 and Wendy Torrance in 1980.","Shelley Duvall"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This influential English political philosopher believed in rule by absolute sovereign and the need for a social contract. His masterwork is Leviathan.","Thomas Hobbes"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This early scholastic philosopher was a Franciscan friar best known for his principle that opposes multiplying unnecessary entities in making propositions or drawing conclusions.","William of Ockham"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Twentieth Century English pacifist was the founder of analytic philosophy. His History of Western Philosophy helped him garner the Nobel Prize for Literature in 1950.","Bertrand Russell"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This influential philosopher espoused the master-slave theory of morality and believed in the will to power as the motivating force behind animal and human behavior.","Nietzsche"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Seventeenth Century Dutch rationalist was a pantheist excommunicated from the Jewish Church for heresy. He believed mind and body were of one substance. His greatest contributions were in the field of moral philosophy.","Spinoza"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["His Categorical Imperative was a concept for moral actions based on the premise that one should act only according to the maxim that such action could or would be made into a universal law.","Kant"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["He was a Seventeenth Century rationalist who invented calculus, put forth the doctrine of Windowless Monads, and believed that this universe was the best possible one God could have created.","Leibniz"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The sailors in South Pacific love a woman whose skin is as tender as DiMaggios glove and is always chewin betel nuts. If anyone has objections, Well aint that too damn bad.","Bloody Mary"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Andrew Lloyd Webber song I Dont Know How to Love Him is about what character?","Jesus Christ"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these songs from the movie Cabaret originated in the Broadway version?","Tomorrow Belongs to Me"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These songs all appear in the original Broadway version of The Sound of Music, but not in the movie version. Which one of them is NOT sung by Max and the Baroness?","An Ordinary Couple"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This ensemble song was removed just prior to the opening of the musical Show Boat, but its music remained as part of the overture.","Misrys Comin Around"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The song Send in the Clowns from the musical A Little Night Music was specifically written for which actress?","Glynis Johns"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these movie musical numbers was NOT nominated for a Best Original Song Oscar?","Come What May, Moulin Rouge"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The song A Little Priest, from Stephen Sondheims 1979 musical Sweeney Todd, is about what?","Cannibalism"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to a popular song from the 2003 puppet musical Avenue Q, what is the Internet for?","Porn"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the best-known tales of Arthurian times is The Sword in the Stone, written by T. H. White. In the book, the soon-to-be-king, Arthur, is lives with which of these people?","Sir Ector"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the popular childrens animated musical, Quest For Camelot, what well-known female singer provided the singing voice for Lady Juliana?","Cèline Dion"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1456, Sir Thomas Mallory completed what is one of the most well-known accounts of the life of King Arthur, called Le Morte DArthur.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the reign of King Henry II, what is thought to be the grave of King Arthur, was discovered where in England?","Glastonbury"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that in Greek mythology, Medusa, who was a beautiful girl with beautiful hair, became a Gorgon with serpents in her hair because she was arrogant and dared to compare her beauty to that of Athena?","No"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Gigantoleteira mean?","The giants destroyer"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the name Ergane mean?","Worker"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of musical instrument did Athena invent?","Flute"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does Korih, one of Athenas names, mean?","Virgin"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ancient Greeks believed that this Titan created man.","Prometheus"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Titan overthrew his father, Ouranos and ruled over the Earth before the gods.","Cronus"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These mythological figures were gigantic beings with one hundred hands.","Hecatoncheires"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Greek god is known as the Earth-shaker?","Poseidon"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Zeus is the Greek god of the sky and the chief of the gods.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the mythological giant three-headed dog that guarded the gate to the underworld.","Cerberus"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the home of the gods in Greek mythology?","Mt. Olympus"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Greek mythology, Pegasus and his brother, Chrysaor were born when Perseus decapitated this monster.","Medusa"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to Greek mythology, Odysseus and his men landed on the island of the Lotus Eaters following the Trojan War.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Polyphemus, the one-eyed son of Poseidon, asked his father not to allow this mythological hero to return home.","Odysseus"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Baroque painters Caravaggio and Rembrandt used chiaroscuro, an art technique, related to the distribution of light and dark in a painting.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Diego Velazquez, a Spanish Baroque Era painter, became most famous with what kind of paintings?","Portraits"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Boy Blowing a Horn, a sculpture created by Italian Baroque Era sculptor Pietro Tacca, is displayed where?","in the Hermitage Museum, Saint Petersburg, Russia"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Works of Pietro Bernini, a Baroque Era sculptor, are displayed in which American museum?","The Metropolian Museum of Art, New York City"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ottavio Leoni, an Italian Baroque Era printmaker and painter, painted which of the following drawings?","Urban III"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rubens, one of the most famous Flemish Baroque Era painters, was a student of Cornelis de Vos.","False"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did Diego Velazquez, a Spanish Baroque Era painter, spend his middle period?","Madrid"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In India dacoit is a synonym for what word?","bandit"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dear Elle:hes a lucky guy--","Omigod You Guys"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What division is based on the different treatment of the three original velar rows?","Satem and Centum languages"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Venetic is an extinct language from the Indo-European family that was spoken in what country?","Italy"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The official language of the Hittite Empire, the Hittite language, is part of what group of extinct Indo-European languages?","Anatolian"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What language of the Baltic group is extinct?","Selonian"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["English belongs to what group of languages in the Indo-European family?","Germanic"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Grimms law describes what Proto-Indo-European language?","Proto-Germanic language"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what group belongs the Spanish language?","Italic"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What language from the South-Slavic branch usees Cyrillic script?","Bulgarian"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Scythians, who dominated the Pontic steppe throughout Classical Antiquity. spoke a language that belongs to what Indo-European group?","Indo-Iranian"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest subdivision of Indo-European as regards the largest number of native speakers and of individual languages?","Indo-Iranian"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How is the Echidna described Greek mythology?","Half-woman, half-serpent"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of creature is Pegasus according to Greek legends?","Winged horse"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During which century did Italian painter Michelangelo live and work?","15th-16th century"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to painter and sculpture Michelangelo, art originated from which of the following?","Inner inspiration"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Michelangelos view of nature and its place in art?","He saw it as an enemy."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about Michelangelo?","He lived in poverty."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Painter and sculptor Michelangelo is believed to have had homosexual inclinations.","True"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these phrases is a synonym of limbo?","Middle ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these phrases refers to cemetery?","Burying ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What phrase is a synonym of jungle?","Uncultivated ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the term swale refer to?","Low ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which phrase is a synonym of chase?","Hunting ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the word bog mean?","Spongy ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the word hardpan?","Hard ground"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What syntactic element is not part of the predicate?","Subject"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What category is never marked on Non-Finite Verb Phrases such us to have been studying, being studied, etc?","Tense"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the sentence Cristiano Ronaldo was the best player available, what is the syntactic function of the Noun Phrase the best player available?","Subject Complement"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sentence is not in the indicative clause type (or mood)?","Dont move!"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sentence contains an Obligatory Adjunct, also known as Predicator Complement?","The baby weighs 9 pounds."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Identify the Operator in the sentence: The football match must have been played last Saturday.","must"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The nominal clauses are finite dependent clauses that fulfill the functions of Subject, Object and Complement in clause structure. There are four main types: wh-nominal relative, dependent exclamative, wh-interrogative and what other type?","that-clause as in He saw that the bottles were empty."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where do we have an example of code, one of the NICE constructions (negation, inversion, code and emphasis)?","I will stay, if you will."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what sentence is there a modifier in the Adverbial Phrase?","My shoes are bright red."],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of what kind is the coordination between the clauses in the sentence You should neither ask him for money nor accept it if he offers?","Alternation"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete this line from a song, featured in the movie Cannibal! The Musical:","a baked potato"],"tags_json":"[\"trivia\",\"humanities\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
