{"kind":"deck","format":"deez.nut","version":2,"name":"Literature v3"}
{"kind":"note","note_type":"basic","fields":["This novel by Jules Verne, often called his lost novel, was written in 1863 and published for the first time in 1994. It tells the story of a young man who lives in a highly technologically advanced world.","Paris in the 20th Century"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the reason for Jules Vernes permanent limp with his left leg?","He was shot."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jules Vernes publisher, Pierre-Jules Hetzel suggested that Verne make what kind of major changes in all of his works?","Introducing a more optimistic tone"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these inventions did Jules Verne predict in his novels written in the 19th century?","All of these"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What novel by Jules Verne was used as a base for a 2008 3-D science fiction movie directed by Eric Brevig?","Journey to the Center of the Earth"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do the initials T. S. stand for in the name of the famous poet T. S. Eliot?","Thomas Stearns"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["T. S. Eliot was the last of 6 children surviving. How old were his parents when he was born?","44"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["T. S. Eliots father, who came from a prominent New England family, was on the Board of Directors of Washington University. He was also a Chairman at Hydraulic-Press Brick Company in St. Louis, a successful business man and a chemist. He married Eliots mother in 1868. What was her occupation?","A poet and a social worker"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["T. S. Eliot attended this prestigious Ivy League college, editing its literary magazine with Pulitzer- winning poet Conrad Aiken.","Harvard"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["While a doctoral student, T. S. Eliot studied Buddhism and Indic philology, learning Sanskrit and Pāli to read the religious texts. What languages did Eliot study/learn in prep school and college?","Latin, Greek, French, and German"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In April 1915, T. S. Eliot met Vivienne Haigh-Wood, a governess in Cambridge. They were married on 26 June 1915. Where were they married?","In a local register office"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After marriage, T. S. Eliot gave up writing his dissertation, and never received his PhD.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["After leaving college in Oxford, T. S. Eliot took a teaching job at Highgate School. There he taught this future British Poet Laureate, documentarian of Metro-land, and self-described poet and hack.","Sir John Betjeman"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["While a student at Harvard, T. S. Eliot befriended this Spanish-born philosopher, essayist, poet, and novelist who wrote in Reason in Common Sense, Those who cannot remember the past, are condemned to repeat it.","George Santayana"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous poem by T. S. Eliot was considered offensive and upsetting because of its opening lines describing the dusky sky as a patient etherised upon a table.?","The Love Song of J. Alfred Prufrock"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["First published in 1915, this poem by T. S. Eliot portrays upper class society as quite empty and lonely. Its epigraph is from Marlowes The Jew of Malta-","Portrait of a Lady"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1920, T. S. Eliot published the collection Poems. It included the poem Gerontion. What famous phrase, often used to describe espionage and counter-intelligence, comes from this poem?","wilderness of mirrors"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In his book Lies and the Lying Liars Who Tell Them, Al Franken refers to this radio talk show host as a Big Fat Idiot.","Rush Limbaugh"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In his book Lies and the Lying Liars Who Tell Them, Franken writes that these two words are Bill OReillys answer to any intelligent liberal comment.","shut up"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Al Franken is critical of this veteran news journalist, famous as managing editor of the Fox News Channel.","Brit Hume"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is Al Franken talking about when he says, He had us all supporting him and united after 9/11 and then he created a war in Iraq and he will never really have Mission Accomplished?","George W. Bush"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why did Al Franken choose to run as a Democrat according to Franken himself?","They care more about the poor than the Republicans"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the church that Rayford Steele, Chloe Steele, Buck Williams and Bruce Barnes are members of in the second novel in the Left Behind series?","New Hope Village Church"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who coined the name Tribulation Force for the group portrayed in the second book of the series Left Behind?","Chloe"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fictional characters Both Buck and Rayford go to work for Nicolae Carpathia in Tribulation Force.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Hattie Durham becomes romantically involved with which character in Tribulation Force?","Nicolae"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["One of the most interesting characters introduced in Tribulation Force is Rabinnacal Scholar Tsion (pronounced Zee-own) Ben-Judah, who made a startling announcement to the whole world that put him and his family in jeopardy. What was his announcement?","He believed Jesus was the promised Messiah."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Both Rayford and his daughter Chloe are married in Tribulation Force","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The American Military moves against Nicolae in the book Tribulation Force","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nicolae Carpathia, the main antagonist in the Left Behind series, institutes a one-world religion.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What stunning announcement does Hattie make near the end of Tribulation Force?","She is pregnant with Nicolaes child."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which member of the Tribulation Force dies at the end of the self-titled novel?","Bruce"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Dick Franciss profession before he became a writer?","Jockey"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first novel Dick Francis wrote?","Dead Cert"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what novel by Dick Francis does the popular character Sid Halley first appear?","Odds Against"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sid Halley, the protagonist of several novels by Dick Francis, is disabled. What is the nature of his disability?","He has only one hand."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Only two Dick Francis characters appear as the protagonist of more than one book. Sid Halley is one of them. Who is the other?","Kit Fielding"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the profession of Charles Todd in the novel In the Frame?","Painter"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many non-fiction books did Dick Francis write in the 20th century?","two"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why didnt Dick Francis win the 1956 Grand National when he was a jump jockey for the Queen Mother?","His horse fell."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the popular rumor that circulated about Dick Franciss books?","His wife wrote them."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What did Dick Francis do after the death of his wife?","He began collaborating with his younger son Felix."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The members of the Pretty Committee, described in the novel The Clique, get kicked out of school.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kristen Gregory from the book The Clique is rich and always wears designer clothes.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Clique, what school do the members of the Pretty Committee go to?","OCD"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the Pretty Committees second in command in the book The Clique?","Dylan"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who comes back with Alicia from Spain in Lisi Harrisons The Clique?","Nina"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What movie does The Clique character Claire get a part in?","Dial L for Loser"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Clique protagonist Massie Block has a pet in the book.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Call me Ishmael.","Moby-Dick"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There were four of us.","Three Men in a Boat"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was a pleasure to burn.","Fahrenheit 451"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["No one would have believed, in the last years of the nineteenth century, that human affairs were being watched keenly and closely by intelligences greater than mans and yet as mortal as his own; that as men busied themselves about their affairs they were scrutinized and studied, perhaps almost as narrowly as a man with a microscope might scrutinize the transient creatures that swarm and multiply in a drop of water.","The War of the Worlds"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It was the best of times, it was the worst of times. is the beginning of this famous Dickens historical novel, concerning the French Revolution and dealing with some timeless moral issues, such as guilt, treachery and patriotism.","A Tale of Two Cities"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It can hardly be a coincidence that no language on Earth has ever produced the expression as pretty as an airport.","The Long Dark Tea-Time of the Soul"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If you really want to hear about it, the first thing youll probably want to know is where I was born, and what my lousy childhood was like, and how my parents were occupied and all before they had me, and all that David Copperfield kind of crap, but I dont feel like going into it, if you want to know the truth.","The Catcher in the Rye"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.","Pride and Prejudice"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This happened in 1932, when the state penitentiary was still at Cold Mountain. And the electric chair was there, too, of course.","The Green Mile"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Happy families are all alike; every unhappy family is unhappy in its own way.","Anna Karenina"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Both in the year when Mark Twain was born and the year when he died, the Halleys Comet passed by Earth.","Samuel Langhorne Clemens"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This romantic hero is a wealthy gentleman who at first feels superior to Elizabeth Bennet and ignores her. Later, however, he falls in love with her, which is a blow to his pride.","Mr. Darcy"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This literary character from the only novel of Emily Bronte is passionately and intensely in love with Cathrine Earnshow, but she marries someone else because of her desire for social advancement.","Heathcliff"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This literary character has an obssessive love affair with Mildred Rogers, a shallow and self-centerd woman he encounters in London.","Philip Carey"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This fictional hero falls in love with his employee, the governess Jane Eyre, but their wedding ceremony is interrupted by the announcement that he has a wife who lives in the attic of his manor, Thornfield Hall.","Edward Rochester"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This romantic hero is obsessed with the beautiful Fermina Daza. He waits more than 50 years for her husband to die and declares his love for her.","Florentino Ariza"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This mysterious literary hero acquired an immense wealth in order to win back his beloved Daisy, who had married Tom Buchanan.","Jay Gatsby"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This American officer, the literary creation of Ernest Hemingway, deserts World War I and escapes to Switzerland with his beloved Catherine Barkley.","Frederic Henry"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This romantic literary character loves passionately Estella, a beautiful girl, brought up by the cold, wealthy and eccentric Miss Havisham.","Pip"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This pragmatic and opportunistic literary hero is attracted by the pretty and coquettish Scarlett OHara.","Rhett Butler"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This literary character, depicted by the Victorian writer Thomas Hardy, escapes with Tess, the woman he loves, although she had committed a murder.","Angel Clare"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this novel the main character, Rodion Razkolnikov, who lives in St. Petersburg, murders an old pawnbroker and her younger sister, and later, gets overwhelmed by feelings of paranoia and self-loathing.","Crime and Punishment"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this novel, American millionaire Samuel Edward Ratchett is found stabbed to death during a journey. The case is investigated by detective Hercule Poarot, who is also among the passengers.","‘Murder on the Orient Express’"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel ‘A Study In Scarlet’, the word ‘RACHE’ is written in blood on the wall of a deserted house beside a dead body. Name the literary detective who investigates the case.","Sherlock Holmes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this famous play Claudius murders his brother, the King of Denmark, and marries the widowed Queen Gertrude.","Hamlet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this novel, private eye Philip Marlowe is arrested on suspicion of the murder of Terry Lenox’s wife. After Marlowe is released, he finds out that Terry Lenox, himself, has committed suicide in Mexico. When Marlowe gets home, he finds a cryptic note from Lenox and a $5000 bill.","‘The Long Goodbye’"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this book, based on a true story, Truman Capote recounts the murders of Herb Clutter, a rich farmer from Kansas, his wife Bonnie, his sixteen-year-old daughter Nancy, and his fifteen-year-old son, Kenyon.","‘In Cold Blood’"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this bestseller, based on a real case and written by Joe McGinnis, Jeffrey MacDonald is accused of killing his pregnant wife and two young daughters.","‘Fatal Vision’"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This author wrote ‘The Road to Gandolfo’, a story in which the former General MacKenzie Hawkins makes up an outrageous plan to kidnap the Pope and to demand a ransom of $400 million – a dollar for every Catholic in the world.","Robert Ludlum"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This novel is narrated by the fictional character Frank Chambers, a drifter who stops at a roadside diner and meets ‘femme fatale’, Cora. After starting an affair, Cora and Frank murder Cora’s husband, Nick Papadakis, who is the owner of the diner.","‘The Postman Always Rings Twice’"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this novel, written by Agatha Christie, the Banty family discover in their library the dead body of a young woman. Later, the remains of another dead girl are found in a nearby quarry. Which detective investigates the case?","Miss Jane Marple"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many works did Stephen King write under the pseudonym Richard Bachman?","6"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the horror novel From a Buick 8, strange reptiles crawled out of the trunk of a car.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Jacks werewolf friend in the novel The Talisman?","Wolf"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was one of Randall Flaggs nicknames in Stephen Kings novel The Stand?","the walking dude"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Stephen Kings novel The Girl Who Loved Tom Gordon, what position did Tom Gordon play for the Boston Red Sox?","relief picher"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Dolores Claiborne, what is the name of Dolores Claibornes daughter?","Selena St. George"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the mouse in the book The Green Mile?","Mr. Jingles"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of the parts that Tolkien originally divided the book in do Aragorn, Gimli, and Legolas decide to go after Merry and Pippin in The Two Towers?","First"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book Lord of the Rings: The Two Towers, does Gollum ever decide to be on Frodos side?","No"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book, Lord of the Rings: The Two Towers, does Eowyn have romantic interest in Aragorn?","Yes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Aragorn ever really have a doubt about his place on the throne of Gondor In the book, Lord of the Rings: The Two Towers?","No"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is Wormtongue really sad when he sees the army of Uruk-Hai in the book, Lord of the Rings: The Two Towers?","Not in the least"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book, Lord of the Rings: The Two Towers, does Aragorn fall off of a cliff?","No"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do the orcs ride wolves in the book, Lord of the Rings: The Two Towers?","Yes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Diary of a Madman","Guy de Maupassant"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Servant of the Bones","Anne Rice"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Hellbound Heart","Clive Barker"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Tell-tale Heart","Edgar Allan Poe"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Talisman; Black House","Both"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As I Lay Dying","William Faulkner"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Battlefield Earth","None of these"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Dunwich Horror; The Colour Out of Space; The Dream-Quest of Unknown Kadath","H.P. Lovecraft"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Devils Dictionary","Ambrose Bierce"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Doll Who Ate His Mother","Ramsey Campbell"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Scottish poet, born in 1759, wrote the famous song Auld Lang Syne which goes like this:","Robert Burns"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How old was the prominent English poet John Keats when he died in 1821?","26 years old"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these plays by English poet and playwright William Shakespeare is not a comedy?","Macbeth"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these poems was written by American Modernist poet T. S. Eliot and describes his feeling of depression and pessimism about society after World War I?","The Hollow Men"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This American poet, born in 1874, won the Pulitzer Prize four times and recited his poem The Gift Outright at the inauguration of U.S. President John F. Kennedy.","Robert Frost"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Anglo-Scottish poet, author of Childe Harolds Pilgrimage, died in Greece where he participated in the fight for the countrys independence?","George Gordon Byron"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which famous work by American poet Henry W. Longfellow was based on the legends of the Ojibway Indians?","The Song of Hiawatha"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Norwegian band used William Blakes influential poem The Marriage of Heaven and Hell as lyrics for their 1998 album Themes from William Blakes The Marriage of Heaven and Hell?","Ulver"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these poems from Walt Whitmans masterpiece collection Leaves of Grass was dedicated to U.S. President Abraham Lincoln?","O Captain! My Captain!"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The title of the 2004 movie Eternal Sunshine of the Spotless Mind was taken from the poem Eloisa to Abelard written by which English poet?","Alexander Pope"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which book by Mark Twain is Jim a major character?","Huckleberry Finn"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which novel does the evil Injun Joe appear?","The Adventures of Tom Sawyer"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which work by Mark Twain do we find Adam and Eve writing their diaries?","Letters from the Earth"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which story features a character named Jim Smiley who was responsible for one of the tallest tales of the Old West?","The Celebrated Jumping Frog of Calaveras County"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sir Boss is the protagonist of which novel?","A Connecticut Yankee in King Arthurs Court"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aunt Polly is a character from which book?","The Adventures of Tom Sawyer"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which novel did Mark Twain- Special Travelling Correspondent of the Alta appear?","The Innocents Abroad"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In this novel we find Cal Higbie and Mark Twain celebrating the curious time when the two were millionaires for ten days?","Roughing It"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which novel do the Duke and the King do their best to swindle god-fearin folk?","Huckleberry Finn"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which story does Danl Webster appear as a leading character?","The Celebrated Jumping Frog"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dying is an art like everything else. I do it so it feels like hell. I do it so it feels real.","Sylvia Plath"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["I saw the best minds of my generation destroyed by madness, starving, hysterical, naked","Allen Ginsburg"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Preface to a Twenty Volume Suicide Note","Immamu Amiri Baraka"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Penetrating a Fresh Abyss","David Payne, Jr."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This is the way they ring the bells in Bedlam","Anne Sexton"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why talk of beauty? What could be more beautiful than these heroic happy dead who rushed like lions to the roaring slaughter? They did not stop to think--they died instead. Then shall the voice of liberty be mute?","E. E. Cummings"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the desert I saw a creature naked, bestial. Squatting on the ground he held his heart in his hands and ate of it. I asked Is it good, friend? It is bitter--bitter he replied but I like it because it is bitter and because it is my heart.","Stephen Crane"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["We are the hollow men. We are the stuffed men. Leaning together-- headpiece filled with straw--alas! Our dried voices when we whisper together are meaningless as wind in dry grass or rats feet over broken glass in our dry cellar....This is the way the world ends not with a bang but a whimper.","T.S. Eliot"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Book of Nightmares","Galway Kinnel"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Twilight, Bellas dad Charlie buys her an old Chevy truck as a homecoming gift. What colour is it?","Red"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Though it is girls choice, who asks Bella to the spring dance in the book Twilight?","All of these"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book Twilight, Edward says he is 17, but admits he has been 17 for a while. In what year was he actually born?","1901"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bella, the protagonist of the novel Twilight, is tracked by a vampire intent on killing her. What is his name?","James"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Twilight, Jasper is the newest member of the Cullen family and the last to adopt their vegetarian diet.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During his round of questions in the novel Twilight, Edward asks Bella what her favourite gemstone is, to which she immediately answers Topaz, the colour of Edwards eyes. Until recently she would have given a different answer. What did her favourite gemstone use to be?","Garnet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In chapter 6 of the novel Twilight, Mike Newton organises a beach trip to this beach.","First Beach"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Twilight, Carlisle found Edward whilst working in a hospital in Chicago. What was Edward dying of?","Spanish Influenza"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What game do the Cullens play in the thunderstorm in the novel Twilight?","Baseball"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel Twilight, who accompanied Bella, when she went to Phoenix to try escape the tracker?","Alice and Jasper"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American hero does Henry Wadsworth Longfellow write about in this poem:","Paul Revere"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This poet, who is famous for his use of lowercase letters and word space, wrote the following:","e e cummings"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of this poem by Edna St. Vincent Millay:","First Fig"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lestat was made into a vampire by Marius.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The Vampire Chronicles Akasha was known as the Mother of all Vampires","Yes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the full name of Bastian, the main character in the book The Neverending Story?","None of these"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Michael Endes novel, The Neverending Story, Bastian stole The Neverending Story from Mr. Smith.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Atreyu, one of the characters in the book The Neverending Story, is what kind of warrior?","Greenskin warrior"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Ygramuls secrete in the fantasy novel, The Neverending Story?","It has magic poison."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of dragon is Falkor in Michael Endes novel The Neverending Story?","A Luck dragon"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did Atreyus horse die in the fantasy novel, The Neverending Story?","in the Swamps of Sadness"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Neverending Story, what kind of creature is Engywook?","Gnome"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Uyulala, is a character in the novel The Neverending Story, that only speaks in rhymes.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many wind giants are there in the book The Neverending Story?","4"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name does Bastian give to the Childlike Empress in The Neverending Story?","Moon Child"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following books, published in 1903, brought everlasting fame to Jack London?","The Call of the Wild"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The life of which character, depicted by Jack London, resembles very much the authors life?","Martin Eden"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following novels by Jack London tells the story of the intellectual Humphrey van Weyden, who is forced to become a common seaman?","The Sea-Wolf"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which novel by Jack London depicts the rise of a fascist-like regime in America?","The Iron Heel"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What breed is the dog Buck, the protagonist in The Call of the Wild by Jack London?","St. Bernard/Collie mix"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following tales is not part of the collection Children of the Frost (1902) by Jack London?","To Build a Fire"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1910 Jack London bought a ranch in Glen Ellen, California, and since then he began to write mostly to finance it.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following novels played a decisive role in Jack Londons life according to his own words, and turned him to literature when he was only eight years old?","Ouidas Signa"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The main story in The Little Lady of the Big House (1916) by Jack London focuses on what?","A love triangle"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Song of Susannah, Susannah is pregnant with whose baby?","Roland"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Song of Susannah takes place mostly in our world, in New York and which other US State?","Maine"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Once born, the child carried by Susannah/Mia was called what?","Mordred"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jake and Father Callahan travel to New York of 1999 and store the Wizards Glass known as Black Thirteen in a deposit box under which famous building?","World Trade Center"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Song of Susannah, Roland and Eddie travel to New York of 1977 in an attempt to buy a plot of land from which man?","Calvin Tower, a bookstore owner"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["While in Maine, Roland and Eddie hear that they are near the home of the author Stephen King, a name that interests them because of the link with which book in their possession?","Salems Lot"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When he meets Stephen King, Roland the gunslinger hypnotises him. What does Roland use to hypnotise people?","A bullet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["While he has Stephen King hypnotised, Roland implants an instruction in the authors mind, what is it?","To continue writing the Dark Tower series of novels"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jake and Father Callahan attempt to rescue Susannah from a restaurant in New York, where she is being held by the soldiers of The Crimson King. What is the name of the restaurant?","The Dixie Pig"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Susannah had left a scrimshaw ornament behind before she was taken into the restaurant, which gave Jake and Father Callahan hope when they found it. What animal shape had the scrimshaw been carved into?","Turtle"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where was Edgar Allan Poe born?","Massachusetts"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Edgar Allan Poes first poem to be published?","The Raven"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What branch of the military did Edgar Allan Poe enlist in?","US Army"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Edgar Allan Poes only completed novel?","The Narrative of Arthur Gordon Pym of Nantucket"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Edgar Allan Poe poem are the following lines from?","Ulalume"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following poems was not written by Edgar Allan Poe?","I Carry Your Heart With Me"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what age did Edgar Allan Poe die?","40"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Edgar Allan Poes last book to be published?","Eureka"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the main characters daemon in the novel The Golden Compass?","Pantalaimon"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the mysterious substance that is being researched in the North by Lord Asriel in Phillip Pullmans book The Golden Compass?","Dust"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Golden Compass, the Master gives the main character an Alethiometer and instructs her to deliver it to Lord Asriel.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who takes the main character of The Golden Compass as a personal assistant?","Mrs. Coulter"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Golden Compass, who is the main characters best friend that turns up missing?","Roger"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The story of the novel The Golden Compass begins in the fictional Jordan College in Oxford.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Golden Compass, are the main character and her friends often at war with the local children of Oxford?","Yes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The Golden Compass, what is Lyras daemons favorite form to sleep in?","Ermine"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Golden Compass, what do the storytellers call those on the General Oblation Board?","Gobblers"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is Lyras uncle in Philip Pullmans novel The Golden Compass?","Lord Asriel"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Golden Compass, can adult daemons change into any form they want?","No"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which English city was author Clive Barker born?","Liverpool"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Clive Barkers book Weaveworld, what is the name of the magical world which lies woven within a rug?","The Fugue"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The novel Weaveworld was made into a comic series in 1991, published by which comic house?","Epic Comics"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the magic sea in the book The Great and Secret Show?","Quiddity"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The 1987 movie Hellraiser was based upon the Clive Barker novella The Damnation Game.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Hellraiser film series, what is the name of the puzzle-box used to open the gateway to the other world?","Lament configuration"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Complete the title of this Clive Barker novel, written as a fable for children: The Thief of _________.","Always"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Clive Barker novel tells a Hollywood ghost story?","Coldheart Canyon"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Clive Barker had his screenplay for the remake of the Japanese monster film Gojira rejected because it was too dark and disturbing.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This book that launched the Discworld series was first published in the U.K. in 1983.","The Colour of Magic"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which surly, jaded denizen of Ankh-Morpork, depicted by Terry Pratchett, is Commander of the Night Watch?","Samuel Vimes"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these is not a guild from the fictional city of Ankh-Morpork?","Sewer Workers Guild"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Terry Pratchetts Discworld series, Death once took over The Hogfathers job and attempted to deliver his version of holiday presents to all the children of Discworld, much like in Tim Burtons film, The Nightmare Before Christmas.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cohen the Barbarian, the greatest hero that Discworld has ever produced, is about 90 years old. He thinks that which one of these is not one of the greatest things in life?","A lovely bit of music"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What popular musical was parodied by Terry Pratchetts 18th Discworld book, Maskerade?","The Phantom of the Opera"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bloody Stupid Johnson, Discworlds famous dyslexic architect, is Terry Pratchetts version of Leonardo da Vinci.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Discworld, the fictional planet on which Terry Pratchetts famous series of novels is set, is carried on the back of four great space elephants. What are the elephants standing on?","ATuin, the star turtle"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many books of the Discworld series were published prior to 2007?","35"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What pen name did Isaac Asimov use for his science fiction series for teenagers titled Lucky Starr?","Paul French"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Isaac Asimov and these other two writers were considered the Big Three science-fiction writers during Asimovs lifetime.","Robert A. Heinlein and Arthur C. Clarke"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these series was not written by Isaac Asimov?","Dune series"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Isaac Asimov suffered from which of the following disorders?","fear of flying"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these entries from the Oxford English dictionary is not a word created by Isaac Asimov?","cyberspace"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the first science fiction short story Isaac Asimov wrote?","Cosmic Corkscrew"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not a science fiction novel co-written by Isaac Asimov and Robert Silverberg?","The Shrouded Planet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what genre of literature other than science fiction did Isaac Asimov write?","mystery"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This book penned by Isaac Asimov won the Hugo (1972), Nebula (1973) and Locus (1973) Awards for best science fiction novel.","The Gods Themselves"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the full name of English writer Terry Pratchett born in 1948?","Terence David John Pratchett"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the title of Terry Pratchetts first published work, a short story printed in his school magazine?","The Hades Business"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these books by Terry Pratchett does not belong to his Discworld series?","The Unadulterated Cat"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is fantasy writer Terry Pratchetts astrological sign?","Taurus"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Terry Pratchetts Discworld series, the lines of what character are usually typed in capital letters?","Death"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When was Terry Pratchett appointed an Officer of the Order of the British Empire for services to literature?","1998"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these four books of Terry Pratchetts Discworld series was published first?","The Colour of Magic"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Terry Pratchett supports this organization in many ways, one of which is fundraising by auctions where people bid money in order to get a Discworld character named after them in the writers next book.","The Orangutan Foundation"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which British artist worked on the UK covers of Terry Pratchetts books of the Discworld series until 2001?","Josh Kirby"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of writer Terry Pratchetts daughter, born in 1976?","Rhianna"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How did Bilbo Baggins come across the One Ring in the novel The Fellowship of the Ring?","When he gets lost in the goblins cave, he finds it in the dirt."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tolkiens character Frodo was 33 when he left for Rivendell.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which elf did the Hobbits talk to on their way to Bree in the novel The Fellowship of the Ring?","Gildor"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which character helped Frodo and Sam rescue Merry and Pippin from the trees?","Tom Bombadil"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the book The Fellowship of the Ring, Arwen was the elf that brought Frodo Baggins across the river into the land of Rivendell.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the river that Glorfindel took Frodo Baggins across?","Bruinen"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["24 October was the day that Tolkiens character Frodo awoke in Rivendell after his ailment.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is stated in The Fellowship of the Ring that the emblems of Durin are wrought of ithildin that mirrors only starlight and moonlight.","True"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What gift did Lady Galadriel give to Samwise Gamgee in The Fellowship of the Ring?","A wooden box with a silver rune"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Uruk-hai, which were described in The Fellowship of the Ring, could only run in the light of the moon.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Thorne Smiths Topper series consists of how many novels?","Three"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Topper novels by Thorne Smith, who is Cosmo Topper?","A banker"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these best describes the plot line of the novel Turnabout by Thorne Smith?","The husband and wifes bodies are magically interchanged."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Glorious Pool by Thorne Smith, what happens to the middle-aged man, his wife, and his mistress?","They become young again."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The protagonist of which Thorne Smith novel has the ability to turn statues into living people?","The Night Life of the Gods"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the novel The Bishops Jaegers by Thorne Smith, what are the jaegers?","Underwear"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is the most accurate description of plot line of Thorne Smiths novel Passionate Witch?","A 17th Century witch is transported into the 20th Century."],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Night life of the Gods by Thorne Smith what object is responsible for the transformations that occur throughout the story?","A ring"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which novel by Thorne Smith do all the main characters end up in court before a totally befuddled judge?","all of these"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The main character of which novel by Thorne Smith is turned into a skeleton?","Skin and Bones"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["William Shakespeare had two daughters and one son, named Susanna, Judith, and Hamlet.","False"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["From what Shakespeare play did Aldous Huxley derive the title of his famous novel, Brave New World?","The Tempest"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The popular Globe Theatre was owned by actors in what famous playing company of the Elizabethan age?","Lord Chamberlains Men"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Shakespeare died on April 23, 1616. What other famous author died on the same day?","Miguel de Cervantes Saavedra"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What character from the play Hamlet made famous the line, Something is rotten in the state of Denmark!?","Marcellus"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Shakespeare comedy contains the following lesser known characters: Quince, Snug, Snout, Flute, Bottom, and Starveling?","A Midsummer Nights Dream"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The drama, My Own Private Idaho, starring Keanu Reeves and the late River Phoenix, is adapted from this Shakespeare play.","Henry IV"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["For what role did Laurence Olivier win a Best Actor Oscar in 1948?","Hamlet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The famous Wedding March is incorporated in the music that German composer Felix Mendelssohn wrote in 1842 for what Shakespeare play?","A Midsummer Nights Dream"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What English poet wrote the poem In the Bleak Midwinter in which Snow had fallen, snow on snow,","Christina Rossetti"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What American Modernist poet wrote the poem The Snow Man, which opens with the lines,","Wallace Stevens"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the play by William Shakespeare in which the character Sir Andrew Aguecheek appears.","Twelfth Night"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which play by William Shakespeare is the character King Claudius introduced?","Hamlet"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Shylock is a character depicted in this Shakespearean play.","The Merchant of Venice"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Angelo is a character from this famous play by William Shakespeare.","Measure for Measure"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Iago is the antagonist of which play by William Shakespeare?","Othello"],"tags_json":"[\"trivia\",\"literature\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
