{"kind":"deck","format":"deez.nut","version":2,"name":"Entertainment v1"}
{"kind":"note","note_type":"basic","fields":["Greta Garbo was successfully treated for this disease.","Breast cancer"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1952, A.S. Douglas developed the first graphical game to run on a computer. It ran on the EDSAC. What was the name of this game?","OXO"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nolan Bushnell is considered to be the father of the video arcade industry. In 1972 he founded his own game company and together with Ted Dabney and Al Alcorn released the first arcade video game with major success- Pong. What was the name of his company?","Atari"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pong was first installed at a high school.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1972 a company named Waco released the first handheld electronic game. What was its name?","Tic Tac Toe"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1978 Taito released one of the most influential arcade video games. It was called Space Invaders and marked the beginning of the Golden Age of arcade games. What was the thing that the player controlled in Space Invaders?","A movable laser cannon"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mario, probably the best-known video game character, first appeared in Donkey Kong in 1981. His brother Luigi first appeared in Mario Bros.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Nintendo is undoubtedly one of the most successful and best known console manufacturers. Nintendo has created several TV consoles and many handheld portables, such as the Game Boy and the Game Watch. When was the company originally founded?","1889"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["With the introduction of cheap and relatively powerful processors such as Intel 386, Intel 486 and Motorola 68000 3D-graphics became fashionable. It was used in FPS games like the legendary Wolfenstein 3D and Doom. Do you know what FPS stands for in this context?","First Person Shooter"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Sonic the Hedgehog is a mascot of Sony Playstation.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When in 1996 3dfx released the Voodoo chipset, it made high-resolution and more-detailed 3D games possible. One of the first games to take advantage of this was Quake. Do you know which company released this marvelous game?","id Software"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These fictional superheroes were born, when a container of radioactive waste bounced off a truck and struck a young boy, turning him into Daredevil.","Teenage Mutant Ninja Turtles"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This superhero, who first appeared in the comic book Tales of Suspense, used his own invention to keep his heart pumping.","Iron Man"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Marvel Comics superhero, whose birth name was Peter Benjamin Parker, first used his new found superpowers as a professional wrestler.","Spiderman"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This comedic superhero, created by Ben Edlund, met an accountant named Arthur, after taking a long bus ride into The City.","The Tick"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These comic book superheroes were trained in Professor Xaviers School for Gifted Youngsters.","The X-Men"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Marvel Comics character became a ruthless vigilante, after witnessing his familys violent murder?","The Punisher"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This DC Comics superhero, whose true identity is Bruce Wayne, decided to train himself to the peak of physical perfection after witnessing the murder of his parents.","Batman"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which fictional member ot the Teen Titans started out as Batmans sidekick?","Nightwing"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fellow Justice League members Superman and Martian Manhunter have something in common. What is it?","They are both aliens."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following fictional heroes is a World War II veteran?","Captain America"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the real name of Gambit who first appeared in the comic book The Uncanny X-Men?","Remy LeBeau"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these X-Men characters is not a member of the Summers family line?","Mister Sinister"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Archangel, a mutant and a member of the X-Men, was which horseman of Apocalypse?","Death"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which antagonist of the X-Men is responsible for the death of Wolverine in the comic books?","Magneto"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these X-men characters is not a mutant?","Juggernaut"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Age of Apocalypse timeline, Wolverine, a member of the X-Men, is married to which female?","Storm"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the head of the X-Men in the Age of Apocalypse timeline?","Magneto"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Omega Red, a foe of the X-Men, serves which country?","Russia"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the real name of X-Men member Wolverine?","James Howlett"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This member of the Hellfire Clubs inner circle, known as the White Queen, once fought against the X-Men.","Emma Frost"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When was the Miss America pageant first held?","September 7, 1921"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The most common talents performed are singing and dancing, but there have been a variety of other odd talents as well. Which talent was performed at a Miss America pageant?","Packing a suitcase"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first Jewish Miss America?","Bess Myerson"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Miss America always goes on to compete in the Miss Universe pageant.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["As of the beginning of the new millenium, how many Miss America title holders were from New Jersey, the state that held the competitions?","2"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the first deaf Miss America?","Heather Whitestone"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Until 2004 ABC aired the Miss America pageant , it then switched to what station?","CMT"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Snoopy first make his first appearance in a comic strip?","1950"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name was Charles Schulz originally going to give to Charlie Browns dog Snoopy?","Sniffy"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What position did cartoon character Snoopy play in Charlie Browns Little League baseball team?","Short Stop"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did comic strip character Snoopy first appear sleeping on top of his doghouse?","1958"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did comic strip character Snoopy first walk upright?","1956"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these pairs roller coaster- theme park is wrong?","Avalanche- Holiday World"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Top Thrill Dragster was opened in 2003 and it was the tallest and fastest roller coaster in the world until 2005 (this is true). It was the first roller coaster to break the 300 ft (91.4 m) barrier.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these pairs roller coaster- year of opening is wrong?","Nitro- 2000"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["October 2006 saw the release of which Mortal Kombat game?","12th"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Mortal Kombat storyline, Liu Kang was brutally murdered by which character?","Shang Tsung"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What feature makes Kenshi different from all other Mortal Kombat characters?","He is blind."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How does Calvins dad like to spend his vacation in the comic strip Calvin and Hobbes","Going Camping"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the cartoon Calvin and Hobbes, Calvin enjoys the dinners that his mom makes.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cartoon character Calvin hates taking baths.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does comic strip character Calvin like to do during recess?","None of these"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is NOT the name of one of the Calvin and Hobbes books?","The Conclusive Calvin and Hobbes"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following words is not part of the title of Calvins favorite book in the Calvin and Hobbes comic strip?","Louis"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["SeaWorld has an official airline and one of its Boeing 737 jetliners is painted to look like a flying Killer Whale. Name this airline.","Southwest"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is more than one Killer Whale named Shamu in the SeaWorld parks in the U.S.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did SeaWorld Orlando open?","1973"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these creatures is not featured in the exhibit of the world famous SeaWorld attraction Wild Arctic?","Penguin"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What SeaWorld attraction allows you to walk through a tube in which sharks swim all around you?","Shark Encounter"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the SeaWorld Orlando amusement ride that is a combination of a water ride and a roller coaster?","Journey to Atlantis"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the names of the four theme parks that make up Disney World?","Magic Kingdom, Epcot, Animal Kingdom, Disney Hollywood Studios"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many acres did Walt Disney purchase for Disney World to be built on?","27,400"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the main icon of the Magic Kingdom park?","Cinderellas Castle"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the title, given to employees at Disney World?","Cast Members"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements is a true fact about Disney World?","All of the above."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many resorts are there on the Disney World property?","32"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["World Showcase is a part of Epcot that highlights different countries and cultures. Which of the following countries is not in the Showcase?","Spain"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Twilight Tower of Terror is a free fall thrill ride located in Hollywood Studios. It is based on a television show from the 1950s. What was the name of that show?","The Twilight Zone"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the main icon of the Animal Kingdom park?","The Tree of Life"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the four parks is the largest single Disney theme park in the world?","Animal Kingdom"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dilbert from the self-titled comic strip is an engineer who graduated from MIT. What type of engineering degree does Dilbert have?","Electrical"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not one of the characters that live in Dilberts house in the comic strip Dilbert?","Catbert"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not a word/term created by Scott Adams for the comic strip Dilbert?","synergy"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the comic strip Dilbert, the real name of Dilberts pointed-haired boss is Phil.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the brother of the pointed-haired boss in the comic strip Dilbert?","Phil, Prince of Insufficient Light"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Dilberts coworker in the comic strip Dilbert, who believes he has psychic powers?","Asok"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Dilberts sometimes girlfriend in the comic strip Dilbert?","Liz"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which wrestler is famous for using a move called the Pedigree?","Triple H"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dave Animal Batistas famous ending move is called the Batista Drop.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The FU is the signature move of this wrestler, who also performs a pre-ending move called U Cant See Me.","John Cena"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which finishing move is most notably performed by Shawn Michaels?","Sweet Chin Music"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the signature finishing move performed by EDGE of SmackDown?","the Spear"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which WWE champion has two signature moves called the Swanton Bomb and the Twist of Fate?","Jeff Hardy"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the ending move used by former champion Randy Orton called?","RKO"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is The Undertakers signature finishing move?","Tombstone Pile Driver"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which former WWE champion uses a move called Codebreakerr?","Chris Jericho"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the music video game Guitar Hero 3, what is the encore song you play in the first set of songs?","Rock All Night"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are five unlockable characters in the music video game Guitar Hero 3.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many songs excluding the encores are there in Guitar Hero 3?","32"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Slash, a character in the Guitar Hero 3 music video game, is also a real life musician that became popular with which of these bands?","Guns N Roses"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Music video game Guitar Hero 3 is rated T for teen.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Choose the missing words in the following lyrics to get the name of a song from Guitar Hero 3:","Mississippi queen"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Guitar Hero 3, “Bulls on Parade by Rage Against the Machine is the third encore song.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the last boss in the music video game Guitar Hero 3?","Lou"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was the debut of the comic strip Hagar the Horrible?","1973"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Hagar the Horrible from the comic strip of the same name had his own short lived line of beer called Hagars Viking Beer which was pulled off the shelves due to lack of sales.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Shortly after its creation the Hagar the Horrible comic strips distributed to how many newspapers worldwide?","1,900"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In how many countries were the Hagar the Horrible comic strips strip distributed?","58"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many languages were the Hagar the Horrible comics printed in worldwide?","13"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of radiation was Dr. Banner exposed to that causes him to turn into the Hulk?","Gamma"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did The Incredible Hulk debut?","1962"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year saw the debut of The Incredible Hulk TV series?","1978"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1989 TV movie The Trial of he Incredible Hulk, the Hulk co-stars with what fellow superhero?","Daredevil"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who were the creators of comics superhero Aquaman?","Paul Norris and Mort Weisinger"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What famous comic book company published Aquaman Comics?","DC Comics"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aquamans enemy the Ocean Master was his own father.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did comics character Aquaman ever have a child?","Yes"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Aquamans girlfriend and eventual wife?","Mera"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these was not one of Aquamans amazing powers?","Having complete control over water"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How long could Aquaman survive out of water?","One Hour"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Comics superhero Aquaman was one of the founding members of The Justice League of America.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the comic strip FoxTrot, what is the name of the only girl in the Fox family?","Paige"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does FoxTrot character Jason ever joke that it is 25 degrees out?","No"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the comics FoxTrot, Roger Fox is writing a novel.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Does Andy and Rogers daughter get notes in her locker in FoxTrot?","Yes"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Peters girlfriend in the comics FoxTrot?","Denise"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following best describes Andy and Roger’s youngest child in the comics FoxTrot?","A nerd"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Has FoxTrot character Jason developed a plan for a Star Trek-themed amusement park?","No"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What Batman villain formerly worked as a zoologist?","ManBat"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What super villain once broke Batmans back, leaving him crippled and wheelchair-bound?","Bane"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the character of Robin first introduced?","1940"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is credited with creating Batman?","Bob Kane"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Detective Comics #267, a magical Kobold from another dimension decides to help Batman fight crime--what was his name?","Bat-Mite"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Bat-hounds name?","Ace"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What were the names of Bruce Waynes parents?","Thomas Martha"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The original Batgirl was related to what familiar Batman character?","Batwoman"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Bat-villains was introduced first?","Catwoman"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was Alfred the butlers original family name?","Beagle"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many health points does the Mountian Giant unit have?","1600"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What hero does the phrase Moonlight shines upon the guilty and the innocent alike belong to?","Naisha"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the leader of the Burning Legion?","Archimond"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the well from which Night Elfs originally obtained their magical powers?","Well of Eternity"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What hero or unit does the this phrase belong to?","Muradin Bronzebeard"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is Tyrande Whisperwind in love with?","Malfurion Stormrage"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Warcraft III:The Frozen Throne, Illidan Stormrage works for?","Kiljaeden"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the creator of Bloom County?","Berkely Brethed"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the penguin in Bloom County?","Opus"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Bloom County, Milo Bloom was a 10-year-old reporter for The Bloom Chronicle.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the hard rock band formed by lawyer Steve Dallas in the Bloom County comic strip?","Deathtongue"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who did Opus marry in the comic strip Bloom County?","Lola Granola"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Bloom County character Opus has appeared in two other comic strips titled Neverland and Opus.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of the feminist school teacher in Bloom County?","Bobbie Harlowe"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was a TV Christmas special that centered on the famous comic strip character Opus.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the comic strip Bloom County, Bill the cat became a televangelist. What was his name?","Fundamentally Oral Bill"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Andy Capp make his comic strip debut?","1957"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is NOT one of Andy Capps hobbies?","Hunting"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There was once a musical based on the Andy Capp comic strip.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who are Andy Capps best friends and neighbors?","The Whites"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What country are the Andy Capp comic strips set in?","Britain"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cartoon character Andy Capp has a son.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did the Andy Capp comic strips reach the U.S.?","1963"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these comics was the first comic Jim Davis created?","Gnorm Gnat"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did the comic strip Garfield come out?","1978"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that the comic strip Garfield inspired a CD titled Am I Cool or Not?","No"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is Garfields on and off girlfriend?","Arlene"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it true that Nermal, who makes unannounced visits into Garfields home, is a male kitten?","Yes"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the fictional dog that gets pushed around by Garfield?","Odie"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the Garfields owner on the popular comic strip?","Jon Arbuckle"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the profession of Irma, one of the supporting characters on the comic strip Garfield?","waitress"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Garfields veterinarian on the self-titled comic strip?","Liz Wilson"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This ancient circus, situated between the Palatine and Aventine hills, was both the first and the largest circus in Rome.","Circus Maximus"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the creator of the French circus, who is also thought to be one of the creators of modern circus?","Antonio Franconi"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which state did the first circus building in the USA open in 1793?","Pennsylvania"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was typical for the Cirque nouveau or the New Circus that developed in the 1970s in France, Australia, the USA.and the UK?","No animals were used."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the presenter of a traditional circus show called?","ringmaster"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["O and Ovo are among the shows performed by this circus group founded in 1984.","Cirque du Soleil"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Frenchman who invented the flying trapeze in 1859.","Jules Leotard"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which traveling circus of the early 20th century, based in Peru, Indiana, was the inspiration for Cathy Days novel The Circus in Winter?","The Hagenbeck-Wallace Circus"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is the name of an old British circus dynasty that toured Europe and the Far East with their shows?","Chipperfield"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What circus was founded in 1995 by a duo named Fireplay?","The Bindlestiff Family Cirkus"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who sidelined WWE wrestler John Cena for 4 months, because of a torn pectoral muscle?","Randy Orton"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The WWE wrestlers Jeff Hardy and Matt Hardy tag-team with each other a lot.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This Diva was one of the best WWE Divas ever, but unfortunately, she retired in 2007.","Lita"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["WWE wrestler Triple H is the brother of Stephanie McMahon.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["WWE DIVA Ashley was actually born in Los Angles, California.","No"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who did WWE wrestler Matt Hardy lose his love interest Lita to?","Edge"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When did WWE wrestler Ric Flairs career end?","March 31 2008"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At Wrestlemania 24, it came down to Y2J, Chris Jericho and CM Punk in the Money In The Bank ladder match and CM Punk won.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Marvel character Anubis is also known as The Guardian of the Veil .","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Marvel comics universe, Horus is the God of fire.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Marvel character Zeus ruled the underworld.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Seth is the Egyptian god of evil and death in the Marvel Comics universe.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what radio station do the Junkies broadcast?","WJFK"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is NOT one of the four Junkies?","Bruce The Hugger"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Johnny Cakes Auville once stayed in a coffin in order to win a bet.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to the Junkies, what is the practice of inebriated love making immediately followed by redistribution of wealth and treating your friends to breakfast called?","sturching"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["If someone well-versed in Junkies Lingo says that someone or something is a show, it is a positive thing.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Junkies ersatz nickname is The Latin Donkey?","JP"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On Fridays, Big Daddy Kev comes in for a segment on the morning Junkies show to talk about fantasy sports.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first tubular steel track roller coaster?","Matterhorn Bobsleds, Disneyland"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first amusement park with four roller coasters that are taller than 200 feet (61 m)?","Cedar Point Sandusky, Ohio, USA"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first looping roller coaster?","Centrifugal Railway, Frascati Garden, Paris"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the first roller coaster to reach a height of 100 ft?","Cyclone, Revere Beach, Revere, Massachusetts, United States"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There has never been a wooden roller coaster with an inversion.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the first modern roller coaster to have a vertical loop?","Revolution, Six Flags Magic Mountain, Valencia, California"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who is the mascot for Indiana Beach?","IB Crow"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which roller coaster was Indiana Beachs first?","Galaxy"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In addition to the sandy beach, Indiana Beach also has a large waterpark.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not a lodging option at Indiana Beach?","Time-shares"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year did Indiana Beach open?","1926"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the Shafer Queen?","River boat"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the Indiana Beach slogan?","Theres more than corn in Indiana."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Indiana Beach has a water and ski show.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of walk-through attraction at Indiana Beach was voted the worlds #1 in 2006?","a haunted house"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Judge Dredds first name?","Joseph"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Judge Dredd is 2000 ADs longest-running character, appearing from the first issue in 1977.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Judge Dredds visual appearance was loosely based on the character of Frankenstein from the film Death Race 2000.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The giant city, Mega City One, where Judge Dredd is a lawkeeper, is located in which area that we would recognise nowadays?","East coast USA"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sentence does Judge Dredd frequently utter during his duties?","I am the law!"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Judge Dredds clone-brother, who he turned in to the authorities when he began to break the law?","Rico"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Judge Dredd once lived in an apartment block named after a character from Rawhide.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following has Judge Dredd not battled against?","Daleks from the TV series Dr Who"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the film Judge Dredd, who plays the title character?","Sylvester Stallone"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In The New Batman Adventures episode Over the Edge, who does Commissioner Gordon hire to help him kill Batman?","Bane"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fictional character Batman has a son.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What issue did the Joker originally appear in?","Detective Comics #168"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Homestar Runner, what power does the blue diamond on Strong Bads mask give him?","He can mentally open Cold Ones."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Internet cartoon Homestar Runner, Strong Bad works with Homestar and The Cheat at an unnamed tech company, but what is his dream job?","2nd 2nd assistant space whale scrubber"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the fan club dedicated to Homestar Runner character Strong Bad?","The Deleteheads"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the e-mail secret recipes, Strong Bad claims he has a secret family recipe for cooking which of the following?","Chekt"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the e-mail animal, Homestar Runner character Strong Bad is asked to make-up an animal. What is NOT one of the animals that he creates?","La Mongo"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cartoon character Strong Bad got this name because he can bench-press 125 pounds.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Homestar Runner cartoon, Strong Bad and Strong Sad co-author the Teen Girl Squad comic.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which movie is this Warcraft 3 quote from?","Cool Hand Luke"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the cartoon series Calvin and Hobbes, what is Hobbes?","A stuffed tiger"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Calvins favorite subject according to the popular comics Calvin and Hobbes?","Dinosaurs"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the Calvin and Hobbes comics, Hobbes is constantly sneaking up on Calvin and pouncing on him when he doesnt expect it.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these has not been used as a ring name by Hulk Hogan?","The Bronze Bomb"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who bought the rights to the name Hulk Hogan in 2005?","Hulk Hogan"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year was Hulk Hogan inducted into the WWE Hall of Fame?","2005"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Hulk Hogans oldest daughter Cassidy refuses to be filmed on the familys reality show.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of Hulk Hogans wife, whom he married in 1983?","Linda"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Hulk Hogan has played in several rock bands.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what year did Hulk Hogan make his debut in the World Wrestling Federation?","1979"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these actors has Hulk Hogan not co-starred with?","John Ritter"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which of the Rocky movies did Hulk Hogan have a part?","Rocky III"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which video game is the following quote from?","Escape from Monkey Island"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which video game are the following quotes from?","Call of Duty"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emmett Kelly, who initially was a trapeze artist, started working as a clown in what year?","1931"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the name of Emmett Kellys son, who also played a character named Weary Willie?","Emmett Kelly Jr."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Circus performer Emmet Kelly is depicted in a famous photograph trying to put out the fire that occurred shortly after the San Francisco Earthquake in 1938.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emmett Kelly died of heart attack in 1979 at age of 80.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emmett Kelly took a year off from the stage and circus to serve as mascot for which baseball team?","Brooklyn Dodgers"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1957, Cecil B. DeMilles hired Emmett Kelly to perform in I, Clowns.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Circus performer Emmet Kelly started his trapeze act in 1923 with the John Robinson Circus.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name Emmett Kellys birth state, which is also the location of the Emmett Kelly Museum.","Kansas"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Emmett Kellys character, Weary Willie, always made fans burst out in laughter.","False"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many contestants are there in the Miss America competition each year?","52"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many years does the winner of the Miss America Pageant hold the Miss America title?","1"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did the first Miss America pageant take place?","Atlantic City, New Jersey"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Miss America Pageant is the number one provider of which of the following?","Scholarships for women in the United States"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During the talent portion of the Miss America competition the contestants perform on stage. What are the two most common talents that are exhibited?","Singing and dancing"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In 1996, a phone-in poll was held to ask the public if they should continue with the swimsuit portion of the Miss America Pageant. What percentage of voters wanted the swimsuit portion to continue?","87%"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the very first woman to win the Miss America competition?","Margaret Gorman"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the Miss America competition televised for the very first time?","1955"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who became the first African American woman to win the title of Miss America?","Vanessa Williams"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many times can a woman compete in the Miss America pageant?","1"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What hero do these words belong to: I fear no death, I fear no enemy, our","Fenix"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who created Popeye, Olive Oyl and Bluto?","Elzie C. Segar"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Olive Oyl was created before Popeye.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was the woman who was the basis for the character Olive Oyl?","Dora Paskel"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who provided the voice for Olive Oyl in the cartoons?","Mae Questel"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following movies premiered in 1948?","Olive Oyl for President"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1980 movie Popeye, which pair portrayed Popeye and Olive?","Robin Williams and Shelley Duvall"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Sweet Pea?","It is never revealed."],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Olive Oyls niece?","Diesel Oyl"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What rock group is featured in the Rock n Roller Coaster?","Aerosmith"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Dark Knight is an indoor roller coaster.","True"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who created Captain America?","Joe Simon Jack Kirby"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Captain America made his first appearance in what comic book?","Captain America Comics #1"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who was Captain Americas sidekick during World War II?","Bucky"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is Captain Americas secret identity?","Steve Rogers"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["For a brief period during the 1970s, disillusioned by U.S. politics, Captain America changed his name to ...","Nomad"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What team of superheroes discovered Captain Americas body frozen in a block of ice in 1964?","Avengers"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What villain did Captain America and Bucky fight in the very first issue of Captain America Comics?","Red Skull"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What was the original shape of Captain Americas shield?","Badge-shaped"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Who played the title role in the 1979 TV movie Captain America?","Reb Brown"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Captain Americas original sidekick was wounded in combat, who replaced him?","Golden Girl"],"tags_json":"[\"trivia\",\"entertainment\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
