{"kind":"deck","format":"deez.nut","version":2,"name":"Animals v3"}
{"kind":"note","note_type":"basic","fields":["What does the diet of wombats consist of in general?","Plants"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many babies does the female wombat give birth to every spring?","One"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unusual anatomical feature do wombats possess?","Their pouch faces backwards."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Wombats have an incredibly fast metabolism.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these wombat species is also known as Coarse-haired Wombat?","Common Wombat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What way of defence do wombats use when they feel threatened?","Kicking"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the smallest wombat species on the planet?","Southern Hairy-nosed Wombat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What should a person do to escape the attack of a wombat in the wild?","Climb a tree"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This species, also known as Yaminon, is the largest wombat species on the planet.","Northern Hairy-nosed Wombat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On which continent can you find the turltle-dove during most of the year?","Europe"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which continent does the turtle-dove migrate to in the colder winter months?","Africa"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements is true about the turtle-dove?","They are viewed as a symbol of love."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the expected lifespan of a turtle-dove?","20 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the incubation period for turtle-dove eggs?","12-14 days"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following makes the turtle-dove different from other birds?","They suck to drink instead of tilting their heads back."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The turtle-dove is closely related to the raven.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are the main colors of turtle-doves?","Brown and gray"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The name of the turtle-dove is derived from the sound it produces.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Turtle-doves tend to eat in their nests and high in the trees.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is not true about the vision of bats?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What important bone-building mineral do the cartilage of bats finger bones lack, which makes them very flexible?","Calcium"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do megabats, also called flying foxes, feed on?","Fruit and nectar"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How do most bat species spend the cold winter months?","They hibernate."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A bat is featured on the coat of arms of this Spanish city.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What status does the bat have in Chinese folklore and tradition?","It is a symbol of happiness and longevity."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What city in the US state of Texas is a home of the largest bat colony in North America during the summer?","Austin"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name is commonly used when referring to the bat species Vampyrum spectrum, also known as False Vampire Bat?","Spectral Bat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What bat species is considered the largest in the world?","Golden-capped fruit bat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What other common name is used for the Kittis Hog-nosed Bat, the smallest bat species in the world?","Bumblebee bat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["During what geological time period did the ammonites evolve?","The Devonian period"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The nautilus is the closest living relative of the ammonite.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the largest known species of ammonite, which was found in Germany in 1895.","Parapuzosia seppenradensis"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the greatest depth the shell of a nautilus can withstand before imploding?","800 meters"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Were the shells of all ammonites coiled?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the average lifespan of a nautilus?","20 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ammonites lived on the ocean floor.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Ammonites became extinct at the end of what geological period?","Cretaceous"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What flower remedy would be most beneficial to a stand-offish horse that gets irritated quickly and has a hard time accepting change?","Beech"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aspen is beneficial to a horse that is nervous and anxious, shies at invisible objects in a familiar arena and bolts for no reason.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rescue remedy is a combination of Rock Rose, Star of Bethlehem, Impatiens, Cherry Plum and Clematis essences.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["All Bach flower remedies can be used by people.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Up to how many different Bach remedies can you combine?","7"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Cerato essence is suitable for horses that withhold their emotions despite suffering from a pain or disease.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is used as a cleansing remedy?","Crab Apple"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Salix vitellina is the scientific name of this essence usually given to a horse that appears to sulk, goes into moods and refuses any sort of attention.","Willow"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animals are the colugos, or cobegos, which is found only in Asia?","Mammals"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What other name is commonly used for the Japanese Macaque, a monkey native to Japan?","Snow Monkey"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these Asian tortoise species is a very popular pet in many countries around the world?","Russian Tortoise"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the color of the legs, bill and eye rims of the Green Magpie, a small Asian bird with bright green plumage?","Red"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To which Asian country is the Giant Panda native?","China"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the smallest bat species on the planet, endemic to the Asian continent?","Kittis Hog-nosed Bat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name is used for the enigmatic bovid mammal Kting Voar, which is believed to populate Cambodia and Vietnam in Asia?","Snake-eating Cow"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sense of the Malayan Tapir, also called Asian Tapir, is underdeveloped?","Eyesight"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many horns does the Indian Rhinoceros, found only in Asia, have on its snout?","One"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the favorite food of the Fairy-bluebird, which is found only in Asia?","Figs"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term is used the denote the terrestrial stage of the development of the young newt?","Eft"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what country is the Rhinoderma rufum, a species of frog from the family Rhinodermatidae, endemic?","Chile"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal translation of the Greek word amphibios, from which the modern word amphibian originated?","Both kinds of life"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What interesting characteristic do all amphibians called caecilians share?","They have no legs."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal does the greater siren, a nocturnal amphibian, resemble externally?","An eel"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is wrong about the Glass frogs from the amphibian family Centrolenidae?","They are found mainly in Australia and Tasmania."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What other interesting name is used commonly to refer to the Purple frog, an amphibian endemic to the Western Ghats in India?","Pignose Frog"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the diet of the Eastern Tiger Salamander mainly consist of?","Insects"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What behavior is typical of the Argentine horned frog, also known as Argentine wide-mouthed frog?","It would eat up anything that comes in its eyesight."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where does the female Suriname Toad keep its eggs until they develop into young frogs?","On its back"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many orders of trilobite are there?","10"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What order of trilobite was the only one to survive the Devonian mass extinction?","Proetida"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Approximately how many species of trilobite existed over the duration of the Paleozoic?","17,000"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Trilobites developed one of the first complex visual systems.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Not all trilobites had eyes.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What genus and species did the largest complete trilobite fossil ever found belong to?","Isotelus rex"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The pygidium refers to what section of a trilobites body?","The tail"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is believed to be an ancestor of the trilobites?","Spriggina"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did some trilobites filter-feed as a means of obtaining food?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what geographical region is the Aye-aye indigenous?","Madagascar"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the lemur Aye-aye?","It is the largest nocturnal primate on the planet."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What physical feature does the lemur Aye-aye share with rodents, leading to its original classification in order Rodentia?","Very large incisors"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unusual physical characteristic does the lemur Aye-aye possess?","It has extremely long fingers."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In what places does the nocturnal Aye-aye sleep during the daytime?","On trees"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the reproduction of the Aye-aye?","None of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where did the name of the Aye-aye originate from according to common hypothesis?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How is the lemur Aye-aye classified according to its diet?","Omnivore"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the Aye-aye traditionally associated with according to ancient Malagasy legends?","Death"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the Aye-aye character from the 2005 animated comedy movie Madagascar?","Maurice"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what geographic area is the koala endemic?","Australia"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unique feature do the the fingers of the koala possess?","They have fingerprints."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the diet of the koala almost exclusively consist of?","Eucalyptus leaves"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term is used to refer to the infant koala, as well as to any other baby marsupial?","Joey"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about koalas?","They were nearly erased from the planet due to hunting in the early 20th century."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This fictional koala character, created by author Dorothy Wall, fist appeared in the 1933 book Jacko - the Broadcasting Kookaburra.","Blinky Bill"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What unusual anatomical characteristic does the koala possess?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The koala is the only animal species on the planet to possess this quality.","Its brain size is extremely reduced."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the Greek word Phascolarctos, denoting the genus to which koalas belong, mean?","Pouch bear"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When anxious, the koala produces a loud sound similar to the cry made by this creature.","Human baby"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal meaning of the word giraffe considering its Arabic origin?","Tall"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is wrong?","The giraffe is the only surviving member of its genus."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term is used for the behavior exhibited by male giraffes that are engaged in a fight?","Necking"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Giraffes sometimes use their extremely long blue tongues for this purpose.","Cleaning insects from their face"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these giraffe subspecies is easily distinguished by the very light colored spots on its body?","West African Giraffe"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The horns of which giraffes are very often bald on top?","Males"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Of all mammals, giraffes require the least amount of which of the following?","Sleep"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This artiodactyl mammal is the closest surviving relative of the giraffe.","Okapi"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest living subspecies of giraffe on the planet?","Masai Giraffe"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What method of defense do giraffes most often employ against predator attacks?","Kicking"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the name of the zebra literally mean?","Wild ass"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the senses of zebras is generally underdeveloped and the animal cannot rely very much on it?","None of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal is the number one predator of zebras?","Lion"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the term denoting a group of zebras that live together?","Harem"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Unfortunately this fictional dog is constantly bullied by his buddy cat.","Odie"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which cartoon dog is one of Mickey Mouses best friends?","Goofy"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which Rough Collie was awarded a star on the Hollywood Walk of Fame?","Lassie"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the real name of the dog who first played the fictitious dog Benji in the series of Benji films?","Higgins"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dog, whose name means barker in Russian, became the first living creature from Earth to enter orbit.","Laika"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This dog, who first showed up in a Bud Light Beer Super Bowl ad, had a black circle around one eye.","Spuds MacKenzie"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Name the Red Baron hunting Beagle from Charles Schultz popular comic strip, Peanuts.","Snoopy"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This cartoon Great Dane often needs his nephew headstrong nephew to protect him.","Scooby"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is the most distinctive feature of one of the largest marine creatures, which is also known to be the best diver - the sperm whale?","Its enormous head"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Giant squids, for long believed to be mythical creatures, are a type of deep-ocean dwelling squid that can grow to a tremendous size. The giant squid also holds the record for the largest organ, in which of these bodily systems?","Visual system"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Herman Melvilles Moby-Dick, the leading character Ahab, consumed with the desire for revenge for his lost leg, mindlessly pursues a whale nicknamed Moby Dick. What type of whale is Moby Dick, according to the book?","Sperm whale"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This member of the oceanic dolphin family, named for its versatile predatory habits, cannot be mistaken with any other sea creature, due to its distinctive coloration - black back, white chest, sides, and a patch above and behind each eye.","Killer whale"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In marine science, ichthyology, branch of zoology closely related to marine biology and oceanography, is the study of what?","Fish"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Devilfish, a large species of ray, also called manta, was named such due to which of these characteristic features?","Two pointed lobes on each side of the head"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Periplaneta americana, Blattella germanica and Gromphadorhina portentosa are all species of this insect.","Cockroach"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["It is the national insect of Canada and the state insect of Texas.","Monarch butterfly"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Many Royal Navy and US Navy ships are named after this fearful insect. Not just that, but an F/A-18 aircraft and a Honda motorcycle also carry its name.","Hornet"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The scarab, a sacred beetle to Ancient Egyptians, is commonly known as what?","Dung Beetle"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the common length of a full grown male Komodo Dragon?","9 feet"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Komodo Dragon is NOT native to which of these islands?","Savalhi"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How heavy was the largest verified wild Komodo Dragon?","365 lbs."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Komodo Dragon is venomous.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the top speed that a Komodo Dragon can reach?","13 mph"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Komodo Dragon is only one of 3 species of venomous lizards in the world.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these American zoos does NOT house Komodo Dragons?","Bronx Zoo"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Female Komodo Dragons can lay eggs without any contact with males.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How fast can a black bear run?","48 km/hour"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are all bears omnivores?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is not a nickname for a polar bear?","Great bear"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At what age can grizzly bears start to mate?","4 and a half year"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do polar bears live in Antarctica?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many years does a mother grizzly stay with her cubs?","1and a half to 3 and a half years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many polar bear subspecies are there?","0"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these animals usually preys on black bear cubs?","Cougar"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What of these members of the bear family is the largest?","Polar bear"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where do orphaned grizzly cubs Grinder and Coola live?","British Columbia"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are just 2 species of turkey in the world.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are wild turkeys very good fliers?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Turkeys are named after the country of Turkey.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many eggs does a turkey usually lay?","8-15"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Turkeys like to roost high in trees at night.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Turkeys were once threatened with extinction in America.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Did all Indian tribes of North America eat turkeys or consider them to be edible?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Male turkeys are monogamous and will stay with one female for life.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A cats sense of hearing is much more sensitive than that of a human or a dog.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How fast can a domestic cat sprint?","30 MPH"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements if true about a cat?","Their urine glows under a black light."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The nose pad of a cat is unique like the human fingerprint.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["According to a survey, what percentage of American cat owners admit to blow drying their feline after giving it a bath?","25%"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which type of cat is almost always female?","Calico"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cats have 517 of these in their entire body.","Muscles"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Indoor cats tend to live longer.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was the very first cat show held?","1895"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not one of the most popular names for female cats in the USA?","Socks"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["On what continent can aardvarks be found?","Africa"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are aardvarks an endangered species?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the scientific name for an aardvark?","Orycteropus afer"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aardvark is a word coming from the Afrikaans/Dutch that literally translates as what?","Earth Pig"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many young can an adult aardvark have at one time?","only 1"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the gestation period for an aardvark?","7 months"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are aardvarks nocturnal animals?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Aardvarks have more olfactory nerves than other mammals.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which one of these statements about aardvarks is false?","Aardvarks only eat termites."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What color was the aardvark from the Pink Panther cartoon?","Blue"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the gestation period of a dolphin?","Varies by species"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Orca (Killer Whale) is the largest species of dolphin.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is NOT a species of dolphin?","Eastern Dolphin"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Dolphins are only found in the ocean.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What year was named by the United Nations as the Year of the Dolphin?","2007"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Approximately, how many species of dolphins exist?","40"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are all dolphins considered whales?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where in the world can you find the dolphin known as the Boto?","South America"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the scientific name of the Common Raccoon?","Procyon lotor"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these in NOT a species of raccoon?","Tree Raccoon"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In Toronto, Canada the raccoon has become a great urban pest, only exceeded by the Gray Squirrel.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is the raccoon native to Europe?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are badgers related to weasels?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many young can an adult badger have at one time?","1-5"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The badger can be found in every part of the lower 48 states.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Can you find badgers in Europe?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not a part of the badgers diet?","Insects"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Badgers like to use one den all year round.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Are badgers the largest native carnivores found in the UK?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The expression badgering someone” came from the cruel sport of badger baiting.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following octopuses could most easily kill a human?","The Blue Ringed Octopus"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many hearts do most octopi have?","3"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following best defines the octopus related word midden?","a pile of shells"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Octopi live alone all their lives except when mating.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The octopus is considered the smartest invertebrate.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following is the name for an octopuss tongue?","Radula"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Octopuses have excellent vision. Which of the following statements about an octopuss vision is NOT true?","They can see in color."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following octopi has the scientific name Enteroctopus Dofleini?","Giant Pacific Octopus"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following words is NOT related to the octopus?","Tentacles"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What two continents did Smilodon inhabit?","North and South America"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How much could a full-grown Smilodon weigh?","450 lbs."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is it believed that Smilodon was a social animal?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which species of Smilodon was the largest?","Smilodon populator"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Approximately how long ago did Smilodon become extinct?","10,000 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Tomato Frog is native to the eastern coast of Madagascar.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What king of habitat do Tomato Frogs live in?","in marshes, shallow pools, flooded meadows, and wetlands"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tomato Frogs existence is threatened due to what reason?","Habitat destruction"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tomato Frogs tend to hit sexual maturity in about 9-14 months.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Male Tomato Frogs are bright red.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Female Tomato Frogs are larger than male Tomato Frogs.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When Tomato Frogs are in captivity at a zoo, what kind of food are they fed?","Vitamin-dusted crickets and mealworms."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tomato Frogs lay their eggs in the water during rainy seasons.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The life span of a Tomato Frog is 15-35 years.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When the Tomato Frog is threatened its skin secretes a thick substance containing a toxin.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The manatee is a marine mammal.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The manatee has a tail similar in shape to that of the dolphin.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Manatees range in weight from 900 to 1200 pounds (400-550 kg.)","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Manatees are found more commonly in Caribbean, Mexico, and Florida waters. Why?","The water is warm."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these do manatees use to communicate with their calves and other manatees?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Due to the presence of a specific protein in the blood plasma octopuses have this unusual blood color.","Blue"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Some animals have an inborn instinct to swallow gastroliths in order to improve the breaking down of food inside their stomachs. What kind of objects are gastroliths?","Rocks"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Parthenogenesis (from Greek - virgin creation), an asexual way of reproduction without the need of fertilization, occurs naturally in these animals.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements is true about mosquitoes?","Only female mosquitoes suck blood."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of respiratory organs do lungfish have?","They have both lungs and gills."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Cockroaches are among the most resilient creatures on our planet. But how long can they survive without air?","45 minutes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Human skin has the unique ability to acquire a darker shade when exposed to UV-rays. What animals share this ability with us?","Pigs and hammerhead sharks"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Koalas almost exclusively feed on this type of food.","Eucalyptus leaves"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements is true about snails?","Snails do have tooth-like formations."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Some sharks hardly ever stop swimming during their whole existence. What is the reason for this?","Some sharks have lost the ability to pump water through their gills, so they need to keep moving in order to stay alive"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Mimic Leatherjacket, found in the tropical marine waters throughout the Indo-Pacific, mimics which poisonous fish?","Saddled Puffer"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This primitive shark, with a brown thin eel-like body, has six pairs of gill slits and trident-like teeth.","Frilled shark"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This fish, which resembles the Angel fish, is recognized by its brightly coloured and patterned body, as well as by the dark band across its eyes.","Butterfly fish"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Parrot fish, found in the Atlantic Indian and Pacific Ocean reefs, was given its name for what reason?","Because of its beak-like mouth"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the other name of Mola mola, a fish generally considered to be the most massive bony fish in the world?","Ocean Sunfish"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When threatened, this fish, also known as balloonfish, increases in size by swallowing water or air.","Porcupinefish"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The zebrafish (Girella zebra), which can be recognised by its pale body and yellow fins, is endemic to which region?","Australian waters"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Flashlight fish, has a light-producing organ, which contains luminescent bacteria. Where is this organ located?","Below the eye of the fish"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The catfishes Physailia pellucida and Kryptopterus bicirrhis, found in the mid-waters of Southeast Asia, use what kind of camouflage?","Transparency"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Giant Pandas eat oranges and bananas.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is the Giant Panda an endangered species?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Giant Panda and which of the following serve as an Asian countrys national emblem?","The dragon"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Do Giant Pandas hibernate?","No"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the gestation period of the Giant Panda?","95-160 days"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This animal is the second most expensive for zoos to maintain after the Giant Panda.","Elephant"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The giant pandas diet is 99% this.","bamboo"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pandas live in the mountains in the Sichuan, Shaanxi, and Gansu provinces in this country.","China"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["At birth, pandas weigh about 4 ounces and are the size of a stick of butter. Which of these is NOT true about a newborn panda?","They are grey in color."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pandas do not hibernate.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pandas live and travel together.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pandas spend 10-16 hours a day eating, the rest of the time they are usually resting. When are pandas most active?","at dusk and at dawn"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["When a panda is born, it is impossible to tell if it is male or female. How old is the panda before its gender is known?","4 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is TRUE about pandas?","They are carnivores."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How long does a panda usually live in captivity?","20 - 30 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The panda is the symbol of this conservation organization, formed in 1961.","The World Wildlife Fund"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The panda has an enlarged wristbone that works as an opposable thumb.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Pandas are known to roar.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In the 1930s movie King Kong, the giant ape battles a pterodactyl.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many stomachs does a starfish have?","2"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A starfish cannot regenerate a lost arm.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["All starfish have 5 arms.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In which country is the Gohongaze Starfish considered an edible delicacy?","Japan"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Starfish are capable of both asexual and sexual reproduction.","True"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Starfish are fast moving creatures.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["A starfish is a type of fish.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There are two classes of starfish. Name them.","Sea Star and Brittle Stars"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these is not a relative of the starfish?","Sea Horse"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is located on the end of every arm of a starfish?","Eye"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scorpions are active at night in order to avoid which of their predators?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Raccoons are usually nocturnal animals, and they are famous for dousing their food before eating it. This is actually an activity that imitates foraging for food at shores. What is the term for such an activity?","Vacuum activity"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What sense helps kiwis find food in the dark?","Sense of smell"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Kakapo is a nocturnal parrot indigenous to New Zealand. Due to its resemblance to this nocturnal animal, it is also called by its name.","Owl"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Mink are mainly active at night and they do not hibernate. Which of these animals is a predator of the American Mink?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What animal is the largest nocturnal prosimian on the planet?","Aye-aye"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Catfish are bony fish that are active in the nighttime. How did they get their interesting name?","They have barbels that remind of cat whiskers."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Fireflies are known for their ability to produce light of this color.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The Ocelot is a nocturnal cat that is also called by this name in certain regions.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Tapeti is a nocturnal cottontail rabbit that is indigenous to these areas.","Central and South America"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the average speed dolphins can reach?","16.5 km/hr"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How deep can a bottlenose dolphin dive?","300 meters"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How many different species of dolphins are there in the world?","32"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Is dolphins sense of hearing superior to that of humans?","Yes"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How do dolphins generally sleep if they are in the wild?","with only one brain hemisphere in slow-wave sleep"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which is the smallest species of dolphin?","Maui Dolphin/Hectors Dolphin"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about squirrels?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the tongue of the giraffe?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about elephants?","They are able to digest 40% of their food."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about grasshoppers?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these foods does the Canada goose include in its diet?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the digestive system of the Hoatzin, a herbivorous tropical bird?","It breaks down its food through bacterial fermentation."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the meaning of the term graminivore?","an animal that feeds on grass"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of herbivorous animals are the granivores?","Animals that feed on seeds"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the diet of Green iguanas?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the diet of the Sumatran rhinoceros?","It feeds mainly in the morning and before dusk."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which continents does the natural habitat of the jaguar span upon?","North and South America"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The jaguars extremely powerful bite, which can pierce through a turtles shell, makes it the mammal with the strongest jaw in the animal kingdom.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of the following statements is not true about the reproduction of jaguars?","Both males and females provide parenting of the cubs."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["How can jaguars be described in terms of social activity?","Solitary"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In jaguars society only male animals hunt while females look after the cubs.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["All but one of the following activities are generally untypical for jaguars. Choose the one most natural to them.","Stalking and ambushing their prey"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["In nature adult jaguars are apex predators in the food chain. What does this mean?","They are not preyed on by other predators."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The jaguar is the national animal of which of the following countries?","Brasil"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jaguars closely resemble which other big cats in physical appearance?","Leopard"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Jaguars appearance seems to vary across regions and habitats. How do forest jaguars differ from the jaguars in open areas?","Forest jaguars are generally darker and smaller"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What continent does the large Griffon Vulture inhabit?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What common name is used to refer to the scavenging animals, representatives of the order Opiliones?","Harvestmen"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal meaning of the word raccoon, which originates from the Algonquin word ahrah-koon-em and denotes a scavenging mammal?","One who rubs, scrubs and scratches with its hands"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term is mainly used in literature to refer to a group of crows?","A murder"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What term refers to the animal that is the result of crossbreeding between a male coyote and a female dog?","Coydog"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What do the beetles from the genus Nicrophorus do after finding a carcass?","They bury it."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What hyena species is the largest surviving on the planet?","Spotted Hyena"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of animals are the Yellow jackets, the scavenging and predatory animals belonging to the genera Vespula and Dolichovespula?","Wasps"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lions may be skilled predators, but they would also eat carrion. What animal is the lions preferred food?","Wildebeest"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these names is commonly used for the carrion flies, belonging to the family Calliphoridae?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The diet of most parrots consists of this type of food.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the parrots breeding habits?","Parrots are monogamous."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the color of the eggs of all parrot species?","White"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Parrots are considered the most intelligent birds on the planet along with these birds.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["These parrots are believed to be the best at imitating sounds and human speech.","African Grey Parrot"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Larger parrot species have longer life spans than smaller ones. What is the average life span of a large parrot?","Up to 80 years"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the predominant color in Amazon Parrots plumage?","Green"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["The heaviest parrot species on the planet is the Kakapo. What is the average weight that a normal mature Kakapo can reach?","2 to 4 kg"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these makes Cockatoos different from other parrot species?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Lories and lorikeets have special tongues with brush-like tips for feeding on very small insects.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This cat breed has a wild markings and is a crossbreed between an Asian Leopard Cat and a domestic cat.","Bengal"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This old breed of cat has long fur. It originated in the Middle East, and some of its representatives have a flat face.","Persian"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This hairless cat has a dog-like face and folded ears.","Ukrainian Levkoy"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This large cat was is the result of crossbreeding between a domestic cat and a Jungle Cat.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This cat breed originated in Russia and has a short fluffy tail.","Kurilian Bobtail"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This cat breed is believed to have developed naturally in China. It has short golden brown fur with the so-called broken striped pattern and a large strong body.","Dragon Li"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What cat breed, also called the Greyhound of the cats, has no hair except for down?","Cornish Rex"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What cat breed has very thick short fur, large round eyes, round head and chubby cheeks?","British Shorthair"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This breed of cat has a round head, large round eyes and very small ears bended forward and downward.","Scottish Fold"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["This old large cat breed occurred naturally in Europe. It has waterproof thick fluffy fur and can survive very cold weather.","Norwegian Forest Cat"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name of the communities formed by rabbits living together?","Warrens"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the difference between rabbits and hares?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the digestive tract of rabbits?","They are hindgut digesters."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the common name of cecotropes, products of the cecum which rabbits reingest to get nutrients?","Night feces"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Rabbits vomit often to get rid of whatever their stomach is unable to digest.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these types of food do rabbits prefer to include in their daily diet?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is true about the behavior of rabbits?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the name used for young rabbits?","Kittens"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What are rabbits associated with in Aztec mythology?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the place of rabbits in Japanese tradition and mythology?","They are believed to inhabit the Moon."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scorpions are not found naturally in this geographical area.","New Zealand"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What name is used to refer to the scorpion species also known as Omdurman scorpion, and Israeli desert scorpion?","Deathstalker"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scorpions are known to glow when exposed to this type of light.","Blacklight"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What distinctive anatomical characteristic do the scorpions from the Hemiscorpiidae family possess, which makes them easily recognizable?","Their body is flat and broad."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["There is a separate species of scorpions which have two tails, with a venomous sting on each tail.","False"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Where does the female scorpion raise its young?","On her back"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Which of these statements is wrong about the reproduction of scorpions?","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the diet of scorpions usually consist of?","Insects"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What type of behavior is characteristic of scorpion species?","Photophobic behavior"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Scorpion venom is regarded as a potential source of chemicals that can be used in the treatment of this disease.","All of these"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What common name is used to refer to the insects from the subfamily Triatominae, mainly found in the Americas?","Kissing bugs"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the largest extant butterfly species on the planet?","Queen Alexandras Birdwing"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["Why were the insects known as snakeflies given this interesting name?","Their body is elongated."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What distinctive anatomical feature does the beetle species Trogodendron fasciculatum possess?","Bright yellow antennae"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What does the flamboyant flower beetle, also known as striped love beetle, feed on?","Nectar"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What belief about the European hornet, the largest European eusocial wasp, is widespread among the people who are afraid of it?","Three stings can kill an adult human, and seven can kill a horse."],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["To what geographical area is the Ctenomorphodes chronus, a species of stick insect, endemic?","Australia"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What kind of substance does the female redeye cicada prefer for laying eggs into?","Plant tissue"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What part of their body do the insects from order Archaeognatha use to spring up into the air?","Tail"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
{"kind":"note","note_type":"basic","fields":["What is the literal translation of the Greek word Embioptera, which denotes an order of insects, also known as webspinners?","Lively wings"],"tags_json":"[\"trivia\",\"animals\",\"source:open-trivia-qa\",\"license:cc-by-sa-4.0\"]"}
